# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nicholas\Documents\GitHub\PYSAT\src\New PYSAT_Gui\mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class pysat_ui(object):
    def createmodels(self, MainWindow):
        self.CreateModels = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CreateModels.setFont(font)
        self.CreateModels.setObjectName(_fromUtf8("CreateModels"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.CreateModels)
        self.verticalLayout_17.setMargin(11)
        self.verticalLayout_17.setSpacing(6)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setMargin(11)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setMargin(11)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_70 = QtGui.QLabel(self.CreateModels)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.verticalLayout_18.addWidget(self.label_70)
        self.label_71 = QtGui.QLabel(self.CreateModels)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.verticalLayout_18.addWidget(self.label_71)
        self.label_72 = QtGui.QLabel(self.CreateModels)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.verticalLayout_18.addWidget(self.label_72)
        self.label_73 = QtGui.QLabel(self.CreateModels)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.verticalLayout_18.addWidget(self.label_73)
        self.horizontalLayout_14.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setMargin(11)
        self.verticalLayout_19.setSpacing(6)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.create_model_spin = QtGui.QSpinBox(self.CreateModels)
        self.create_model_spin.setMaximum(20)
        self.create_model_spin.setObjectName(_fromUtf8("create_model_spin"))
        self.verticalLayout_19.addWidget(self.create_model_spin)
        self.create_model_spin_2 = QtGui.QSpinBox(self.CreateModels)
        self.create_model_spin_2.setMaximum(20)
        self.create_model_spin_2.setObjectName(_fromUtf8("create_model_spin_2"))
        self.verticalLayout_19.addWidget(self.create_model_spin_2)
        self.create_model_spin_3 = QtGui.QSpinBox(self.CreateModels)
        self.create_model_spin_3.setMaximum(20)
        self.create_model_spin_3.setObjectName(_fromUtf8("create_model_spin_3"))
        self.verticalLayout_19.addWidget(self.create_model_spin_3)
        self.create_model_spin_4 = QtGui.QSpinBox(self.CreateModels)
        self.create_model_spin_4.setMaximum(20)
        self.create_model_spin_4.setObjectName(_fromUtf8("create_model_spin_4"))
        self.verticalLayout_19.addWidget(self.create_model_spin_4)
        self.horizontalLayout_14.addLayout(self.verticalLayout_19)
        self.verticalLayout_17.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setMargin(11)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_74 = QtGui.QLabel(self.CreateModels)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_15.addWidget(self.label_74)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setMargin(11)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_75 = QtGui.QLabel(self.CreateModels)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.horizontalLayout_16.addWidget(self.label_75)
        self.label_76 = QtGui.QLabel(self.CreateModels)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.horizontalLayout_16.addWidget(self.label_76)
        self.label_77 = QtGui.QLabel(self.CreateModels)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.horizontalLayout_16.addWidget(self.label_77)
        self.label_78 = QtGui.QLabel(self.CreateModels)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.horizontalLayout_16.addWidget(self.label_78)
        self.label_79 = QtGui.QLabel(self.CreateModels)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.horizontalLayout_16.addWidget(self.label_79)
        self.label_83 = QtGui.QLabel(self.CreateModels)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.horizontalLayout_16.addWidget(self.label_83)
        self.label_84 = QtGui.QLabel(self.CreateModels)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.horizontalLayout_16.addWidget(self.label_84)
        self.label_88 = QtGui.QLabel(self.CreateModels)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.horizontalLayout_16.addWidget(self.label_88)
        self.label_89 = QtGui.QLabel(self.CreateModels)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.horizontalLayout_16.addWidget(self.label_89)
        self.label_90 = QtGui.QLabel(self.CreateModels)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.horizontalLayout_16.addWidget(self.label_90)
        self.label_91 = QtGui.QLabel(self.CreateModels)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.horizontalLayout_16.addWidget(self.label_91)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.verticalLayout_17.addLayout(self.horizontalLayout_15)
        self.verticalLayout_8.addWidget(self.CreateModels)
        self.CreateModels.setTitle(_translate("MainWindow", "Create Models", None))
        self.label_70.setText(_translate("MainWindow", "Value 1", None))
        self.label_71.setText(_translate("MainWindow", "Value 2", None))
        self.label_72.setText(_translate("MainWindow", "Value 3", None))
        self.label_73.setText(_translate("MainWindow", "Value 4", None))
        self.label_74.setText(_translate("MainWindow", "ncs", None))
        self.label_75.setText(_translate("MainWindow", "[", None))
        self.label_76.setText(_translate("MainWindow", "(", None))
        self.label_77.setText(_translate("MainWindow", "0", None))
        self.label_78.setText(_translate("MainWindow", ",", None))
        self.label_79.setText(_translate("MainWindow", "0", None))
        self.label_83.setText(_translate("MainWindow", ",", None))
        self.label_84.setText(_translate("MainWindow", "0", None))
        self.label_88.setText(_translate("MainWindow", ",", None))
        self.label_89.setText(_translate("MainWindow", "0", None))
        self.label_90.setText(_translate("MainWindow", ")", None))
        self.label_91.setText(_translate("MainWindow", "]", None))


        QtCore.QObject.connect(self.create_model_spin_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_79.setNum)
        QtCore.QObject.connect(self.create_model_spin, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_77.setNum)
        QtCore.QObject.connect(self.create_model_spin_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_84.setNum)
        QtCore.QObject.connect(self.create_model_spin_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_89.setNum)

