from tests import test_BaselineRemoval
from tests import test_MainWindow
from tests import test_MaskData
from tests import test_MultiplyByVector
from tests import test_Normalization
from tests import test_OutputFolder
from tests import test_PeakAreas
from tests import test_Plot
from tests import test_PlotSpectra
from tests import test_Plot_ICA_PCA
from tests import test_ReadChemCamData
from tests import test_RegressionPredict
from tests import test_RegressionTrain
from tests import test_RemoveRows
from tests import test_RenameData
from tests import test_SplitDataset
from tests import test_StratifiedFolds
from tests import test_SubmodelPredict
from tests import test_WriteToCSV
