# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nfinch\Documents\GitHub\PySAT\src\PYSAT_Gui_UI_Forms\02_mainwindow_no_test_folds.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(581, 843)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_9.setMargin(11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.scrollArea = QtGui.QScrollArea(self.centralWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 561, 721))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.scrollAreaWidgetContents_2.setFont(font)
        self.scrollAreaWidgetContents_2.setStyleSheet(_fromUtf8("QGroupBox {\n"
"  border: 2px solid gray;\n"
"  border-radius: 6px;\n"
"  margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"\n"
"  padding-top: -14px;\n"
"  padding-left: 8px;\n"
"}\n"
""))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.setMargin(11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.unknownData = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.unknownData.setFont(font)
        self.unknownData.setObjectName(_fromUtf8("unknownData"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.unknownData)
        self.verticalLayout_6.setMargin(11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.unknownData)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lineEdit_2 = QtGui.QLineEdit(self.unknownData)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setMargin(11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.unknownDataButton = QtGui.QToolButton(self.unknownData)
        self.unknownDataButton.setObjectName(_fromUtf8("unknownDataButton"))
        self.verticalLayout_5.addWidget(self.unknownDataButton)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addWidget(self.unknownData)
        self.referenceData = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.referenceData.setFont(font)
        self.referenceData.setObjectName(_fromUtf8("referenceData"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.referenceData)
        self.verticalLayout_15.setMargin(11)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setMargin(11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setMargin(11)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_8 = QtGui.QLabel(self.referenceData)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_16.addWidget(self.label_8)
        self.horizontalLayout_11.addLayout(self.verticalLayout_16)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setMargin(11)
        self.verticalLayout_20.setSpacing(6)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.lineEdit_9 = QtGui.QLineEdit(self.referenceData)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.verticalLayout_20.addWidget(self.lineEdit_9)
        self.horizontalLayout_11.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setMargin(11)
        self.verticalLayout_21.setSpacing(6)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.fullDataBaseButton_3 = QtGui.QToolButton(self.referenceData)
        self.fullDataBaseButton_3.setObjectName(_fromUtf8("fullDataBaseButton_3"))
        self.verticalLayout_21.addWidget(self.fullDataBaseButton_3)
        self.horizontalLayout_11.addLayout(self.verticalLayout_21)
        self.verticalLayout_15.addLayout(self.horizontalLayout_11)
        self.verticalLayout_8.addWidget(self.referenceData)
        self.Normalization = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Normalization.setFont(font)
        self.Normalization.setObjectName(_fromUtf8("Normalization"))
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.Normalization)
        self.verticalLayout_27.setMargin(11)
        self.verticalLayout_27.setSpacing(6)
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setMargin(11)
        self.verticalLayout_26.setSpacing(6)
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.norm_label = QtGui.QLabel(self.Normalization)
        self.norm_label.setObjectName(_fromUtf8("norm_label"))
        self.horizontalLayout_2.addWidget(self.norm_label)
        self.norm_spinBox_9 = QtGui.QSpinBox(self.Normalization)
        self.norm_spinBox_9.setMaximum(1000)
        self.norm_spinBox_9.setObjectName(_fromUtf8("norm_spinBox_9"))
        self.horizontalLayout_2.addWidget(self.norm_spinBox_9)
        self.norm_spinBox = QtGui.QSpinBox(self.Normalization)
        self.norm_spinBox.setMaximum(1000)
        self.norm_spinBox.setObjectName(_fromUtf8("norm_spinBox"))
        self.horizontalLayout_2.addWidget(self.norm_spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_26.addLayout(self.verticalLayout_2)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setMargin(11)
        self.verticalLayout_22.setSpacing(6)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setMargin(11)
        self.horizontalLayout_24.setSpacing(6)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.norm_label_8 = QtGui.QLabel(self.Normalization)
        self.norm_label_8.setObjectName(_fromUtf8("norm_label_8"))
        self.horizontalLayout_24.addWidget(self.norm_label_8)
        self.norm_spinBox_16 = QtGui.QSpinBox(self.Normalization)
        self.norm_spinBox_16.setMaximum(1000)
        self.norm_spinBox_16.setObjectName(_fromUtf8("norm_spinBox_16"))
        self.horizontalLayout_24.addWidget(self.norm_spinBox_16)
        self.norm_spinBox_8 = QtGui.QSpinBox(self.Normalization)
        self.norm_spinBox_8.setMaximum(1000)
        self.norm_spinBox_8.setObjectName(_fromUtf8("norm_spinBox_8"))
        self.horizontalLayout_24.addWidget(self.norm_spinBox_8)
        self.verticalLayout_22.addLayout(self.horizontalLayout_24)
        self.verticalLayout_26.addLayout(self.verticalLayout_22)
        self.verticalLayout_27.addLayout(self.verticalLayout_26)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setMargin(11)
        self.horizontalLayout_25.setSpacing(6)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem)
        self.NormValuebutton = QtGui.QPushButton(self.Normalization)
        self.NormValuebutton.setObjectName(_fromUtf8("NormValuebutton"))
        self.horizontalLayout_25.addWidget(self.NormValuebutton)
        self.verticalLayout_27.addLayout(self.horizontalLayout_25)
        self.verticalLayout_8.addWidget(self.Normalization)
        self.CrossValidation = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CrossValidation.setFont(font)
        self.CrossValidation.setObjectName(_fromUtf8("CrossValidation"))
        self.CrossValid = QtGui.QVBoxLayout(self.CrossValidation)
        self.CrossValid.setMargin(11)
        self.CrossValid.setSpacing(6)
        self.CrossValid.setObjectName(_fromUtf8("CrossValid"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setMargin(11)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_14 = QtGui.QLabel(self.CrossValidation)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_11.addWidget(self.label_14)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setMargin(11)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.elementNameLine = QtGui.QLineEdit(self.CrossValidation)
        self.elementNameLine.setObjectName(_fromUtf8("elementNameLine"))
        self.verticalLayout_12.addWidget(self.elementNameLine)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.CrossValid.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8.addWidget(self.CrossValidation)
        self.CompRanges = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CompRanges.setFont(font)
        self.CompRanges.setObjectName(_fromUtf8("CompRanges"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.CompRanges)
        self.verticalLayout_7.setMargin(11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_80 = QtGui.QLabel(self.CompRanges)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.horizontalLayout_3.addWidget(self.label_80)
        self.comp_range = QtGui.QSpinBox(self.CompRanges)
        self.comp_range.setMinimum(-100)
        self.comp_range.setMaximum(1000)
        self.comp_range.setObjectName(_fromUtf8("comp_range"))
        self.horizontalLayout_3.addWidget(self.comp_range)
        self.comp_range_2 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_2.setMaximum(1000)
        self.comp_range_2.setObjectName(_fromUtf8("comp_range_2"))
        self.horizontalLayout_3.addWidget(self.comp_range_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setMargin(11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_81 = QtGui.QLabel(self.CompRanges)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.horizontalLayout_5.addWidget(self.label_81)
        self.comp_range_3 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_3.setMaximum(1000)
        self.comp_range_3.setObjectName(_fromUtf8("comp_range_3"))
        self.horizontalLayout_5.addWidget(self.comp_range_3)
        self.comp_range_4 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_4.setMaximum(1000)
        self.comp_range_4.setObjectName(_fromUtf8("comp_range_4"))
        self.horizontalLayout_5.addWidget(self.comp_range_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setMargin(11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_82 = QtGui.QLabel(self.CompRanges)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.horizontalLayout_7.addWidget(self.label_82)
        self.comp_range_5 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_5.setMaximum(1000)
        self.comp_range_5.setObjectName(_fromUtf8("comp_range_5"))
        self.horizontalLayout_7.addWidget(self.comp_range_5)
        self.comp_range_6 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_6.setMaximum(1000)
        self.comp_range_6.setObjectName(_fromUtf8("comp_range_6"))
        self.horizontalLayout_7.addWidget(self.comp_range_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setMargin(11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_85 = QtGui.QLabel(self.CompRanges)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.horizontalLayout_10.addWidget(self.label_85)
        self.comp_range_7 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_7.setMaximum(1000)
        self.comp_range_7.setObjectName(_fromUtf8("comp_range_7"))
        self.horizontalLayout_10.addWidget(self.comp_range_7)
        self.comp_range_8 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_8.setMaximum(1000)
        self.comp_range_8.setObjectName(_fromUtf8("comp_range_8"))
        self.horizontalLayout_10.addWidget(self.comp_range_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setMargin(11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_40 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_9.addWidget(self.label_40)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setMargin(11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_20 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_6.addWidget(self.label_20)
        self.label_21 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_6.addWidget(self.label_21)
        self.label_22 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_6.addWidget(self.label_22)
        self.label_23 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_6.addWidget(self.label_23)
        self.label_24 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_6.addWidget(self.label_24)
        self.label_27 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_6.addWidget(self.label_27)
        self.label_29 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_6.addWidget(self.label_29)
        self.label_28 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_6.addWidget(self.label_28)
        self.label_26 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_6.addWidget(self.label_26)
        self.label_25 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_6.addWidget(self.label_25)
        self.label_32 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_6.addWidget(self.label_32)
        self.label_30 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_6.addWidget(self.label_30)
        self.label_33 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_6.addWidget(self.label_33)
        self.label_34 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_6.addWidget(self.label_34)
        self.label_31 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_6.addWidget(self.label_31)
        self.label_39 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_6.addWidget(self.label_39)
        self.label_36 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_6.addWidget(self.label_36)
        self.label_37 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_6.addWidget(self.label_37)
        self.label_35 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_6.addWidget(self.label_35)
        self.label_38 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_6.addWidget(self.label_38)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayout_8.addWidget(self.CompRanges)
        self.CreateModels = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CreateModels.setFont(font)
        self.CreateModels.setObjectName(_fromUtf8("CreateModels"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.CreateModels)
        self.verticalLayout_17.setMargin(11)
        self.verticalLayout_17.setSpacing(6)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setMargin(11)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setMargin(11)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_70 = QtGui.QLabel(self.CreateModels)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.verticalLayout_18.addWidget(self.label_70)
        self.label_71 = QtGui.QLabel(self.CreateModels)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.verticalLayout_18.addWidget(self.label_71)
        self.label_72 = QtGui.QLabel(self.CreateModels)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.verticalLayout_18.addWidget(self.label_72)
        self.label_73 = QtGui.QLabel(self.CreateModels)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.verticalLayout_18.addWidget(self.label_73)
        self.horizontalLayout_14.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setMargin(11)
        self.verticalLayout_19.setSpacing(6)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.create_model_spin = QtGui.QSpinBox(self.CreateModels)
        self.create_model_spin.setMaximum(20)
        self.create_model_spin.setObjectName(_fromUtf8("create_model_spin"))
        self.verticalLayout_19.addWidget(self.create_model_spin)
        self.create_model_spin_2 = QtGui.QSpinBox(self.CreateModels)
        self.create_model_spin_2.setMaximum(20)
        self.create_model_spin_2.setObjectName(_fromUtf8("create_model_spin_2"))
        self.verticalLayout_19.addWidget(self.create_model_spin_2)
        self.create_model_spin_3 = QtGui.QSpinBox(self.CreateModels)
        self.create_model_spin_3.setMaximum(20)
        self.create_model_spin_3.setObjectName(_fromUtf8("create_model_spin_3"))
        self.verticalLayout_19.addWidget(self.create_model_spin_3)
        self.create_model_spin_4 = QtGui.QSpinBox(self.CreateModels)
        self.create_model_spin_4.setMaximum(20)
        self.create_model_spin_4.setObjectName(_fromUtf8("create_model_spin_4"))
        self.verticalLayout_19.addWidget(self.create_model_spin_4)
        self.horizontalLayout_14.addLayout(self.verticalLayout_19)
        self.verticalLayout_17.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setMargin(11)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_74 = QtGui.QLabel(self.CreateModels)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_15.addWidget(self.label_74)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setMargin(11)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_75 = QtGui.QLabel(self.CreateModels)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.horizontalLayout_16.addWidget(self.label_75)
        self.label_76 = QtGui.QLabel(self.CreateModels)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.horizontalLayout_16.addWidget(self.label_76)
        self.label_77 = QtGui.QLabel(self.CreateModels)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.horizontalLayout_16.addWidget(self.label_77)
        self.label_78 = QtGui.QLabel(self.CreateModels)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.horizontalLayout_16.addWidget(self.label_78)
        self.label_79 = QtGui.QLabel(self.CreateModels)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.horizontalLayout_16.addWidget(self.label_79)
        self.label_83 = QtGui.QLabel(self.CreateModels)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.horizontalLayout_16.addWidget(self.label_83)
        self.label_84 = QtGui.QLabel(self.CreateModels)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.horizontalLayout_16.addWidget(self.label_84)
        self.label_88 = QtGui.QLabel(self.CreateModels)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.horizontalLayout_16.addWidget(self.label_88)
        self.label_89 = QtGui.QLabel(self.CreateModels)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.horizontalLayout_16.addWidget(self.label_89)
        self.label_90 = QtGui.QLabel(self.CreateModels)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.horizontalLayout_16.addWidget(self.label_90)
        self.label_91 = QtGui.QLabel(self.CreateModels)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.horizontalLayout_16.addWidget(self.label_91)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.verticalLayout_17.addLayout(self.horizontalLayout_15)
        self.verticalLayout_8.addWidget(self.CreateModels)
        self.N_Folds = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.N_Folds.setFont(font)
        self.N_Folds.setObjectName(_fromUtf8("N_Folds"))
        self.CrossValid_2 = QtGui.QVBoxLayout(self.N_Folds)
        self.CrossValid_2.setMargin(11)
        self.CrossValid_2.setSpacing(6)
        self.CrossValid_2.setObjectName(_fromUtf8("CrossValid_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setMargin(11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setMargin(11)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_15 = QtGui.QLabel(self.N_Folds)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_13.addWidget(self.label_15)
        self.horizontalLayout_8.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setMargin(11)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.n_folds_spinBox = QtGui.QSpinBox(self.N_Folds)
        self.n_folds_spinBox.setObjectName(_fromUtf8("n_folds_spinBox"))
        self.verticalLayout_14.addWidget(self.n_folds_spinBox)
        self.horizontalLayout_8.addLayout(self.verticalLayout_14)
        self.CrossValid_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_8.addWidget(self.N_Folds)
        self.CrossValidation.raise_()
        self.CreateModels.raise_()
        self.Normalization.raise_()
        self.CompRanges.raise_()
        self.unknownData.raise_()
        self.referenceData.raise_()
        self.N_Folds.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.addWidget(self.scrollArea)
        self.OK = QtGui.QGroupBox(self.centralWidget)
        self.OK.setObjectName(_fromUtf8("OK"))
        self.ok = QtGui.QHBoxLayout(self.OK)
        self.ok.setMargin(11)
        self.ok.setSpacing(6)
        self.ok.setObjectName(_fromUtf8("ok"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ok.addItem(spacerItem1)
        self.okButton = QtGui.QPushButton(self.OK)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.okButton.setFont(font)
        self.okButton.setMouseTracking(False)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.ok.addWidget(self.okButton)
        self.verticalLayout_9.addWidget(self.OK)
        self.scrollArea.raise_()
        self.OK.raise_()
        self.CrossValidation.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
