


        MainWindow.resize(666, 500)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 642, 352))
        self.scrollAreaWidgetContents_2.setStyleSheet("QGroupBox {\n"
"                                    border: 2px solid gray;\n"
"                                    border-radius: 6px;\n"
"                                    margin-top: 0.5em;\n"
"                                    }\n"
"\n"
"                                    QGroupBox::title {\n"
"\n"
"                                    padding-top: -14px;\n"
"                                    padding-left: 8px;\n"
"                                    }\n"
        self.scatter = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        font.setPointSize(10)
        self.scatter.setFont(font)
        self.scatter.setObjectName("scatter")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scatter)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scatter_vlayout = QtWidgets.QVBoxLayout()
        self.scatter_vlayout.setContentsMargins(11, 11, 11, 11)
        self.scatter_vlayout.setSpacing(6)
        self.scatter_vlayout.setObjectName("scatter_vlayout")
        self.scatter_choosedata_hlayout = QtWidgets.QHBoxLayout()
        self.scatter_choosedata_hlayout.setContentsMargins(11, 11, 11, 11)
        self.scatter_choosedata_hlayout.setSpacing(6)
        self.scatter_choosedata_hlayout.setObjectName("scatter_choosedata_hlayout")
        self.scatter_choosedata_label = QtWidgets.QLabel(self.scatter)
        self.scatter_choosedata_label.setObjectName("scatter_choosedata_label")
        self.scatter_choosedata_hlayout.addWidget(self.scatter_choosedata_label)
        self.scatter_choosedata = QtWidgets.QComboBox(self.scatter)
        self.scatter_choosedata.setIconSize(QtCore.QSize(50, 20))
        self.scatter_choosedata.setObjectName("scatter_choosedata")
        self.scatter_choosedata.addItem("")
        self.scatter_choosedata.addItem("")
        self.scatter_choosedata_hlayout.addWidget(self.scatter_choosedata)
        self.figname_label = QtWidgets.QLabel(self.scatter)
        self.figname_label.setObjectName("figname_label")
        self.scatter_choosedata_hlayout.addWidget(self.figname_label)
        self.figname_text = QtWidgets.QLineEdit(self.scatter)
        self.figname_text.setObjectName("figname_text")
        self.scatter_choosedata_hlayout.addWidget(self.figname_text)
        self.plot_title_label = QtWidgets.QLabel(self.scatter)
        self.plot_title_label.setObjectName("plot_title_label")
        self.scatter_choosedata_hlayout.addWidget(self.plot_title_label)
        self.plot_title_text = QtWidgets.QLineEdit(self.scatter)
        self.plot_title_text.setObjectName("plot_title_text")
        self.scatter_choosedata_hlayout.addWidget(self.plot_title_text)
        self.scatter_vlayout.addLayout(self.scatter_choosedata_hlayout)
        self.scatter_choosevars_hlayout = QtWidgets.QHBoxLayout()
        self.scatter_choosevars_hlayout.setContentsMargins(11, 11, 11, 11)
        self.scatter_choosevars_hlayout.setSpacing(6)
        self.scatter_choosevars_hlayout.setObjectName("scatter_choosevars_hlayout")
        self.scatter_choosex_vlayout = QtWidgets.QVBoxLayout()
        self.scatter_choosex_vlayout.setContentsMargins(11, 11, 11, 11)
        self.scatter_choosex_vlayout.setSpacing(6)
        self.scatter_choosex_vlayout.setObjectName("scatter_choosex_vlayout")
        self.scatter_choosex_label = QtWidgets.QLabel(self.scatter)
        self.scatter_choosex_label.setObjectName("scatter_choosex_label")
        self.scatter_choosex_vlayout.addWidget(self.scatter_choosex_label)
        self.xvar_choices = QtWidgets.QComboBox(self.scatter)
        self.xvar_choices.setObjectName("xvar_choices")
        self.scatter_choosex_vlayout.addWidget(self.xvar_choices)
        self.xtitle_hlayout = QtWidgets.QHBoxLayout()
        self.xtitle_hlayout.setContentsMargins(11, 11, 11, 11)
        self.xtitle_hlayout.setSpacing(6)
        self.xtitle_hlayout.setObjectName("xtitle_hlayout")
        self.xtitle_label = QtWidgets.QLabel(self.scatter)
        self.xtitle_label.setObjectName("xtitle_label")
        self.xtitle_hlayout.addWidget(self.xtitle_label)
        self.xtitle_text = QtWidgets.QLineEdit(self.scatter)
        self.xtitle_text.setObjectName("xtitle_text")
        self.xtitle_hlayout.addWidget(self.xtitle_text)
        self.scatter_choosex_vlayout.addLayout(self.xtitle_hlayout)
        self.xrange_hlayout = QtWidgets.QHBoxLayout()
        self.xrange_hlayout.setContentsMargins(11, 11, 11, 11)
        self.xrange_hlayout.setSpacing(6)
        self.xrange_hlayout.setObjectName("xrange_hlayout")
        self.xmin_label = QtWidgets.QLabel(self.scatter)
        self.xmin_label.setObjectName("xmin_label")
        self.xrange_hlayout.addWidget(self.xmin_label)
        self.xmin_spin = QtWidgets.QDoubleSpinBox(self.scatter)
        self.xmin_spin.setObjectName("xmin_spin")
        self.xrange_hlayout.addWidget(self.xmin_spin)
        self.xmax_label = QtWidgets.QLabel(self.scatter)
        self.xmax_label.setObjectName("xmax_label")
        self.xrange_hlayout.addWidget(self.xmax_label)
        self.xmax_spin = QtWidgets.QDoubleSpinBox(self.scatter)
        self.xmax_spin.setObjectName("xmax_spin")
        self.xrange_hlayout.addWidget(self.xmax_spin)
        self.scatter_choosex_vlayout.addLayout(self.xrange_hlayout)
        self.scatter_choosevars_hlayout.addLayout(self.scatter_choosex_vlayout)
        self.scatter_choosey_vlayout = QtWidgets.QVBoxLayout()
        self.scatter_choosey_vlayout.setContentsMargins(11, 11, 11, 11)
        self.scatter_choosey_vlayout.setSpacing(6)
        self.scatter_choosey_vlayout.setObjectName("scatter_choosey_vlayout")
        self.scatter_choosey_label = QtWidgets.QLabel(self.scatter)
        self.scatter_choosey_label.setObjectName("scatter_choosey_label")
        self.scatter_choosey_vlayout.addWidget(self.scatter_choosey_label)
        self.yvar_choices = QtWidgets.QComboBox(self.scatter)
        self.yvar_choices.setObjectName("yvar_choices")
        self.scatter_choosey_vlayout.addWidget(self.yvar_choices)
        self.ytitle_hlayout = QtWidgets.QHBoxLayout()
        self.ytitle_hlayout.setContentsMargins(11, 11, 11, 11)
        self.ytitle_hlayout.setSpacing(6)
        self.ytitle_hlayout.setObjectName("ytitle_hlayout")
        self.ytitle_label = QtWidgets.QLabel(self.scatter)
        self.ytitle_label.setObjectName("ytitle_label")
        self.ytitle_hlayout.addWidget(self.ytitle_label)
        self.ytitle_text = QtWidgets.QLineEdit(self.scatter)
        self.ytitle_text.setObjectName("ytitle_text")
        self.ytitle_hlayout.addWidget(self.ytitle_text)
        self.scatter_choosey_vlayout.addLayout(self.ytitle_hlayout)
        self.yrange_hlayout = QtWidgets.QHBoxLayout()
        self.yrange_hlayout.setContentsMargins(11, 11, 11, 11)
        self.yrange_hlayout.setSpacing(6)
        self.yrange_hlayout.setObjectName("yrange_hlayout")
        self.ymin_label = QtWidgets.QLabel(self.scatter)
        self.ymin_label.setObjectName("ymin_label")
        self.yrange_hlayout.addWidget(self.ymin_label)
        self.ymin_spin = QtWidgets.QDoubleSpinBox(self.scatter)
        self.ymin_spin.setObjectName("ymin_spin")
        self.yrange_hlayout.addWidget(self.ymin_spin)
        self.ymax_label = QtWidgets.QLabel(self.scatter)
        self.ymax_label.setObjectName("ymax_label")
        self.yrange_hlayout.addWidget(self.ymax_label)
        self.ymax_spin = QtWidgets.QDoubleSpinBox(self.scatter)
        self.ymax_spin.setObjectName("ymax_spin")
        self.yrange_hlayout.addWidget(self.ymax_spin)
        self.scatter_choosey_vlayout.addLayout(self.yrange_hlayout)
        self.scatter_choosevars_hlayout.addLayout(self.scatter_choosey_vlayout)
        self.scatter_vlayout.addLayout(self.scatter_choosevars_hlayout)
        self.legend_hlayout = QtWidgets.QHBoxLayout()
        self.legend_hlayout.setContentsMargins(11, 11, 11, 11)
        self.legend_hlayout.setSpacing(6)
        self.legend_hlayout.setObjectName("legend_hlayout")
        self.legend_label = QtWidgets.QLabel(self.scatter)
        self.legend_label.setObjectName("legend_label")
        self.legend_hlayout.addWidget(self.legend_label)
        self.legend_label_text = QtWidgets.QLineEdit(self.scatter)
        self.legend_label_text.setObjectName("legend_label_text")
        self.legend_hlayout.addWidget(self.legend_label_text)
        self.onetoone = QtWidgets.QCheckBox(self.scatter)
        self.onetoone.setObjectName("onetoone")
        self.legend_hlayout.addWidget(self.onetoone)
        self.scatter_vlayout.addLayout(self.legend_hlayout)
        self.scatter_color_file_hlayout = QtWidgets.QHBoxLayout()
        self.scatter_color_file_hlayout.setContentsMargins(11, 11, 11, 11)
        self.scatter_color_file_hlayout.setSpacing(6)
        self.scatter_color_file_hlayout.setObjectName("scatter_color_file_hlayout")
        self.color_label = QtWidgets.QLabel(self.scatter)
        self.color_label.setObjectName("color_label")
        self.scatter_color_file_hlayout.addWidget(self.color_label)
        self.color_choices = QtWidgets.QComboBox(self.scatter)
        self.color_choices.setIconSize(QtCore.QSize(50, 20))
        self.color_choices.setObjectName("color_choices")
        self.color_choices.addItem("")
        self.color_choices.addItem("")
        self.color_choices.addItem("")
        self.color_choices.addItem("")
        self.color_choices.addItem("")
        self.color_choices.addItem("")
        self.color_choices.addItem("")
        self.scatter_color_file_hlayout.addWidget(self.color_choices)
        self.file_label = QtWidgets.QLabel(self.scatter)
        self.file_label.setObjectName("file_label")
        self.scatter_color_file_hlayout.addWidget(self.file_label)
        self.file_text = QtWidgets.QLineEdit(self.scatter)
        self.file_text.setObjectName("file_text")
        self.scatter_color_file_hlayout.addWidget(self.file_text)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.scatter_color_file_hlayout.addItem(spacerItem)
        self.scatter_vlayout.addLayout(self.scatter_color_file_hlayout)
        self.verticalLayout.addLayout(self.scatter_vlayout)
        self.verticalLayout_8.addWidget(self.scatter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ok.addItem(spacerItem1)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 666, 26))


        self.scatter.setTitle(_translate("MainWindow", "Scatter Plot"))
        self.scatter_choosedata_label.setText(_translate("MainWindow", "Choose data:"))
        self.scatter_choosedata.setItemText(0, _translate("MainWindow", "Choose Data"))
        self.scatter_choosedata.setItemText(1, _translate("MainWindow", "Known Data"))
        self.figname_label.setText(_translate("MainWindow", "Figure name:"))
        self.plot_title_label.setText(_translate("MainWindow", "Plot Title:"))
        self.scatter_choosex_label.setText(_translate("MainWindow", "Choose X variable:"))
        self.xtitle_label.setText(_translate("MainWindow", "X title:"))
        self.xmin_label.setText(_translate("MainWindow", "X min:"))
        self.xmax_label.setText(_translate("MainWindow", "X max:"))
        self.scatter_choosey_label.setText(_translate("MainWindow", "Choose Y variable:"))
        self.ytitle_label.setText(_translate("MainWindow", "Y title:"))
        self.ymin_label.setText(_translate("MainWindow", "Y min:"))
        self.ymax_label.setText(_translate("MainWindow", "Y max:"))
        self.legend_label.setText(_translate("MainWindow", "Legend Label:"))
        self.onetoone.setText(_translate("MainWindow", "One to One"))
        self.color_label.setText(_translate("MainWindow", "Color:"))
        self.color_choices.setItemText(0, _translate("MainWindow", "Red"))
        self.color_choices.setItemText(1, _translate("MainWindow", "Green"))
        self.color_choices.setItemText(2, _translate("MainWindow", "Blue"))
        self.color_choices.setItemText(3, _translate("MainWindow", "Cyan"))
        self.color_choices.setItemText(4, _translate("MainWindow", "Magenta"))
        self.color_choices.setItemText(5, _translate("MainWindow", "Yellow"))
        self.color_choices.setItemText(6, _translate("MainWindow", "Black"))
        self.file_label.setText(_translate("MainWindow", "Plot Filename:"))
        self.actionTommy_s_Methgod.setText(_translate("MainWindow", "Tommy\'s Method"))



