


        self.scrollAreaWidgetContents_2.setStyleSheet("QGroupBox {\n"
"                                    border: 2px solid gray;\n"
"                                    border-radius: 6px;\n"
"                                    margin-top: 0.5em;\n"
"                                    }\n"
"\n"
"                                    QGroupBox::title {\n"
"\n"
"                                    padding-top: -14px;\n"
"                                    padding-left: 8px;\n"
"                                    }\n"
        self.regression = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        font.setPointSize(10)
        self.regression.setFont(font)
        self.regression.setObjectName("regression")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.regression)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.regression_vlayout = QtWidgets.QVBoxLayout()
        self.regression_vlayout.setContentsMargins(11, 11, 11, 11)
        self.regression_vlayout.setSpacing(6)
        self.regression_vlayout.setObjectName("regression_vlayout")
        self.regression_choosedata_hlayout = QtWidgets.QHBoxLayout()
        self.regression_choosedata_hlayout.setContentsMargins(11, 11, 11, 11)
        self.regression_choosedata_hlayout.setSpacing(6)
        self.regression_choosedata_hlayout.setObjectName("regression_choosedata_hlayout")
        self.regression_choosedata_label = QtWidgets.QLabel(self.regression)
        self.regression_choosedata_label.setObjectName("regression_choosedata_label")
        self.regression_choosedata_hlayout.addWidget(self.regression_choosedata_label)
        self.regression_choosedata = QtWidgets.QComboBox(self.regression)
        self.regression_choosedata.setIconSize(QtCore.QSize(50, 20))
        self.regression_choosedata.setObjectName("regression_choosedata")
        self.regression_choosedata.addItem("")
        self.regression_choosedata.addItem("")
        self.regression_choosedata_hlayout.addWidget(self.regression_choosedata)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.regression_choosedata_hlayout.addItem(spacerItem)
        self.regression_vlayout.addLayout(self.regression_choosedata_hlayout)
        self.regression_choosevars_hlayout = QtWidgets.QHBoxLayout()
        self.regression_choosevars_hlayout.setContentsMargins(11, 11, 11, 11)
        self.regression_choosevars_hlayout.setSpacing(6)
        self.regression_choosevars_hlayout.setObjectName("regression_choosevars_hlayout")
        self.regression_choosex_vlayout = QtWidgets.QVBoxLayout()
        self.regression_choosex_vlayout.setContentsMargins(11, 11, 11, 11)
        self.regression_choosex_vlayout.setSpacing(6)
        self.regression_choosex_vlayout.setObjectName("regression_choosex_vlayout")
        self.regression_choosex_label = QtWidgets.QLabel(self.regression)
        self.regression_choosex_label.setObjectName("regression_choosex_label")
        self.regression_choosex_vlayout.addWidget(self.regression_choosex_label)
        self.regression_choosex = QtWidgets.QListWidget(self.regression)
        self.regression_choosex.setMinimumSize(QtCore.QSize(50, 0))
        self.regression_choosex.setMaximumSize(QtCore.QSize(100, 16777215))
        self.regression_choosex.setObjectName("regression_choosex")
        item = QtWidgets.QListWidgetItem()
        self.regression_choosex.addItem(item)
        self.regression_choosex_vlayout.addWidget(self.regression_choosex)
        self.regression_choosevars_hlayout.addLayout(self.regression_choosex_vlayout)
        self.regression_choosey_vlayout = QtWidgets.QVBoxLayout()
        self.regression_choosey_vlayout.setContentsMargins(11, 11, 11, 11)
        self.regression_choosey_vlayout.setSpacing(6)
        self.regression_choosey_vlayout.setObjectName("regression_choosey_vlayout")
        self.regression_choosey_label = QtWidgets.QLabel(self.regression)
        self.regression_choosey_label.setObjectName("regression_choosey_label")
        self.regression_choosey_vlayout.addWidget(self.regression_choosey_label)
        self.regression_choosey = QtWidgets.QListWidget(self.regression)
        self.regression_choosey.setMaximumSize(QtCore.QSize(100, 16777215))
        self.regression_choosey.setObjectName("regression_choosey")
        item = QtWidgets.QListWidgetItem()
        self.regression_choosey.addItem(item)
        self.regression_choosey_vlayout.addWidget(self.regression_choosey)
        self.regression_choosevars_hlayout.addLayout(self.regression_choosey_vlayout)
        self.yrange_vlayout = QtWidgets.QVBoxLayout()
        self.yrange_vlayout.setContentsMargins(11, 11, 11, 11)
        self.yrange_vlayout.setSpacing(6)
        self.yrange_vlayout.setObjectName("yrange_vlayout")
        self.ymin_hlayout = QtWidgets.QHBoxLayout()
        self.ymin_hlayout.setContentsMargins(11, 11, 11, 11)
        self.ymin_hlayout.setSpacing(6)
        self.ymin_hlayout.setObjectName("ymin_hlayout")
        self.ymin_label = QtWidgets.QLabel(self.regression)
        self.ymin_label.setObjectName("ymin_label")
        self.ymin_hlayout.addWidget(self.ymin_label)
        self.ymin_spin = QtWidgets.QDoubleSpinBox(self.regression)
        self.ymin_spin.setObjectName("ymin_spin")
        self.ymin_hlayout.addWidget(self.ymin_spin)
        self.yrange_vlayout.addLayout(self.ymin_hlayout)
        self.ymax_hlayout = QtWidgets.QHBoxLayout()
        self.ymax_hlayout.setContentsMargins(11, 11, 11, 11)
        self.ymax_hlayout.setSpacing(6)
        self.ymax_hlayout.setObjectName("ymax_hlayout")
        self.ymax_label = QtWidgets.QLabel(self.regression)
        self.ymax_label.setObjectName("ymax_label")
        self.ymax_hlayout.addWidget(self.ymax_label)
        self.ymax_spin = QtWidgets.QDoubleSpinBox(self.regression)
        self.ymax_spin.setObjectName("ymax_spin")
        self.ymax_hlayout.addWidget(self.ymax_spin)
        self.yrange_vlayout.addLayout(self.ymax_hlayout)
        self.regression_choosevars_hlayout.addLayout(self.yrange_vlayout)
        self.regression_vlayout.addLayout(self.regression_choosevars_hlayout)
        self.ransac_hlayout = QtWidgets.QHBoxLayout()
        self.ransac_hlayout.setContentsMargins(11, 11, 11, 11)
        self.ransac_hlayout.setSpacing(6)
        self.ransac_hlayout.setObjectName("ransac_hlayout")
        self.regression_ransac_checkbox = QtWidgets.QCheckBox(self.regression)
        self.regression_ransac_checkbox.setObjectName("regression_ransac_checkbox")
        self.ransac_hlayout.addWidget(self.regression_ransac_checkbox)
        self.ransac_options_hlayout = QtWidgets.QHBoxLayout()
        self.ransac_options_hlayout.setContentsMargins(11, 11, 11, 11)
        self.ransac_options_hlayout.setSpacing(6)
        self.ransac_options_hlayout.setObjectName("ransac_options_hlayout")
        self.ransac_lossfunc_label = QtWidgets.QLabel(self.regression)
        self.ransac_lossfunc_label.setObjectName("ransac_lossfunc_label")
        self.ransac_options_hlayout.addWidget(self.ransac_lossfunc_label)
        self.ransac_lossfunc_combobox = QtWidgets.QComboBox(self.regression)
        self.ransac_lossfunc_combobox.setObjectName("ransac_lossfunc_combobox")
        self.ransac_lossfunc_combobox.addItem("")
        self.ransac_lossfunc_combobox.addItem("")
        self.ransac_options_hlayout.addWidget(self.ransac_lossfunc_combobox)
        self.ransac_thresh_label = QtWidgets.QLabel(self.regression)
        self.ransac_thresh_label.setObjectName("ransac_thresh_label")
        self.ransac_options_hlayout.addWidget(self.ransac_thresh_label)
        self.ransac_thresh_spin = QtWidgets.QDoubleSpinBox(self.regression)
        self.ransac_thresh_spin.setObjectName("ransac_thresh_spin")
        self.ransac_options_hlayout.addWidget(self.ransac_thresh_spin)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ransac_options_hlayout.addItem(spacerItem1)
        self.ransac_hlayout.addLayout(self.ransac_options_hlayout)
        self.regression_vlayout.addLayout(self.ransac_hlayout)
        self.regression_choosealg_hlayout = QtWidgets.QHBoxLayout()
        self.regression_choosealg_hlayout.setContentsMargins(11, 11, 11, 11)
        self.regression_choosealg_hlayout.setSpacing(6)
        self.regression_choosealg_hlayout.setObjectName("regression_choosealg_hlayout")
        self.regression_choosealg_label = QtWidgets.QLabel(self.regression)
        self.regression_choosealg_label.setObjectName("regression_choosealg_label")
        self.regression_choosealg_hlayout.addWidget(self.regression_choosealg_label)
        self.regression_choosealg = QtWidgets.QComboBox(self.regression)
        self.regression_choosealg.setIconSize(QtCore.QSize(50, 20))
        self.regression_choosealg.setObjectName("regression_choosealg")
        self.regression_choosealg.addItem("")
        self.regression_choosealg.addItem("")
        self.regression_choosealg.addItem("")
        self.regression_choosealg_hlayout.addWidget(self.regression_choosealg)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.regression_choosealg_hlayout.addItem(spacerItem2)
        self.regression_vlayout.addLayout(self.regression_choosealg_hlayout)
        self.pls_widget = QtWidgets.QWidget(self.regression)
        self.pls_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.pls_widget.setObjectName("pls_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.pls_widget)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pls_nc_label = QtWidgets.QLabel(self.pls_widget)
        self.pls_nc_label.setObjectName("pls_nc_label")
        self.horizontalLayout_2.addWidget(self.pls_nc_label)
        self.pls_nc_spinbox = QtWidgets.QSpinBox(self.pls_widget)
        self.pls_nc_spinbox.setObjectName("pls_nc_spinbox")
        self.horizontalLayout_2.addWidget(self.pls_nc_spinbox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.regression_vlayout.addWidget(self.pls_widget)
        self.gp_widget = QtWidgets.QWidget(self.regression)
        self.gp_widget.setObjectName("gp_widget")
        self.gp_vlayout = QtWidgets.QVBoxLayout(self.gp_widget)
        self.gp_vlayout.setContentsMargins(11, 11, 11, 11)
        self.gp_vlayout.setSpacing(6)
        self.gp_vlayout.setObjectName("gp_vlayout")
        self.gp_dim_red_hlayout = QtWidgets.QHBoxLayout()
        self.gp_dim_red_hlayout.setContentsMargins(11, 11, 11, 11)
        self.gp_dim_red_hlayout.setSpacing(6)
        self.gp_dim_red_hlayout.setObjectName("gp_dim_red_hlayout")
        self.gp_dim_red_label = QtWidgets.QLabel(self.gp_widget)
        self.gp_dim_red_label.setObjectName("gp_dim_red_label")
        self.gp_dim_red_hlayout.addWidget(self.gp_dim_red_label)
        self.gp_dim_red_combobox = QtWidgets.QComboBox(self.gp_widget)
        self.gp_dim_red_combobox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.gp_dim_red_combobox.setObjectName("gp_dim_red_combobox")
        self.gp_dim_red_combobox.addItem("")
        self.gp_dim_red_combobox.addItem("")
        self.gp_dim_red_combobox.addItem("")
        self.gp_dim_red_combobox.addItem("")
        self.gp_dim_red_hlayout.addWidget(self.gp_dim_red_combobox)
        self.gp_vlayout.addLayout(self.gp_dim_red_hlayout)
        self.gp_verticalLayout = QtWidgets.QVBoxLayout()
        self.gp_verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.gp_verticalLayout.setSpacing(6)
        self.gp_verticalLayout.setObjectName("gp_verticalLayout")
        self.gp_rand_starts_hlayout = QtWidgets.QHBoxLayout()
        self.gp_rand_starts_hlayout.setContentsMargins(11, 11, 11, 11)
        self.gp_rand_starts_hlayout.setSpacing(6)
        self.gp_rand_starts_hlayout.setObjectName("gp_rand_starts_hlayout")
        self.gp_rand_starts_label = QtWidgets.QLabel(self.gp_widget)
        self.gp_rand_starts_label.setObjectName("gp_rand_starts_label")
        self.gp_rand_starts_hlayout.addWidget(self.gp_rand_starts_label)
        self.gp_rand_starts_spin = QtWidgets.QSpinBox(self.gp_widget)
        self.gp_rand_starts_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gp_rand_starts_spin.setObjectName("gp_rand_starts_spin")
        self.gp_rand_starts_hlayout.addWidget(self.gp_rand_starts_spin)
        self.gp_verticalLayout.addLayout(self.gp_rand_starts_hlayout)
        self.gp_theta0_hlayout = QtWidgets.QHBoxLayout()
        self.gp_theta0_hlayout.setContentsMargins(11, 11, 11, 11)
        self.gp_theta0_hlayout.setSpacing(6)
        self.gp_theta0_hlayout.setObjectName("gp_theta0_hlayout")
        self.gp_theta0_label = QtWidgets.QLabel(self.gp_widget)
        self.gp_theta0_label.setObjectName("gp_theta0_label")
        self.gp_theta0_hlayout.addWidget(self.gp_theta0_label)
        self.gp_theta0_spin = QtWidgets.QDoubleSpinBox(self.gp_widget)
        self.gp_theta0_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gp_theta0_spin.setObjectName("gp_theta0_spin")
        self.gp_theta0_hlayout.addWidget(self.gp_theta0_spin)
        self.gp_verticalLayout.addLayout(self.gp_theta0_hlayout)
        self.gp_thetaU_hlayout = QtWidgets.QHBoxLayout()
        self.gp_thetaU_hlayout.setContentsMargins(11, 11, 11, 11)
        self.gp_thetaU_hlayout.setSpacing(6)
        self.gp_thetaU_hlayout.setObjectName("gp_thetaU_hlayout")
        self.gp_thetaU_label = QtWidgets.QLabel(self.gp_widget)
        self.gp_thetaU_label.setObjectName("gp_thetaU_label")
        self.gp_thetaU_hlayout.addWidget(self.gp_thetaU_label)
        self.gp_thetaU_spin = QtWidgets.QDoubleSpinBox(self.gp_widget)
        self.gp_thetaU_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gp_thetaU_spin.setObjectName("gp_thetaU_spin")
        self.gp_thetaU_hlayout.addWidget(self.gp_thetaU_spin)
        self.gp_verticalLayout.addLayout(self.gp_thetaU_hlayout)
        self.gp_thetaL_hlayout = QtWidgets.QHBoxLayout()
        self.gp_thetaL_hlayout.setContentsMargins(11, 11, 11, 11)
        self.gp_thetaL_hlayout.setSpacing(6)
        self.gp_thetaL_hlayout.setObjectName("gp_thetaL_hlayout")
        self.gp_thetaL_label = QtWidgets.QLabel(self.gp_widget)
        self.gp_thetaL_label.setObjectName("gp_thetaL_label")
        self.gp_thetaL_hlayout.addWidget(self.gp_thetaL_label)
        self.gp_thetaL_spin = QtWidgets.QDoubleSpinBox(self.gp_widget)
        self.gp_thetaL_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gp_thetaL_spin.setObjectName("gp_thetaL_spin")
        self.gp_thetaL_hlayout.addWidget(self.gp_thetaL_spin)
        self.gp_verticalLayout.addLayout(self.gp_thetaL_hlayout)
        self.gp_vlayout.addLayout(self.gp_verticalLayout)
        self.regression_vlayout.addWidget(self.gp_widget)
        self.verticalLayout.addLayout(self.regression_vlayout)
        self.verticalLayout_8.addWidget(self.regression)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ok.addItem(spacerItem4)


        self.regression.setTitle(_translate("MainWindow", "Regression"))
        self.regression_choosedata_label.setText(_translate("MainWindow", "Choose data:"))
        self.regression_choosedata.setItemText(0, _translate("MainWindow", "Choose Data"))
        self.regression_choosedata.setItemText(1, _translate("MainWindow", "Known Data"))
        self.regression_choosex_label.setText(_translate("MainWindow", "Choose X variable(s):"))
        __sortingEnabled = self.regression_choosex.isSortingEnabled()
        self.regression_choosex.setSortingEnabled(False)
        item = self.regression_choosex.item(0)
        item.setText(_translate("MainWindow", "Choose X"))
        self.regression_choosex.setSortingEnabled(__sortingEnabled)
        self.regression_choosey_label.setText(_translate("MainWindow", "Choose Y variable(s):"))
        __sortingEnabled = self.regression_choosey.isSortingEnabled()
        self.regression_choosey.setSortingEnabled(False)
        item = self.regression_choosey.item(0)
        item.setText(_translate("MainWindow", "Choose Y"))
        self.regression_choosey.setSortingEnabled(__sortingEnabled)
        self.ymin_label.setText(_translate("MainWindow", "Y min:"))
        self.ymax_label.setText(_translate("MainWindow", "Y max:"))
        self.regression_ransac_checkbox.setText(_translate("MainWindow", "RANSAC"))
        self.ransac_lossfunc_label.setText(_translate("MainWindow", "Loss function:"))
        self.ransac_lossfunc_combobox.setItemText(0, _translate("MainWindow", "Squared"))
        self.ransac_lossfunc_combobox.setItemText(1, _translate("MainWindow", "Absolute"))
        self.ransac_thresh_label.setText(_translate("MainWindow", "Threshold:"))
        self.regression_choosealg_label.setText(_translate("MainWindow", "Choose Algorithm:"))
        self.regression_choosealg.setItemText(0, _translate("MainWindow", "PLS"))
        self.regression_choosealg.setItemText(1, _translate("MainWindow", "GP"))
        self.regression_choosealg.setItemText(2, _translate("MainWindow", "Others coming soon..."))
        self.gp_dim_red_label.setText(_translate("MainWindow", "Dimensionality reduction\n"
"                                                                                        method:\n"
"                                                                                    "))
        self.gp_dim_red_combobox.setItemText(0, _translate("MainWindow", "PCA"))
        self.gp_dim_red_combobox.setItemText(1, _translate("MainWindow", "FastICA"))
        self.gp_dim_red_combobox.setItemText(2, _translate("MainWindow", "ICA - JADE"))
        self.gp_dim_red_combobox.setItemText(3, _translate("MainWindow", "None"))
"                                                                                                starts:\n"
"                                                                                            "))
        self.gp_theta0_label.setText(_translate("MainWindow", "Starting Theta:\n"
"                                                                                            "))
        self.gp_thetaU_label.setText(_translate("MainWindow", "Upper bound on\n"
"                                                                                                Theta:\n"
"                                                                                            "))
        self.gp_thetaL_label.setText(_translate("MainWindow", "Lower bound on\n"
"                                                                                                Theta:\n"
"                                                                                            "))
        self.actionTommy_s_Methgod.setText(_translate("MainWindow", "Tommy\'s Method"))



