


        self.scrollAreaWidgetContents_2.setStyleSheet("QGroupBox {\n"
"                                    border: 2px solid gray;\n"
"                                    border-radius: 6px;\n"
"                                    margin-top: 0.5em;\n"
"                                    }\n"
"\n"
"                                    QGroupBox::title {\n"
"\n"
"                                    padding-top: -14px;\n"
"                                    padding-left: 8px;\n"
"                                    }\n"
        self.submodel = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        font.setPointSize(10)
        self.submodel.setFont(font)
        self.submodel.setObjectName("submodel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.submodel)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.submodel_vlayout = QtWidgets.QVBoxLayout()
        self.submodel_vlayout.setContentsMargins(11, 11, 11, 11)
        self.submodel_vlayout.setSpacing(6)
        self.submodel_vlayout.setObjectName("submodel_vlayout")
        self.submodel_choosedata_hlayout = QtWidgets.QHBoxLayout()
        self.submodel_choosedata_hlayout.setContentsMargins(11, 11, 11, 11)
        self.submodel_choosedata_hlayout.setSpacing(6)
        self.submodel_choosedata_hlayout.setObjectName("submodel_choosedata_hlayout")
        self.submodel_choosedata = QtWidgets.QComboBox(self.submodel)
        self.submodel_choosedata.setIconSize(QtCore.QSize(50, 20))
        self.submodel_choosedata.setObjectName("submodel_choosedata")
        self.submodel_choosedata.addItem("")
        self.submodel_choosedata.addItem("")
        self.submodel_choosedata_hlayout.addWidget(self.submodel_choosedata)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.submodel_choosedata_hlayout.addItem(spacerItem)
        self.submodel_vlayout.addLayout(self.submodel_choosedata_hlayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.submodel)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.submodel)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.submodel)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.submodel)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.submodel_vlayout.addLayout(self.horizontalLayout)
        self.submodel_choosealg_hlayout = QtWidgets.QHBoxLayout()
        self.submodel_choosealg_hlayout.setContentsMargins(11, 11, 11, 11)
        self.submodel_choosealg_hlayout.setSpacing(6)
        self.submodel_choosealg_hlayout.setObjectName("submodel_choosealg_hlayout")
        self.submodel_choosealg = QtWidgets.QComboBox(self.submodel)
        self.submodel_choosealg.setIconSize(QtCore.QSize(50, 20))
        self.submodel_choosealg.setObjectName("submodel_choosealg")
        self.submodel_choosealg.addItem("")
        self.submodel_choosealg.addItem("")
        self.submodel_choosealg.addItem("")
        self.submodel_choosealg.addItem("")
        self.submodel_choosealg_hlayout.addWidget(self.submodel_choosealg)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.submodel_choosealg_hlayout.addItem(spacerItem2)
        self.submodel_vlayout.addLayout(self.submodel_choosealg_hlayout)
        self.regression_ransac_checkbox = QtWidgets.QCheckBox(self.submodel)
        self.regression_ransac_checkbox.setObjectName("regression_ransac_checkbox")
        self.submodel_vlayout.addWidget(self.regression_ransac_checkbox)
        self.submodel_trainbutton_hlayout = QtWidgets.QHBoxLayout()
        self.submodel_trainbutton_hlayout.setContentsMargins(11, 11, 11, 11)
        self.submodel_trainbutton_hlayout.setSpacing(6)
        self.submodel_trainbutton_hlayout.setObjectName("submodel_trainbutton_hlayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.submodel_trainbutton_hlayout.addItem(spacerItem3)
        self.submodel_trainbutton = QtWidgets.QPushButton(self.submodel)
        self.submodel_trainbutton.setObjectName("submodel_trainbutton")
        self.submodel_trainbutton_hlayout.addWidget(self.submodel_trainbutton)
        self.submodel_vlayout.addLayout(self.submodel_trainbutton_hlayout)
        self.verticalLayout.addLayout(self.submodel_vlayout)
        self.verticalLayout_8.addWidget(self.submodel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ok.addItem(spacerItem4)


        self.submodel.setTitle(_translate("MainWindow", "Submodel Ranges"))
        self.submodel_choosedata.setItemText(0, _translate("MainWindow", "Choose Data"))
        self.submodel_choosedata.setItemText(1, _translate("MainWindow", "Known Data"))
        self.label.setText(_translate("MainWindow", "Min"))
        self.label_2.setText(_translate("MainWindow", "Max"))
        self.submodel_choosealg.setItemText(0, _translate("MainWindow", "Choose Algorithm"))
        self.submodel_choosealg.setItemText(1, _translate("MainWindow", "PLS"))
        self.submodel_choosealg.setItemText(2, _translate("MainWindow", "GP"))
        self.submodel_choosealg.setItemText(3, _translate("MainWindow", "Others coming soon..."))
        self.regression_ransac_checkbox.setText(_translate("MainWindow", "RANSAC"))
        self.submodel_trainbutton.setText(_translate("MainWindow", "Train Submodels"))
        self.actionTommy_s_Methgod.setText(_translate("MainWindow", "Tommy\'s Method"))



