


        MainWindow.resize(581, 542)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 557, 394))
        self.scrollAreaWidgetContents_2.setStyleSheet("QGroupBox {\n"
"                                    border: 2px solid gray;\n"
"                                    border-radius: 6px;\n"
"                                    margin-top: 0.5em;\n"
"                                    }\n"
"\n"
"                                    QGroupBox::title {\n"
"\n"
"                                    padding-top: -14px;\n"
"                                    padding-left: 8px;\n"
"                                    }\n"
        self.submodel_opt = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        font.setPointSize(10)
        self.submodel_opt.setFont(font)
        self.submodel_opt.setObjectName("submodel_opt")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.submodel_opt)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.choosemodel_hlayout = QtWidgets.QHBoxLayout()
        self.choosemodel_hlayout.setContentsMargins(11, 11, 11, 11)
        self.choosemodel_hlayout.setSpacing(6)
        self.choosemodel_hlayout.setObjectName("choosemodel_hlayout")
        self.choosemodel_label = QtWidgets.QLabel(self.submodel_opt)
        self.choosemodel_label.setObjectName("choosemodel_label")
        self.choosemodel_hlayout.addWidget(self.choosemodel_label)
        self.choosemodel = QtWidgets.QComboBox(self.submodel_opt)
        self.choosemodel.setIconSize(QtCore.QSize(50, 20))
        self.choosemodel.setObjectName("choosemodel")
        self.choosemodel.addItem("")
        self.choosemodel_hlayout.addWidget(self.choosemodel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.choosemodel_hlayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.choosemodel_hlayout)
        self.submodels_vlayout = QtWidgets.QVBoxLayout()
        self.submodels_vlayout.setContentsMargins(11, 11, 11, 11)
        self.submodels_vlayout.setSpacing(6)
        self.submodels_vlayout.setObjectName("submodels_vlayout")
        self.low_model_hlayout = QtWidgets.QHBoxLayout()
        self.low_model_hlayout.setContentsMargins(11, 11, 11, 11)
        self.low_model_hlayout.setSpacing(6)
        self.low_model_hlayout.setObjectName("low_model_hlayout")
        self.choose_low_model = QtWidgets.QComboBox(self.submodel_opt)
        self.choose_low_model.setObjectName("choose_low_model")
        self.choose_low_model.addItem("")
        self.low_model_hlayout.addWidget(self.choose_low_model)
        self.low_model_max_label = QtWidgets.QLabel(self.submodel_opt)
        self.low_model_max_label.setObjectName("low_model_max_label")
        self.low_model_hlayout.addWidget(self.low_model_max_label)
        self.low_model_max = QtWidgets.QDoubleSpinBox(self.submodel_opt)
        self.low_model_max.setObjectName("low_model_max")
        self.low_model_hlayout.addWidget(self.low_model_max)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.low_model_hlayout.addItem(spacerItem1)
        self.submodels_vlayout.addLayout(self.low_model_hlayout)
        self.submodel_hlayout = QtWidgets.QHBoxLayout()
        self.submodel_hlayout.setContentsMargins(11, 11, 11, 11)
        self.submodel_hlayout.setSpacing(6)
        self.submodel_hlayout.setObjectName("submodel_hlayout")
        self.choose_submodel = QtWidgets.QComboBox(self.submodel_opt)
        self.choose_submodel.setObjectName("choose_submodel")
        self.submodel_hlayout.addWidget(self.choose_submodel)
        self.submodel_min_label = QtWidgets.QLabel(self.submodel_opt)
        self.submodel_min_label.setObjectName("submodel_min_label")
        self.submodel_hlayout.addWidget(self.submodel_min_label)
        self.submodel_min = QtWidgets.QDoubleSpinBox(self.submodel_opt)
        self.submodel_min.setObjectName("submodel_min")
        self.submodel_hlayout.addWidget(self.submodel_min)
        self.submodel_max_label = QtWidgets.QLabel(self.submodel_opt)
        self.submodel_max_label.setObjectName("submodel_max_label")
        self.submodel_hlayout.addWidget(self.submodel_max_label)
        self.submodel_max = QtWidgets.QDoubleSpinBox(self.submodel_opt)
        self.submodel_max.setObjectName("submodel_max")
        self.submodel_hlayout.addWidget(self.submodel_max)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.submodel_hlayout.addItem(spacerItem2)
        self.submodels_vlayout.addLayout(self.submodel_hlayout)
        self.high_model_hlayout = QtWidgets.QHBoxLayout()
        self.high_model_hlayout.setContentsMargins(11, 11, 11, 11)
        self.high_model_hlayout.setSpacing(6)
        self.high_model_hlayout.setObjectName("high_model_hlayout")
        self.choose_high_model = QtWidgets.QComboBox(self.submodel_opt)
        self.choose_high_model.setObjectName("choose_high_model")
        self.high_model_hlayout.addWidget(self.choose_high_model)
        self.high_model_min_label = QtWidgets.QLabel(self.submodel_opt)
        self.high_model_min_label.setObjectName("high_model_min_label")
        self.high_model_hlayout.addWidget(self.high_model_min_label)
        self.high_model_min = QtWidgets.QDoubleSpinBox(self.submodel_opt)
        self.high_model_min.setObjectName("high_model_min")
        self.high_model_hlayout.addWidget(self.high_model_min)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.high_model_hlayout.addItem(spacerItem3)
        self.submodels_vlayout.addLayout(self.high_model_hlayout)
        self.verticalLayout.addLayout(self.submodels_vlayout)
        self.add_delete_hlayout = QtWidgets.QHBoxLayout()
        self.add_delete_hlayout.setContentsMargins(11, 11, 11, 11)
        self.add_delete_hlayout.setSpacing(6)
        self.add_delete_hlayout.setObjectName("add_delete_hlayout")
        self.add_submodel_button = QtWidgets.QPushButton(self.submodel_opt)
        self.add_submodel_button.setObjectName("add_submodel_button")
        self.add_delete_hlayout.addWidget(self.add_submodel_button)
        self.delete_submodel_button = QtWidgets.QPushButton(self.submodel_opt)
        self.delete_submodel_button.setObjectName("delete_submodel_button")
        self.add_delete_hlayout.addWidget(self.delete_submodel_button)
        self.optimize_checkbox = QtWidgets.QCheckBox(self.submodel_opt)
        self.optimize_checkbox.setObjectName("optimize_checkbox")
        self.add_delete_hlayout.addWidget(self.optimize_checkbox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.add_delete_hlayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.add_delete_hlayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choosedata_label = QtWidgets.QLabel(self.submodel_opt)
        self.choosedata_label.setObjectName("choosedata_label")
        self.horizontalLayout.addWidget(self.choosedata_label)
        self.choosedata = QtWidgets.QComboBox(self.submodel_opt)
        self.choosedata.setObjectName("choosedata")
        self.horizontalLayout.addWidget(self.choosedata)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.predictdata_vlayout = QtWidgets.QVBoxLayout()
        self.predictdata_vlayout.setContentsMargins(11, 11, 11, 11)
        self.predictdata_vlayout.setSpacing(6)
        self.predictdata_vlayout.setObjectName("predictdata_vlayout")
        self.choosedata_predict_label = QtWidgets.QLabel(self.submodel_opt)
        self.choosedata_predict_label.setObjectName("choosedata_predict_label")
        self.predictdata_vlayout.addWidget(self.choosedata_predict_label)
        self.choosedata_predict = QtWidgets.QListWidget(self.submodel_opt)
        self.choosedata_predict.setObjectName("choosedata_predict")
        self.predictdata_vlayout.addWidget(self.choosedata_predict)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.predictdata_vlayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.predictdata_vlayout)
        self.verticalLayout_8.addWidget(self.submodel_opt)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ok.addItem(spacerItem7)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 581, 26))


        self.submodel_opt.setTitle(_translate("MainWindow", "Submodel - Predict"))
        self.choosemodel_label.setText(_translate("MainWindow", "Choose reference model:"))
        self.choosemodel.setItemText(0, _translate("MainWindow", "Model"))
        self.choose_low_model.setItemText(0, _translate("MainWindow", "Submodel"))
        self.low_model_max_label.setText(_translate("MainWindow", "Max:"))
        self.submodel_min_label.setText(_translate("MainWindow", "Min:"))
        self.submodel_max_label.setText(_translate("MainWindow", "Max:"))
        self.high_model_min_label.setText(_translate("MainWindow", "Min:"))
        self.add_submodel_button.setText(_translate("MainWindow", "Add Submodel"))
        self.delete_submodel_button.setText(_translate("MainWindow", "Delete Submodel"))
        self.optimize_checkbox.setText(_translate("MainWindow", "Optimize"))
        self.choosedata_label.setText(_translate("MainWindow", "Choose known data:"))
        self.choosedata_predict_label.setText(_translate("MainWindow", "Choose data to predict:"))
        self.actionTommy_s_Methgod.setText(_translate("MainWindow", "Tommy\'s Method"))



