from PyQt5 import QtWidgets


class BayesianARDregression:
    def BARDR(self):
        self.line = QtWidgets.QFrame(self.regression)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.min_max_layout.addWidget(self.line)
        self.groupbox = QtWidgets.QGroupBox(self.regression)
        self.groupbox.setObjectName("groupbox")
        self.Automatic_Relevance_Determination_form = QtWidgets.QFormLayout(self.groupbox)
        self.Automatic_Relevance_Determination_form.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.Automatic_Relevance_Determination_form.setContentsMargins(11, 11, 11, 11)
        self.Automatic_Relevance_Determination_form.setSpacing(6)
        self.Automatic_Relevance_Determination_form.setObjectName("Automatic_Relevance_Determination_form")
        self.n_inter_label = QtWidgets.QLabel(self.groupbox)
        self.n_inter_label.setObjectName("n_inter_label")
        self.Automatic_Relevance_Determination_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.n_inter_label)
        self.n_inter_spinBox = QtWidgets.QSpinBox(self.groupbox)
        self.n_inter_spinBox.setMaximum(999999)
        self.n_inter_spinBox.setProperty("value", 300)
        self.n_inter_spinBox.setObjectName("n_inter_spinBox")
        self.Automatic_Relevance_Determination_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.n_inter_spinBox)
        self.tol_label = QtWidgets.QLabel(self.groupbox)
        self.tol_label.setObjectName("tol_label")
        self.Automatic_Relevance_Determination_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tol_label)
        self.tol_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupbox)
        self.tol_doubleSpinBox.setDecimals(5)
        self.tol_doubleSpinBox.setMinimum(-99.0)
        self.tol_doubleSpinBox.setSingleStep(0.001)
        self.tol_doubleSpinBox.setProperty("value", 0.001)
        self.tol_doubleSpinBox.setObjectName("tol_doubleSpinBox")
        self.Automatic_Relevance_Determination_form.setWidget(2, QtWidgets.QFormLayout.FieldRole,
                                                              self.tol_doubleSpinBox)
        self.alpha_1_label = QtWidgets.QLabel(self.groupbox)
        self.alpha_1_label.setObjectName("alpha_1_label")
        self.Automatic_Relevance_Determination_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.alpha_1_label)
        self.alpha_1_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupbox)
        self.alpha_1_doubleSpinBox.setDecimals(5)
        self.alpha_1_doubleSpinBox.setMinimum(-99.0)
        self.alpha_1_doubleSpinBox.setSingleStep(0.001)
        self.alpha_1_doubleSpinBox.setProperty("value", 0.001)
        self.alpha_1_doubleSpinBox.setObjectName("alpha_1_doubleSpinBox")
        self.Automatic_Relevance_Determination_form.setWidget(3, QtWidgets.QFormLayout.FieldRole,
                                                              self.alpha_1_doubleSpinBox)
        self.alpha_2_label = QtWidgets.QLabel(self.groupbox)
        self.alpha_2_label.setObjectName("alpha_2_label")
        self.Automatic_Relevance_Determination_form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.alpha_2_label)
        self.alpha_2_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupbox)
        self.alpha_2_doubleSpinBox.setDecimals(8)
        self.alpha_2_doubleSpinBox.setMinimum(-99.0)
        self.alpha_2_doubleSpinBox.setSingleStep(1e-06)
        self.alpha_2_doubleSpinBox.setProperty("value", 1e-06)
        self.alpha_2_doubleSpinBox.setObjectName("alpha_2_doubleSpinBox")
        self.Automatic_Relevance_Determination_form.setWidget(4, QtWidgets.QFormLayout.FieldRole,
                                                              self.alpha_2_doubleSpinBox)
        self.lambda_2_label = QtWidgets.QLabel(self.groupbox)
        self.lambda_2_label.setObjectName("lambda_2_label")
        self.Automatic_Relevance_Determination_form.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lambda_2_label)
        self.lambda_2_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupbox)
        self.lambda_2_doubleSpinBox.setDecimals(8)
        self.lambda_2_doubleSpinBox.setMinimum(-99.0)
        self.lambda_2_doubleSpinBox.setSingleStep(1e-06)
        self.lambda_2_doubleSpinBox.setProperty("value", 1e-06)
        self.lambda_2_doubleSpinBox.setObjectName("lambda_2_doubleSpinBox")
        self.Automatic_Relevance_Determination_form.setWidget(5, QtWidgets.QFormLayout.FieldRole,
                                                              self.lambda_2_doubleSpinBox)
        self.compute_score_label = QtWidgets.QLabel(self.groupbox)
        self.compute_score_label.setObjectName("compute_score_label")
        self.Automatic_Relevance_Determination_form.setWidget(6, QtWidgets.QFormLayout.LabelRole,
                                                              self.compute_score_label)
        self.compute_score_checkBox = QtWidgets.QCheckBox(self.groupbox)
        self.compute_score_checkBox.setCheckable(True)
        self.compute_score_checkBox.setChecked(False)
        self.compute_score_checkBox.setObjectName("compute_score_checkBox")
        self.Automatic_Relevance_Determination_form.setWidget(6, QtWidgets.QFormLayout.FieldRole,
                                                              self.compute_score_checkBox)
        self.fit_intercept_label = QtWidgets.QLabel(self.groupbox)
        self.fit_intercept_label.setObjectName("fit_intercept_label")
        self.Automatic_Relevance_Determination_form.setWidget(8, QtWidgets.QFormLayout.LabelRole,
                                                              self.fit_intercept_label)
        self.fit_intercept_checkBox = QtWidgets.QCheckBox(self.groupbox)
        self.fit_intercept_checkBox.setCheckable(True)
        self.fit_intercept_checkBox.setChecked(True)
        self.fit_intercept_checkBox.setObjectName("fit_intercept_checkBox")
        self.Automatic_Relevance_Determination_form.setWidget(8, QtWidgets.QFormLayout.FieldRole,
                                                              self.fit_intercept_checkBox)
        self.normalize_label = QtWidgets.QLabel(self.groupbox)
        self.normalize_label.setObjectName("normalize_label")
        self.Automatic_Relevance_Determination_form.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.normalize_label)
        self.normalize_checkBox = QtWidgets.QCheckBox(self.groupbox)
        self.normalize_checkBox.setCheckable(True)
        self.normalize_checkBox.setChecked(False)
        self.normalize_checkBox.setObjectName("normalize_checkBox")
        self.Automatic_Relevance_Determination_form.setWidget(9, QtWidgets.QFormLayout.FieldRole,
                                                              self.normalize_checkBox)
        self.copy_X_label = QtWidgets.QLabel(self.groupbox)
        self.copy_X_label.setObjectName("copy_X_label")
        self.Automatic_Relevance_Determination_form.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.copy_X_label)
        self.copy_X_checkBox = QtWidgets.QCheckBox(self.groupbox)
        self.copy_X_checkBox.setCheckable(True)
        self.copy_X_checkBox.setChecked(True)
        self.copy_X_checkBox.setObjectName("copy_X_checkBox")
        self.Automatic_Relevance_Determination_form.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.copy_X_checkBox)
        self.verbose_label = QtWidgets.QLabel(self.groupbox)
        self.verbose_label.setObjectName("verbose_label")
        self.Automatic_Relevance_Determination_form.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.verbose_label)
        self.verbose_checkBox = QtWidgets.QCheckBox(self.groupbox)
        self.verbose_checkBox.setCheckable(True)
        self.verbose_checkBox.setChecked(False)
        self.verbose_checkBox.setObjectName("verbose_checkBox")
        self.Automatic_Relevance_Determination_form.setWidget(11, QtWidgets.QFormLayout.FieldRole,
                                                              self.verbose_checkBox)
        self.threshold_lambda_label = QtWidgets.QLabel(self.groupbox)
        self.threshold_lambda_label.setObjectName("threshold_lambda_label")
        self.Automatic_Relevance_Determination_form.setWidget(7, QtWidgets.QFormLayout.LabelRole,
                                                              self.threshold_lambda_label)
        self.threshold_lambda_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupbox)
        self.threshold_lambda_doubleSpinBox.setDecimals(2)
        self.threshold_lambda_doubleSpinBox.setMinimum(-99.0)
        self.threshold_lambda_doubleSpinBox.setMaximum(999999999.0)
        self.threshold_lambda_doubleSpinBox.setSingleStep(1.0)
        self.threshold_lambda_doubleSpinBox.setProperty("value", 10000.0)
        self.threshold_lambda_doubleSpinBox.setObjectName("threshold_lambda_doubleSpinBox")
        self.Automatic_Relevance_Determination_form.setWidget(7, QtWidgets.QFormLayout.FieldRole,
                                                              self.threshold_lambda_doubleSpinBox)
        self.verticalLayout_2.addWidget(self.groupbox)

        self.n_inter_label.setText("Number of iterations")
        self.tol_label.setText("Tol")
        self.alpha_1_label.setText("alpha_1")
        self.alpha_2_label.setText("alpha_2")
        self.lambda_2_label.setText("lambda_2")
        self.compute_score_label.setText("compute_score")
        self.compute_score_checkBox.setText("compute the objective function at each step of the model")
        self.fit_intercept_label.setText("fit_intercept")
        self.fit_intercept_checkBox.setText("calculate the intercept for this model")
        self.normalize_label.setText("normalize")
        self.normalize_checkBox.setText("regressors X will be normalized before regression")
        self.copy_X_label.setText("copy_X")
        self.copy_X_checkBox.setText("X will be copied; else, it may be overwritten")
        self.verbose_label.setText("verbose")
        self.verbose_checkBox.setText("Verbose mode when fitting the model")
        self.threshold_lambda_label.setText("threshold_lambda")
