from PyQt5 import QtWidgets


class KernelRidgeRegression():
    def kernelRidgeRegression(self):
        self.line = QtWidgets.QFrame(self.regression)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.min_max_layout.addWidget(self.line)
        self.formGroupBox = QtWidgets.QGroupBox(self.regression)
        self.formGroupBox.setObjectName("formGroupBox")
        self.Kernel_Ridge_Regression_formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.Kernel_Ridge_Regression_formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.Kernel_Ridge_Regression_formLayout.setContentsMargins(11, 11, 11, 11)
        self.Kernel_Ridge_Regression_formLayout.setSpacing(6)
        self.Kernel_Ridge_Regression_formLayout.setObjectName("Kernel_Ridge_Regression_formLayout")
        self.alpha_label = QtWidgets.QLabel(self.formGroupBox)
        self.alpha_label.setObjectName("alpha_label")
        self.Kernel_Ridge_Regression_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.alpha_label)
        self.alpha_spinBox = QtWidgets.QSpinBox(self.formGroupBox)
        self.alpha_spinBox.setObjectName("alpha_spinBox")
        self.Kernel_Ridge_Regression_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.alpha_spinBox)
        self.kernel_label = QtWidgets.QLabel(self.formGroupBox)
        self.kernel_label.setObjectName("kernel_label")
        self.Kernel_Ridge_Regression_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.kernel_label)
        self.lineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.Kernel_Ridge_Regression_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.gamma_label = QtWidgets.QLabel(self.formGroupBox)
        self.gamma_label.setObjectName("gamma_label")
        self.Kernel_Ridge_Regression_formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gamma_label)
        self.degree_label = QtWidgets.QLabel(self.formGroupBox)
        self.degree_label.setObjectName("degree_label")
        self.Kernel_Ridge_Regression_formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.degree_label)
        self.coef0_label = QtWidgets.QLabel(self.formGroupBox)
        self.coef0_label.setObjectName("coef0_label")
        self.Kernel_Ridge_Regression_formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.coef0_label)
        self.kernel_params_label = QtWidgets.QLabel(self.formGroupBox)
        self.kernel_params_label.setObjectName("kernel_params_label")
        self.Kernel_Ridge_Regression_formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.kernel_params_label)
        self.degree_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.formGroupBox)
        self.degree_doubleSpinBox.setProperty("value", 3.0)
        self.degree_doubleSpinBox.setObjectName("degree_doubleSpinBox")
        self.Kernel_Ridge_Regression_formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.degree_doubleSpinBox)
        self.coef0_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.formGroupBox)
        self.coef0_doubleSpinBox.setProperty("value", 1.0)
        self.coef0_doubleSpinBox.setObjectName("coef0_doubleSpinBox")
        self.Kernel_Ridge_Regression_formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.coef0_doubleSpinBox)
        self.kernel_params_lineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.kernel_params_lineEdit.setObjectName("kernel_params_lineEdit")
        self.Kernel_Ridge_Regression_formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole,
                                                          self.kernel_params_lineEdit)
        self.gamma_lineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.gamma_lineEdit.setObjectName("gamma_lineEdit")
        self.Kernel_Ridge_Regression_formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gamma_lineEdit)
        self.verticalLayout_2.addWidget(self.formGroupBox)

        self.alpha_label.setText("alpha")
        self.kernel_label.setText("kernel")
        self.lineEdit.setText("linear")
        self.gamma_label.setText("gamma")
        self.degree_label.setText("degree")
        self.coef0_label.setText("coef0")
        self.kernel_params_label.setText("kernel_params")
        self.kernel_params_lineEdit.setText("None")
        self.gamma_lineEdit.setText("None")
