from PyQt5 import QtWidgets


class SupportVectorRegression:
    def SVR(self):
        self.line = QtWidgets.QFrame(self.regression)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.min_max_layout.addWidget(self.line)
        self.groupbox = QtWidgets.QGroupBox(self.regression)
        self.groupbox.setObjectName("groupbox")
        self.Support_Vector_Regression_form = QtWidgets.QFormLayout(self.groupbox)
        self.Support_Vector_Regression_form.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.Support_Vector_Regression_form.setContentsMargins(11, 11, 11, 11)
        self.Support_Vector_Regression_form.setSpacing(6)
        self.Support_Vector_Regression_form.setObjectName("Support_Vector_Regression_form")
        self.C_label = QtWidgets.QLabel(self.groupbox)
        self.C_label.setObjectName("C_label")
        self.Support_Vector_Regression_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.C_label)
        self.C_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupbox)
        self.C_doubleSpinBox.setMinimum(-999999999.0)
        self.C_doubleSpinBox.setMaximum(999999999.0)
        self.C_doubleSpinBox.setProperty("value", 1.0)
        self.C_doubleSpinBox.setObjectName("C_doubleSpinBox")
        self.Support_Vector_Regression_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.C_doubleSpinBox)
        self.epsilon_label = QtWidgets.QLabel(self.groupbox)
        self.epsilon_label.setObjectName("epsilon_label")
        self.Support_Vector_Regression_form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.epsilon_label)
        self.epsilon_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupbox)
        self.epsilon_doubleSpinBox.setMinimum(-999999999.0)
        self.epsilon_doubleSpinBox.setMaximum(999999999.0)
        self.epsilon_doubleSpinBox.setProperty("value", 0.1)
        self.epsilon_doubleSpinBox.setObjectName("epsilon_doubleSpinBox")
        self.Support_Vector_Regression_form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.epsilon_doubleSpinBox)
        self.kernel_label = QtWidgets.QLabel(self.groupbox)
        self.kernel_label.setObjectName("kernel_label")
        self.Support_Vector_Regression_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.kernel_label)
        self.kernel_comboBox = QtWidgets.QComboBox(self.groupbox)
        self.kernel_comboBox.setObjectName("kernel_comboBox")
        self.kernel_comboBox.addItem("")
        self.kernel_comboBox.addItem("")
        self.kernel_comboBox.addItem("")
        self.kernel_comboBox.addItem("")
        self.Support_Vector_Regression_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.kernel_comboBox)
        self.degree_label = QtWidgets.QLabel(self.groupbox)
        self.degree_label.setObjectName("degree_label")
        self.Support_Vector_Regression_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.degree_label)
        self.degree_spinBox = QtWidgets.QSpinBox(self.groupbox)
        self.degree_spinBox.setMaximum(999999999)
        self.degree_spinBox.setProperty("value", 3)
        self.degree_spinBox.setObjectName("degree_spinBox")
        self.Support_Vector_Regression_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.degree_spinBox)
        self.coef0_label = QtWidgets.QLabel(self.groupbox)
        self.coef0_label.setObjectName("coef0_label")
        self.Support_Vector_Regression_form.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.coef0_label)
        self.coef0_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupbox)
        self.coef0_doubleSpinBox.setObjectName("coef0_doubleSpinBox")
        self.Support_Vector_Regression_form.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.coef0_doubleSpinBox)
        self.shrinking_label = QtWidgets.QLabel(self.groupbox)
        self.shrinking_label.setObjectName("shrinking_label")
        self.Support_Vector_Regression_form.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.shrinking_label)
        self.shrinking_checkBox = QtWidgets.QCheckBox(self.groupbox)
        self.shrinking_checkBox.setChecked(True)
        self.shrinking_checkBox.setObjectName("shrinking_checkBox")
        self.Support_Vector_Regression_form.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.shrinking_checkBox)
        self.tol_label = QtWidgets.QLabel(self.groupbox)
        self.tol_label.setObjectName("tol_label")
        self.Support_Vector_Regression_form.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.tol_label)
        self.tol__doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupbox)
        self.tol__doubleSpinBox.setDecimals(3)
        self.tol__doubleSpinBox.setMinimum(-999999999.0)
        self.tol__doubleSpinBox.setMaximum(999999999.0)
        self.tol__doubleSpinBox.setSingleStep(0.001)
        self.tol__doubleSpinBox.setProperty("value", 0.001)
        self.tol__doubleSpinBox.setObjectName("tol__doubleSpinBox")
        self.Support_Vector_Regression_form.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.tol__doubleSpinBox)
        self.cache_size_label = QtWidgets.QLabel(self.groupbox)
        self.cache_size_label.setObjectName("cache_size_label")
        self.Support_Vector_Regression_form.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.cache_size_label)
        self.cache_size_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupbox)
        self.cache_size_doubleSpinBox.setDecimals(0)
        self.cache_size_doubleSpinBox.setMaximum(999999999.0)
        self.cache_size_doubleSpinBox.setProperty("value", 200.0)
        self.cache_size_doubleSpinBox.setObjectName("cache_size_doubleSpinBox")
        self.Support_Vector_Regression_form.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.cache_size_doubleSpinBox)
        self.verbose_label = QtWidgets.QLabel(self.groupbox)
        self.verbose_label.setObjectName("verbose_label")
        self.Support_Vector_Regression_form.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.verbose_label)
        self.verbose_checkBox = QtWidgets.QCheckBox(self.groupbox)
        self.verbose_checkBox.setObjectName("verbose_checkBox")
        self.Support_Vector_Regression_form.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.verbose_checkBox)
        self.max_iter_label = QtWidgets.QLabel(self.groupbox)
        self.max_iter_label.setObjectName("max_iter_label")
        self.Support_Vector_Regression_form.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.max_iter_label)
        self.max_iter_spinBox = QtWidgets.QSpinBox(self.groupbox)
        self.max_iter_spinBox.setMinimum(-999999999)
        self.max_iter_spinBox.setMaximum(999999999)
        self.max_iter_spinBox.setProperty("value", -1)
        self.max_iter_spinBox.setObjectName("max_iter_spinBox")
        self.Support_Vector_Regression_form.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.max_iter_spinBox)
        self.gamma_label = QtWidgets.QLabel(self.groupbox)
        self.gamma_label.setObjectName("gamma_label")
        self.Support_Vector_Regression_form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.gamma_label)
        self.gamma_comboBox = QtWidgets.QComboBox(self.groupbox)
        self.gamma_comboBox.setObjectName("gamma_comboBox")
        self.gamma_comboBox.addItem("")
        self.gamma_comboBox.addItem("")
        self.gamma_comboBox.addItem("")
        self.gamma_comboBox.addItem("")
        self.Support_Vector_Regression_form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.gamma_comboBox)
        self.verticalLayout_2.addWidget(self.groupbox)

        self.C_label.setText("C")
        self.epsilon_label.setText("epsilon")
        self.kernel_label.setText("kernel")
        self.kernel_comboBox.setItemText(0, "rbf")
        self.kernel_comboBox.setItemText(1, "linear")
        self.kernel_comboBox.setItemText(2, "poly")
        self.kernel_comboBox.setItemText(3, "precomputed")
        self.degree_label.setText("degree")
        self.coef0_label.setText("coef0")
        self.shrinking_label.setText("shrinking")
        self.shrinking_checkBox.setText("use the shrinking heuristic")
        self.tol_label.setText("tol")
        self.cache_size_label.setText("cache_size")
        self.verbose_label.setText("verbose")
        self.verbose_checkBox.setText("use the shrinking heuristic")
        self.max_iter_label.setText("max_iter")
        self.gamma_label.setText("gamma")
        self.gamma_comboBox.setItemText(0, "rbf")
        self.gamma_comboBox.setItemText(1, "linear")
        self.gamma_comboBox.setItemText(2, "poly")
        self.gamma_comboBox.setItemText(3, "precomputed")
