# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(538, 317)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.chooseDataLabel = QtWidgets.QLabel(Form)
        self.chooseDataLabel.setObjectName("chooseDataLabel")
        self.gridLayout.addWidget(self.chooseDataLabel, 0, 0, 1, 1)
        self.xVariableLabel = QtWidgets.QLabel(Form)
        self.xVariableLabel.setObjectName("xVariableLabel")
        self.gridLayout.addWidget(self.xVariableLabel, 1, 0, 1, 1)
        self.yVariableLabel = QtWidgets.QLabel(Form)
        self.yVariableLabel.setObjectName("yVariableLabel")
        self.gridLayout.addWidget(self.yVariableLabel, 1, 3, 1, 1)
        self.xVariableList = QtWidgets.QListWidget(Form)
        self.xVariableList.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xVariableList.sizePolicy().hasHeightForWidth())
        self.xVariableList.setSizePolicy(sizePolicy)
        self.xVariableList.setMinimumSize(QtCore.QSize(0, 0))
        self.xVariableList.setMaximumSize(QtCore.QSize(900, 16777215))
        self.xVariableList.setObjectName("xVariableList")
        item = QtWidgets.QListWidgetItem()
        self.xVariableList.addItem(item)
        self.gridLayout.addWidget(self.xVariableList, 2, 0, 1, 3)
        self.yVariableList = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yVariableList.sizePolicy().hasHeightForWidth())
        self.yVariableList.setSizePolicy(sizePolicy)
        self.yVariableList.setMinimumSize(QtCore.QSize(0, 0))
        self.yVariableList.setMaximumSize(QtCore.QSize(900, 16777215))
        self.yVariableList.setObjectName("yVariableList")
        item = QtWidgets.QListWidgetItem()
        self.yVariableList.addItem(item)
        self.gridLayout.addWidget(self.yVariableList, 2, 3, 1, 4)
        self.yMaxLabel = QtWidgets.QLabel(Form)
        self.yMaxLabel.setObjectName("yMaxLabel")
        self.gridLayout.addWidget(self.yMaxLabel, 3, 3, 1, 1)
        self.yMaxDoubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.yMaxDoubleSpinBox.setObjectName("yMaxDoubleSpinBox")
        self.gridLayout.addWidget(self.yMaxDoubleSpinBox, 3, 4, 1, 1)
        self.yMinLabel = QtWidgets.QLabel(Form)
        self.yMinLabel.setObjectName("yMinLabel")
        self.gridLayout.addWidget(self.yMinLabel, 3, 5, 1, 1)
        self.yMinDoubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.yMinDoubleSpinBox.setObjectName("yMinDoubleSpinBox")
        self.gridLayout.addWidget(self.yMinDoubleSpinBox, 3, 6, 1, 1)
        self.chooseAlgorithmLabel = QtWidgets.QLabel(Form)
        self.chooseAlgorithmLabel.setObjectName("chooseAlgorithmLabel")
        self.gridLayout.addWidget(self.chooseAlgorithmLabel, 4, 0, 1, 1)
        self.algorithmLayout = QtWidgets.QVBoxLayout()
        self.algorithmLayout.setObjectName("algorithmLayout")
        self.gridLayout.addLayout(self.algorithmLayout, 5, 0, 1, 7)
        self.chooseAlgorithmComboBox = QtWidgets.QComboBox(Form)
        self.chooseAlgorithmComboBox.setObjectName("chooseAlgorithmComboBox")
        self.gridLayout.addWidget(self.chooseAlgorithmComboBox, 4, 1, 1, 2)
        self.chooseDataComboBox = QtWidgets.QComboBox(Form)
        self.chooseDataComboBox.setObjectName("chooseDataComboBox")
        self.gridLayout.addWidget(self.chooseDataComboBox, 0, 1, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(("Form"))
        self.chooseDataLabel.setText(("Choose Data"))
        self.xVariableLabel.setText(("X Variable"))
        self.yVariableLabel.setText(("Y Variable"))
        __sortingEnabled = self.xVariableList.isSortingEnabled()
        self.xVariableList.setSortingEnabled(False)
        item = self.xVariableList.item(0)
        item.setText(("Choose X"))
        self.xVariableList.setSortingEnabled(__sortingEnabled)
        self.yVariableList.setSortingEnabled(True)
        __sortingEnabled = self.yVariableList.isSortingEnabled()
        self.yVariableList.setSortingEnabled(False)
        item = self.yVariableList.item(0)
        item.setText(("Choose Y"))
        self.yVariableList.setSortingEnabled(__sortingEnabled)
        self.yMaxLabel.setText(("Y Max"))
        self.yMinLabel.setText(("Y Min"))
        self.chooseAlgorithmLabel.setText(("Choose Algorithm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

