# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nfinch\Desktop\GitHub\PySAT_Point_Spectra_GUI\ui\LARS.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(677, 267)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formGroupBox = QtWidgets.QGroupBox(Form)
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.numOfNonzeroCoeffsLabel = QtWidgets.QLabel(self.formGroupBox)
        self.numOfNonzeroCoeffsLabel.setObjectName("numOfNonzeroCoeffsLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.numOfNonzeroCoeffsLabel)
        self.numOfNonzeroCoeffsSpinBox = QtWidgets.QSpinBox(self.formGroupBox)
        self.numOfNonzeroCoeffsSpinBox.setEnabled(False)
        self.numOfNonzeroCoeffsSpinBox.setMaximum(999999)
        self.numOfNonzeroCoeffsSpinBox.setProperty("value", 500)
        self.numOfNonzeroCoeffsSpinBox.setObjectName("numOfNonzeroCoeffsSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.numOfNonzeroCoeffsSpinBox)
        self.fitInterceptLabel = QtWidgets.QLabel(self.formGroupBox)
        self.fitInterceptLabel.setObjectName("fitInterceptLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fitInterceptLabel)
        self.fitInterceptCheckBox = QtWidgets.QCheckBox(self.formGroupBox)
        self.fitInterceptCheckBox.setChecked(True)
        self.fitInterceptCheckBox.setObjectName("fitInterceptCheckBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fitInterceptCheckBox)
        self.positiveLabel = QtWidgets.QLabel(self.formGroupBox)
        self.positiveLabel.setObjectName("positiveLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.positiveLabel)
        self.positiveCheckBox = QtWidgets.QCheckBox(self.formGroupBox)
        self.positiveCheckBox.setObjectName("positiveCheckBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.positiveCheckBox)
        self.verboseLabel = QtWidgets.QLabel(self.formGroupBox)
        self.verboseLabel.setObjectName("verboseLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.verboseLabel)
        self.verboseCheckBox = QtWidgets.QCheckBox(self.formGroupBox)
        self.verboseCheckBox.setObjectName("verboseCheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.verboseCheckBox)
        self.normalizeLabel = QtWidgets.QLabel(self.formGroupBox)
        self.normalizeLabel.setObjectName("normalizeLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.normalizeLabel)
        self.normalizeCheckBox = QtWidgets.QCheckBox(self.formGroupBox)
        self.normalizeCheckBox.setObjectName("normalizeCheckBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.normalizeCheckBox)
        self.precomputeLabel = QtWidgets.QLabel(self.formGroupBox)
        self.precomputeLabel.setObjectName("precomputeLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.precomputeLabel)
        self.precomputeComboBox = QtWidgets.QComboBox(self.formGroupBox)
        self.precomputeComboBox.setObjectName("precomputeComboBox")
        self.precomputeComboBox.addItem("")
        self.precomputeComboBox.addItem("")
        self.precomputeComboBox.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.precomputeComboBox)
        self.copyXLabel = QtWidgets.QLabel(self.formGroupBox)
        self.copyXLabel.setObjectName("copyXLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.copyXLabel)
        self.copyXCheckBox = QtWidgets.QCheckBox(self.formGroupBox)
        self.copyXCheckBox.setChecked(True)
        self.copyXCheckBox.setObjectName("copyXCheckBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.copyXCheckBox)
        self.epsLabel = QtWidgets.QLabel(self.formGroupBox)
        self.epsLabel.setObjectName("epsLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.epsLabel)
        self.fitPathLabel = QtWidgets.QLabel(self.formGroupBox)
        self.fitPathLabel.setObjectName("fitPathLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.fitPathLabel)
        self.fitPathCheckBox = QtWidgets.QCheckBox(self.formGroupBox)
        self.fitPathCheckBox.setChecked(True)
        self.fitPathCheckBox.setObjectName("fitPathCheckBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.fitPathCheckBox)
        self.crossValidatePathLabel = QtWidgets.QLabel(self.formGroupBox)
        self.crossValidatePathLabel.setObjectName("crossValidatePathLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.crossValidatePathLabel)
        self.crossValidateCheckBox = QtWidgets.QCheckBox(self.formGroupBox)
        self.crossValidateCheckBox.setText("")
        self.crossValidateCheckBox.setChecked(True)
        self.crossValidateCheckBox.setObjectName("crossValidateCheckBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.crossValidateCheckBox)
        self.epsDoubleLineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.epsDoubleLineEdit.setObjectName("epsDoubleLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.epsDoubleLineEdit)
        self.verticalLayout.addWidget(self.formGroupBox)

        self.retranslateUi(Form)
        self.crossValidateCheckBox.toggled['bool'].connect(self.numOfNonzeroCoeffsSpinBox.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.numOfNonzeroCoeffsSpinBox, self.fitInterceptCheckBox)
        Form.setTabOrder(self.fitInterceptCheckBox, self.positiveCheckBox)
        Form.setTabOrder(self.positiveCheckBox, self.verboseCheckBox)
        Form.setTabOrder(self.verboseCheckBox, self.normalizeCheckBox)
        Form.setTabOrder(self.normalizeCheckBox, self.precomputeComboBox)
        Form.setTabOrder(self.precomputeComboBox, self.copyXCheckBox)
        Form.setTabOrder(self.copyXCheckBox, self.fitPathCheckBox)
        Form.setTabOrder(self.fitPathCheckBox, self.crossValidateCheckBox)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.numOfNonzeroCoeffsLabel.setText(_translate("Form", "Num of Nonzero Coeffs"))
        self.fitInterceptLabel.setText(_translate("Form", "Fit Intercept"))
        self.fitInterceptCheckBox.setText(_translate("Form", "Calculate the intercept for this model"))
        self.positiveLabel.setText(_translate("Form", "Positive"))
        self.positiveCheckBox.setText(_translate("Form", "Restrict coefficients to be >= 0"))
        self.verboseLabel.setText(_translate("Form", "Verbose"))
        self.verboseCheckBox.setText(_translate("Form", "Verbose mode when fitting the model"))
        self.normalizeLabel.setText(_translate("Form", "Normalize"))
        self.normalizeCheckBox.setText(_translate("Form", "If True, the regressors X will be normalized before regression. ignored when fit_intercept is set to False."))
        self.precomputeLabel.setText(_translate("Form", "Precompute"))
        self.precomputeComboBox.setItemText(0, _translate("Form", "True"))
        self.precomputeComboBox.setItemText(1, _translate("Form", "False"))
        self.precomputeComboBox.setItemText(2, _translate("Form", "auto"))
        self.copyXLabel.setText(_translate("Form", "Copy X"))
        self.copyXCheckBox.setText(_translate("Form", "Computer the objective function at each step of the model"))
        self.epsLabel.setText(_translate("Form", "Eps"))
        self.fitPathLabel.setText(_translate("Form", "Fit Path"))
        self.fitPathCheckBox.setText(_translate("Form", "Store the full path in the coef_path_attribute"))
        self.crossValidatePathLabel.setText(_translate("Form", "Cross Validate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

