# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nfinch\Desktop\GitHub\PySAT_Point_Spectra_GUI\ui\Plot.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topLayout = QtWidgets.QFormLayout()
        self.topLayout.setObjectName("topLayout")
        self.chooseDataLabel = QtWidgets.QLabel(self.groupBox)
        self.chooseDataLabel.setObjectName("chooseDataLabel")
        self.topLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.chooseDataLabel)
        self.chooseDataComboBox = QtWidgets.QComboBox(self.groupBox)
        self.chooseDataComboBox.setObjectName("chooseDataComboBox")
        self.topLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.chooseDataComboBox)
        self.figureNameLabel = QtWidgets.QLabel(self.groupBox)
        self.figureNameLabel.setObjectName("figureNameLabel")
        self.topLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.figureNameLabel)
        self.figureNameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.figureNameLineEdit.setObjectName("figureNameLineEdit")
        self.topLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.figureNameLineEdit)
        self.plotTitleLabel = QtWidgets.QLabel(self.groupBox)
        self.plotTitleLabel.setObjectName("plotTitleLabel")
        self.topLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.plotTitleLabel)
        self.plotTitleLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.plotTitleLineEdit.setObjectName("plotTitleLineEdit")
        self.topLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.plotTitleLineEdit)
        self.verticalLayout.addLayout(self.topLayout)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.XYLayout = QtWidgets.QHBoxLayout()
        self.XYLayout.setObjectName("XYLayout")
        self.xLayout = QtWidgets.QFormLayout()
        self.xLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.xLayout.setObjectName("xLayout")
        self.chooseXVariableLabel = QtWidgets.QLabel(self.groupBox)
        self.chooseXVariableLabel.setObjectName("chooseXVariableLabel")
        self.xLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.chooseXVariableLabel)
        self.chooseXVariableComboBox = QtWidgets.QComboBox(self.groupBox)
        self.chooseXVariableComboBox.setObjectName("chooseXVariableComboBox")
        self.xLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.chooseXVariableComboBox)
        self.xTitleLabel = QtWidgets.QLabel(self.groupBox)
        self.xTitleLabel.setObjectName("xTitleLabel")
        self.xLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.xTitleLabel)
        self.xTitleLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.xTitleLineEdit.setObjectName("xTitleLineEdit")
        self.xLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.xTitleLineEdit)
        self.xMinLabel = QtWidgets.QLabel(self.groupBox)
        self.xMinLabel.setObjectName("xMinLabel")
        self.xLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.xMinLabel)
        self.xMinLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.xMinLineEdit.setObjectName("xMinLineEdit")
        self.xLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.xMinLineEdit)
        self.xMaxLabel = QtWidgets.QLabel(self.groupBox)
        self.xMaxLabel.setObjectName("xMaxLabel")
        self.xLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.xMaxLabel)
        self.xMaxLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.xMaxLineEdit.setObjectName("xMaxLineEdit")
        self.xLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.xMaxLineEdit)
        self.XYLayout.addLayout(self.xLayout)
        self.yLayout = QtWidgets.QFormLayout()
        self.yLayout.setObjectName("yLayout")
        self.chooseYVariableLabel = QtWidgets.QLabel(self.groupBox)
        self.chooseYVariableLabel.setObjectName("chooseYVariableLabel")
        self.yLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.chooseYVariableLabel)
        self.chooseYVariableComboBox = QtWidgets.QComboBox(self.groupBox)
        self.chooseYVariableComboBox.setObjectName("chooseYVariableComboBox")
        self.yLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.chooseYVariableComboBox)
        self.xTitleLabel_3 = QtWidgets.QLabel(self.groupBox)
        self.xTitleLabel_3.setObjectName("xTitleLabel_3")
        self.yLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.xTitleLabel_3)
        self.xTitleLineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.xTitleLineEdit_3.setObjectName("xTitleLineEdit_3")
        self.yLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.xTitleLineEdit_3)
        self.xMinLabel_3 = QtWidgets.QLabel(self.groupBox)
        self.xMinLabel_3.setObjectName("xMinLabel_3")
        self.yLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.xMinLabel_3)
        self.xMinLineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.xMinLineEdit_3.setObjectName("xMinLineEdit_3")
        self.yLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.xMinLineEdit_3)
        self.xMaxLabel_3 = QtWidgets.QLabel(self.groupBox)
        self.xMaxLabel_3.setObjectName("xMaxLabel_3")
        self.yLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.xMaxLabel_3)
        self.xMaxLineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.xMaxLineEdit_3.setObjectName("xMaxLineEdit_3")
        self.yLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.xMaxLineEdit_3)
        self.XYLayout.addLayout(self.yLayout)
        self.verticalLayout.addLayout(self.XYLayout)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.botLayout = QtWidgets.QGridLayout()
        self.botLayout.setObjectName("botLayout")
        self.alphaLabel = QtWidgets.QLabel(self.groupBox)
        self.alphaLabel.setObjectName("alphaLabel")
        self.botLayout.addWidget(self.alphaLabel, 3, 0, 1, 1)
        self.markerLabel = QtWidgets.QLabel(self.groupBox)
        self.markerLabel.setObjectName("markerLabel")
        self.botLayout.addWidget(self.markerLabel, 2, 0, 1, 1)
        self.alphaDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.alphaDoubleSpinBox.setObjectName("alphaDoubleSpinBox")
        self.botLayout.addWidget(self.alphaDoubleSpinBox, 3, 1, 1, 1)
        self.plotFilenameLabel = QtWidgets.QLabel(self.groupBox)
        self.plotFilenameLabel.setObjectName("plotFilenameLabel")
        self.botLayout.addWidget(self.plotFilenameLabel, 4, 0, 1, 1)
        self.lineComboBox = QtWidgets.QComboBox(self.groupBox)
        self.lineComboBox.setObjectName("lineComboBox")
        self.botLayout.addWidget(self.lineComboBox, 1, 1, 1, 1)
        self.lineLabel = QtWidgets.QLabel(self.groupBox)
        self.lineLabel.setObjectName("lineLabel")
        self.botLayout.addWidget(self.lineLabel, 1, 0, 1, 1)
        self.plotFilenameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.plotFilenameLineEdit.setObjectName("plotFilenameLineEdit")
        self.botLayout.addWidget(self.plotFilenameLineEdit, 4, 1, 1, 1)
        self.colorComboBox = QtWidgets.QComboBox(self.groupBox)
        self.colorComboBox.setObjectName("colorComboBox")
        self.botLayout.addWidget(self.colorComboBox, 0, 1, 1, 1)
        self.colorLabel = QtWidgets.QLabel(self.groupBox)
        self.colorLabel.setObjectName("colorLabel")
        self.botLayout.addWidget(self.colorLabel, 0, 0, 1, 1)
        self.markerComboBox = QtWidgets.QComboBox(self.groupBox)
        self.markerComboBox.setObjectName("markerComboBox")
        self.botLayout.addWidget(self.markerComboBox, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.botLayout.addWidget(self.pushButton, 4, 2, 1, 1)
        self.verticalLayout.addLayout(self.botLayout)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Plot"))
        self.chooseDataLabel.setText(_translate("Form", "Choose data"))
        self.figureNameLabel.setText(_translate("Form", "Figure name"))
        self.plotTitleLabel.setText(_translate("Form", "Plot Title"))
        self.chooseXVariableLabel.setText(_translate("Form", "Choose X Variable"))
        self.xTitleLabel.setText(_translate("Form", "X title"))
        self.xMinLabel.setText(_translate("Form", "X min"))
        self.xMaxLabel.setText(_translate("Form", "X max"))
        self.chooseYVariableLabel.setText(_translate("Form", "Choose Y Variable"))
        self.xTitleLabel_3.setText(_translate("Form", "X title"))
        self.xMinLabel_3.setText(_translate("Form", "X min"))
        self.xMaxLabel_3.setText(_translate("Form", "X max"))
        self.alphaLabel.setText(_translate("Form", "Alpha"))
        self.markerLabel.setText(_translate("Form", "Marker"))
        self.plotFilenameLabel.setText(_translate("Form", "Plot Filename"))
        self.lineLabel.setText(_translate("Form", "Line"))
        self.colorLabel.setText(_translate("Form", "Color"))
        self.pushButton.setText(_translate("Form", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

