# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.vboxlayout = QtWidgets.QVBoxLayout(Form)
        self.vboxlayout.setObjectName("vboxlayout")
        self.groupbox = QtWidgets.QGroupBox(Form)
        self.groupbox.setObjectName("groupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formGroupBox = QtWidgets.QGroupBox(self.groupbox)
        self.formGroupBox.setEnabled(False)
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.alphaLabel_2 = QtWidgets.QLabel(self.formGroupBox)
        self.alphaLabel_2.setObjectName("alphaLabel_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.alphaLabel_2)
        self.alphaDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.formGroupBox)
        self.alphaDoubleSpinBox_2.setProperty("value", 1.0)
        self.alphaDoubleSpinBox_2.setObjectName("alphaDoubleSpinBox_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.alphaDoubleSpinBox_2)
        self.copyXLabel_2 = QtWidgets.QLabel(self.formGroupBox)
        self.copyXLabel_2.setObjectName("copyXLabel_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.copyXLabel_2)
        self.copyXCheckBox_2 = QtWidgets.QCheckBox(self.formGroupBox)
        self.copyXCheckBox_2.setChecked(True)
        self.copyXCheckBox_2.setObjectName("copyXCheckBox_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.copyXCheckBox_2)
        self.fitInterceptLabel_4 = QtWidgets.QLabel(self.formGroupBox)
        self.fitInterceptLabel_4.setObjectName("fitInterceptLabel_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fitInterceptLabel_4)
        self.fitInterceptCheckBox_4 = QtWidgets.QCheckBox(self.formGroupBox)
        self.fitInterceptCheckBox_4.setChecked(True)
        self.fitInterceptCheckBox_4.setObjectName("fitInterceptCheckBox_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fitInterceptCheckBox_4)
        self.maxNumOfIterationsLabel_2 = QtWidgets.QLabel(self.formGroupBox)
        self.maxNumOfIterationsLabel_2.setObjectName("maxNumOfIterationsLabel_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.maxNumOfIterationsLabel_2)
        self.maxNumOfIterationslineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox)
        self.maxNumOfIterationslineEdit_2.setObjectName("maxNumOfIterationslineEdit_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.maxNumOfIterationslineEdit_2)
        self.normalizeLabel_4 = QtWidgets.QLabel(self.formGroupBox)
        self.normalizeLabel_4.setObjectName("normalizeLabel_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.normalizeLabel_4)
        self.normalizeCheckBox_4 = QtWidgets.QCheckBox(self.formGroupBox)
        self.normalizeCheckBox_4.setObjectName("normalizeCheckBox_4")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.normalizeCheckBox_4)
        self.solverLabel_2 = QtWidgets.QLabel(self.formGroupBox)
        self.solverLabel_2.setObjectName("solverLabel_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.solverLabel_2)
        self.solverComboBox_2 = QtWidgets.QComboBox(self.formGroupBox)
        self.solverComboBox_2.setObjectName("solverComboBox_2")
        self.solverComboBox_2.addItem("")
        self.solverComboBox_2.addItem("")
        self.solverComboBox_2.addItem("")
        self.solverComboBox_2.addItem("")
        self.solverComboBox_2.addItem("")
        self.solverComboBox_2.addItem("")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.solverComboBox_2)
        self.toleranceLabel_2 = QtWidgets.QLabel(self.formGroupBox)
        self.toleranceLabel_2.setObjectName("toleranceLabel_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.toleranceLabel_2)
        self.toleranceDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.formGroupBox)
        self.toleranceDoubleSpinBox_2.setObjectName("toleranceDoubleSpinBox_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.toleranceDoubleSpinBox_2)
        self.randomStateLabel_2 = QtWidgets.QLabel(self.formGroupBox)
        self.randomStateLabel_2.setObjectName("randomStateLabel_2")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.randomStateLabel_2)
        self.randomStateLineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox)
        self.randomStateLineEdit_2.setObjectName("randomStateLineEdit_2")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.randomStateLineEdit_2)
        self.verticalLayout.addWidget(self.formGroupBox)
        self.formGroupBox_CV = QtWidgets.QGroupBox(self.groupbox)
        self.formGroupBox_CV.setObjectName("formGroupBox_CV")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formGroupBox_CV)
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName("formLayout_6")
        self.alphasLabel_2 = QtWidgets.QLabel(self.formGroupBox_CV)
        self.alphasLabel_2.setObjectName("alphasLabel_2")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.alphasLabel_2)
        self.alphasLineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox_CV)
        self.alphasLineEdit_2.setObjectName("alphasLineEdit_2")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.alphasLineEdit_2)
        self.fitInterceptLabel_3 = QtWidgets.QLabel(self.formGroupBox_CV)
        self.fitInterceptLabel_3.setObjectName("fitInterceptLabel_3")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fitInterceptLabel_3)
        self.fitInterceptCheckBox_3 = QtWidgets.QCheckBox(self.formGroupBox_CV)
        self.fitInterceptCheckBox_3.setChecked(True)
        self.fitInterceptCheckBox_3.setObjectName("fitInterceptCheckBox_3")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fitInterceptCheckBox_3)
        self.normalizeLabel_3 = QtWidgets.QLabel(self.formGroupBox_CV)
        self.normalizeLabel_3.setObjectName("normalizeLabel_3")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.normalizeLabel_3)
        self.normalizeCheckBox_3 = QtWidgets.QCheckBox(self.formGroupBox_CV)
        self.normalizeCheckBox_3.setObjectName("normalizeCheckBox_3")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.normalizeCheckBox_3)
        self.scoringLabel_2 = QtWidgets.QLabel(self.formGroupBox_CV)
        self.scoringLabel_2.setObjectName("scoringLabel_2")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.scoringLabel_2)
        self.scoringComboBox_2 = QtWidgets.QComboBox(self.formGroupBox_CV)
        self.scoringComboBox_2.setObjectName("scoringComboBox_2")
        self.scoringComboBox_2.addItem("")
        self.scoringComboBox_2.addItem("")
        self.scoringComboBox_2.addItem("")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.scoringComboBox_2)
        self.cvLabel_2 = QtWidgets.QLabel(self.formGroupBox_CV)
        self.cvLabel_2.setObjectName("cvLabel_2")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.cvLabel_2)
        self.cvLineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox_CV)
        self.cvLineEdit_2.setObjectName("cvLineEdit_2")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cvLineEdit_2)
        self.gCVModeLabel_2 = QtWidgets.QLabel(self.formGroupBox_CV)
        self.gCVModeLabel_2.setObjectName("gCVModeLabel_2")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.gCVModeLabel_2)
        self.gCVModeComboBox_2 = QtWidgets.QComboBox(self.formGroupBox_CV)
        self.gCVModeComboBox_2.setObjectName("gCVModeComboBox_2")
        self.gCVModeComboBox_2.addItem("")
        self.gCVModeComboBox_2.addItem("")
        self.gCVModeComboBox_2.addItem("")
        self.gCVModeComboBox_2.addItem("")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.gCVModeComboBox_2)
        self.storeCVValuesLabel_2 = QtWidgets.QLabel(self.formGroupBox_CV)
        self.storeCVValuesLabel_2.setObjectName("storeCVValuesLabel_2")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.storeCVValuesLabel_2)
        self.storeCVValuesCheckBox_2 = QtWidgets.QCheckBox(self.formGroupBox_CV)
        self.storeCVValuesCheckBox_2.setObjectName("storeCVValuesCheckBox_2")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.storeCVValuesCheckBox_2)
        self.verticalLayout.addWidget(self.formGroupBox_CV)
        self.formGroupBox_2 = QtWidgets.QGroupBox(self.groupbox)
        self.formGroupBox_2.setObjectName("formGroupBox_2")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formGroupBox_2)
        self.formLayout_5.setObjectName("formLayout_5")
        self.crossValidateLabel_2 = QtWidgets.QLabel(self.formGroupBox_2)
        self.crossValidateLabel_2.setObjectName("crossValidateLabel_2")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.crossValidateLabel_2)
        self.crossValidateCheckBox_2 = QtWidgets.QCheckBox(self.formGroupBox_2)
        self.crossValidateCheckBox_2.setChecked(True)
        self.crossValidateCheckBox_2.setObjectName("crossValidateCheckBox_2")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.crossValidateCheckBox_2)
        self.verticalLayout.addWidget(self.formGroupBox_2)
        self.vboxlayout.addWidget(self.groupbox)

        self.retranslateUi(Form)
        self.crossValidateCheckBox_2.toggled['bool'].connect(self.formGroupBox_CV.setEnabled)
        self.crossValidateCheckBox_2.toggled['bool'].connect(self.formGroupBox.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_("Form"))
        self.alphaLabel_2.setText(_("Alpha"))
        self.copyXLabel_2.setText(_("Copy X"))
        self.fitInterceptLabel_4.setText(_("Fit Intercept"))
        self.maxNumOfIterationsLabel_2.setText(_("Max num of Iterations"))
        self.maxNumOfIterationslineEdit_2.setText(_("None"))
        self.normalizeLabel_4.setText(_("Normalize"))
        self.solverLabel_2.setText(_("Solver"))
        self.solverComboBox_2.setItemText(0, _("auto"))
        self.solverComboBox_2.setItemText(1, _("svd"))
        self.solverComboBox_2.setItemText(2, _("cholesky"))
        self.solverComboBox_2.setItemText(3, _("lsqr"))
        self.solverComboBox_2.setItemText(4, _("sparse_cg"))
        self.solverComboBox_2.setItemText(5, _("sag"))
        self.toleranceLabel_2.setText(_("Tolerance"))
        self.randomStateLabel_2.setText(_("Random State"))
        self.randomStateLineEdit_2.setText(_("None"))
        self.alphasLabel_2.setText(_("alphas"))
        self.alphasLineEdit_2.setText(_("0.1, 1.0, 10.0"))
        self.fitInterceptLabel_3.setText(_("Fit intercept "))
        self.normalizeLabel_3.setText(_("Normalize "))
        self.scoringLabel_2.setText(_("Scoring"))
        self.scoringComboBox_2.setItemText(0, _("None"))
        self.scoringComboBox_2.setItemText(1, _("string"))
        self.scoringComboBox_2.setItemText(2, _("callable"))
        self.cvLabel_2.setText(_("CV"))
        self.cvLineEdit_2.setText(_("None"))
        self.gCVModeLabel_2.setText(_("GCV mode"))
        self.gCVModeComboBox_2.setItemText(0, _("None"))
        self.gCVModeComboBox_2.setItemText(1, _("auto"))
        self.gCVModeComboBox_2.setItemText(2, _("svd"))
        self.gCVModeComboBox_2.setItemText(3, _("eigen"))
        self.storeCVValuesLabel_2.setText(_("Store CV Values           "))
        self.crossValidateLabel_2.setText(_("Cross Validate              "))

