from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)
    
def submodel(pysat_fun, verticalLayout_8):
    submodel = QtGui.QGroupBox()
    font = QtGui.QFont()
    font.setPointSize(10)
    submodel.setFont(font)
    submodel.setObjectName(_fromUtf8("submodel"))
    verticalLayout = QtGui.QVBoxLayout(submodel)
    verticalLayout.setMargin(11)
    verticalLayout.setSpacing(6)
    verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
    submodel_vlayout = QtGui.QVBoxLayout()
    submodel_vlayout.setMargin(11)
    submodel_vlayout.setSpacing(6)
    submodel_vlayout.setObjectName(_fromUtf8("submodel_vlayout"))
    submodel_choosedata_hlayout = QtGui.QHBoxLayout()
    submodel_choosedata_hlayout.setMargin(11)
    submodel_choosedata_hlayout.setSpacing(6)
    submodel_choosedata_hlayout.setObjectName(_fromUtf8("submodel_choosedata_hlayout"))
    submodel_choosedata = QtGui.QComboBox(submodel)
    submodel_choosedata.setIconSize(QtCore.QSize(50, 20))
    submodel_choosedata.setObjectName(_fromUtf8("submodel_choosedata"))
    submodel_choosedata_hlayout.addWidget(submodel_choosedata)
    spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    submodel_choosedata_hlayout.addItem(spacerItem)
    submodel_vlayout.addLayout(submodel_choosedata_hlayout)
    horizontalLayout = QtGui.QHBoxLayout()
    horizontalLayout.setMargin(11)
    horizontalLayout.setSpacing(6)
    horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
    label = QtGui.QLabel(submodel)
    label.setObjectName(_fromUtf8("label"))
    horizontalLayout.addWidget(label)
    lineEdit = QtGui.QLineEdit(submodel)
    lineEdit.setObjectName(_fromUtf8("lineEdit"))
    horizontalLayout.addWidget(lineEdit)
    label_2 = QtGui.QLabel(submodel)
    label_2.setObjectName(_fromUtf8("label_2"))
    horizontalLayout.addWidget(label_2)
    lineEdit_2 = QtGui.QLineEdit(submodel)
    lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
    horizontalLayout.addWidget(lineEdit_2)
    spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    horizontalLayout.addItem(spacerItem1)
    submodel_vlayout.addLayout(horizontalLayout)
    submodel_choosealg_hlayout = QtGui.QHBoxLayout()
    submodel_choosealg_hlayout.setMargin(11)
    submodel_choosealg_hlayout.setSpacing(6)
    submodel_choosealg_hlayout.setObjectName(_fromUtf8("submodel_choosealg_hlayout"))
    submodel_choosealg = QtGui.QComboBox(submodel)
    submodel_choosealg.setIconSize(QtCore.QSize(50, 20))
    submodel_choosealg.setObjectName(_fromUtf8("submodel_choosealg"))
    submodel_choosealg_hlayout.addWidget(submodel_choosealg)
    spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    submodel_choosealg_hlayout.addItem(spacerItem2)
    submodel_vlayout.addLayout(submodel_choosealg_hlayout)
    regression_ransac_checkbox = QtGui.QCheckBox(submodel)
    regression_ransac_checkbox.setObjectName(_fromUtf8("regression_ransac_checkbox"))
    submodel_vlayout.addWidget(regression_ransac_checkbox)
    submodel_trainbutton_hlayout = QtGui.QHBoxLayout()
    submodel_trainbutton_hlayout.setMargin(11)
    submodel_trainbutton_hlayout.setSpacing(6)
    submodel_trainbutton_hlayout.setObjectName(_fromUtf8("submodel_trainbutton_hlayout"))
    spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    submodel_trainbutton_hlayout.addItem(spacerItem3)
    submodel_trainbutton = QtGui.QPushButton(submodel)
    submodel_trainbutton.setObjectName(_fromUtf8("submodel_trainbutton"))
    submodel_trainbutton_hlayout.addWidget(submodel_trainbutton)
    submodel_vlayout.addLayout(submodel_trainbutton_hlayout)
    verticalLayout.addLayout(submodel_vlayout)
    verticalLayout_8.addWidget(submodel)

    submodel.setTitle(_translate("MainWindow", "Submodel Ranges", None))
    submodel_choosedata.setItemText(0, _translate("MainWindow", "Choose Data", None))
    submodel_choosedata.setItemText(1, _translate("MainWindow", "Known Data", None))
    label.setText(_translate("MainWindow", "Min", None))
    label_2.setText(_translate("MainWindow", "Max", None))
    submodel_choosealg.setItemText(0, _translate("MainWindow", "Choose Algorithm", None))
    submodel_choosealg.setItemText(1, _translate("MainWindow", "PLS", None))
    submodel_choosealg.setItemText(2, _translate("MainWindow", "GP", None))
    submodel_choosealg.setItemText(3, _translate("MainWindow", "Others coming soon...", None))
    regression_ransac_checkbox.setText(_translate("MainWindow", "RANSAC", None))
    submodel_trainbutton.setText(_translate("MainWindow", "Train Submodels", None))
