from point_spectra_gui.future_.ui import UI_ARD
from point_spectra_gui.future_.ui import UI_BaselineRemoval
from point_spectra_gui.future_.ui import UI_BayesianRidge
from point_spectra_gui.future_.ui import UI_CrossValidation
from point_spectra_gui.future_.ui import UI_DimenstionalityReduction
from point_spectra_gui.future_.ui import UI_ElasticNet
from point_spectra_gui.future_.ui import UI_GP
from point_spectra_gui.future_.ui import UI_interpolation
from point_spectra_gui.future_.ui import UI_KRR
from point_spectra_gui.future_.ui import UI_LARS
from point_spectra_gui.future_.ui import UI_Lasso
from point_spectra_gui.future_.ui import UI_LassoLARS
from point_spectra_gui.future_.ui import UI_LoadData
from point_spectra_gui.future_.ui import MainWindow
from point_spectra_gui.future_.ui import UI_MaskData
from point_spectra_gui.future_.ui import UI_MultiplyByVector
from point_spectra_gui.future_.ui import UI_Normalization
from point_spectra_gui.future_.ui import UI_OLS
from point_spectra_gui.future_.ui import UI_OMP
from point_spectra_gui.future_.ui import UI_OutputFolder
from point_spectra_gui.future_.ui import UI_PeakAreas
from point_spectra_gui.future_.ui import UI_Plot
from point_spectra_gui.future_.ui import UI_Plot_ICA_PCA
from point_spectra_gui.future_.ui import UI_PlotSpectra
from point_spectra_gui.future_.ui import UI_PLS
from point_spectra_gui.future_.ui import UI_ReadChemCamData
from point_spectra_gui.future_.ui import UI_RegressionPredict
from point_spectra_gui.future_.ui import UI_RegressionTrain
from point_spectra_gui.future_.ui import UI_RemoveRows
from point_spectra_gui.future_.ui import UI_Ridge
from point_spectra_gui.future_.ui import UI_SplitDataset
from point_spectra_gui.future_.ui import UI_StratifiedFolds
from point_spectra_gui.future_.ui import UI_SubmodelPredict
from point_spectra_gui.future_.ui import UI_SVR