# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nicholas\Documents\GitHub\PYSAT\src\New PYSAT_Gui\mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import sys

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class pysat_ui(object):
    def compranges(self, MainWindow):
        self.CompRanges = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CompRanges.setFont(font)
        self.CompRanges.setObjectName(_fromUtf8("CompRanges"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.CompRanges)
        self.verticalLayout_7.setMargin(11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_80 = QtGui.QLabel(self.CompRanges)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.horizontalLayout_3.addWidget(self.label_80)
        self.comp_range = QtGui.QSpinBox(self.CompRanges)
        self.comp_range.setMinimum(-100)
        self.comp_range.setMaximum(1000)
        self.comp_range.setObjectName(_fromUtf8("comp_range"))
        self.horizontalLayout_3.addWidget(self.comp_range)
        self.comp_range_2 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_2.setMaximum(1000)
        self.comp_range_2.setObjectName(_fromUtf8("comp_range_2"))
        self.horizontalLayout_3.addWidget(self.comp_range_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setMargin(11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_81 = QtGui.QLabel(self.CompRanges)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.horizontalLayout_5.addWidget(self.label_81)
        self.comp_range_3 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_3.setMaximum(1000)
        self.comp_range_3.setObjectName(_fromUtf8("comp_range_3"))
        self.horizontalLayout_5.addWidget(self.comp_range_3)
        self.comp_range_4 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_4.setMaximum(1000)
        self.comp_range_4.setObjectName(_fromUtf8("comp_range_4"))
        self.horizontalLayout_5.addWidget(self.comp_range_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setMargin(11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_82 = QtGui.QLabel(self.CompRanges)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.horizontalLayout_7.addWidget(self.label_82)
        self.comp_range_5 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_5.setMaximum(1000)
        self.comp_range_5.setObjectName(_fromUtf8("comp_range_5"))
        self.horizontalLayout_7.addWidget(self.comp_range_5)
        self.comp_range_6 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_6.setMaximum(1000)
        self.comp_range_6.setObjectName(_fromUtf8("comp_range_6"))
        self.horizontalLayout_7.addWidget(self.comp_range_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setMargin(11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_85 = QtGui.QLabel(self.CompRanges)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.horizontalLayout_10.addWidget(self.label_85)
        self.comp_range_7 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_7.setMaximum(1000)
        self.comp_range_7.setObjectName(_fromUtf8("comp_range_7"))
        self.horizontalLayout_10.addWidget(self.comp_range_7)
        self.comp_range_8 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_8.setMaximum(1000)
        self.comp_range_8.setObjectName(_fromUtf8("comp_range_8"))
        self.horizontalLayout_10.addWidget(self.comp_range_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setMargin(11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_40 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_9.addWidget(self.label_40)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setMargin(11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_20 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_6.addWidget(self.label_20)
        self.label_21 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_6.addWidget(self.label_21)
        self.label_22 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_6.addWidget(self.label_22)
        self.label_23 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_6.addWidget(self.label_23)
        self.label_24 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_6.addWidget(self.label_24)
        self.label_27 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_6.addWidget(self.label_27)
        self.label_29 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_6.addWidget(self.label_29)
        self.label_28 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_6.addWidget(self.label_28)
        self.label_26 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_6.addWidget(self.label_26)
        self.label_25 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_6.addWidget(self.label_25)
        self.label_32 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_6.addWidget(self.label_32)
        self.label_30 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_6.addWidget(self.label_30)
        self.label_33 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_6.addWidget(self.label_33)
        self.label_34 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_6.addWidget(self.label_34)
        self.label_31 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_6.addWidget(self.label_31)
        self.label_39 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_6.addWidget(self.label_39)
        self.label_36 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_6.addWidget(self.label_36)
        self.label_37 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_6.addWidget(self.label_37)
        self.label_35 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_6.addWidget(self.label_35)
        self.label_38 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_6.addWidget(self.label_38)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayout_8.addWidget(self.CompRanges)

        self.CompRanges.setTitle(_translate("MainWindow", "Composition Ranges", None))
        self.label_80.setText(_translate("MainWindow", "Value 1", None))
        self.label_81.setText(_translate("MainWindow", "Value 2", None))
        self.label_82.setText(_translate("MainWindow", "Value 3", None))
        self.label_85.setText(_translate("MainWindow", "Full Model Value", None))
        self.label_40.setText(_translate("MainWindow", "compranges", None))
        self.label_20.setText(_translate("MainWindow", "[", None))
        self.label_21.setText(_translate("MainWindow", "0", None))
        self.label_22.setText(_translate("MainWindow", ",", None))
        self.label_23.setText(_translate("MainWindow", "0", None))
        self.label_24.setText(_translate("MainWindow", "]", None))
        self.label_27.setText(_translate("MainWindow", "[", None))
        self.label_29.setText(_translate("MainWindow", "0", None))
        self.label_28.setText(_translate("MainWindow", ",", None))
        self.label_26.setText(_translate("MainWindow", "0", None))
        self.label_25.setText(_translate("MainWindow", "]", None))
        self.label_32.setText(_translate("MainWindow", "[", None))
        self.label_30.setText(_translate("MainWindow", "0", None))
        self.label_33.setText(_translate("MainWindow", ",", None))
        self.label_34.setText(_translate("MainWindow", "0", None))
        self.label_31.setText(_translate("MainWindow", "]", None))
        self.label_39.setText(_translate("MainWindow", "[", None))
        self.label_36.setText(_translate("MainWindow", "0", None))
        self.label_37.setText(_translate("MainWindow", ",", None))
        self.label_35.setText(_translate("MainWindow", "0", None))
        self.label_38.setText(_translate("MainWindow", "]", None))

        QtCore.QObject.connect(self.comp_range, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_21.setNum)
        QtCore.QObject.connect(self.comp_range_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_23.setNum)
        QtCore.QObject.connect(self.comp_range_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_29.setNum)
        QtCore.QObject.connect(self.comp_range_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_26.setNum)
        QtCore.QObject.connect(self.comp_range_5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_30.setNum)
        QtCore.QObject.connect(self.comp_range_6, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_34.setNum)
        QtCore.QObject.connect(self.comp_range_7, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_36.setNum)
        QtCore.QObject.connect(self.comp_range_8, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_35.setNum)
