from PyQt4 import QtCore, QtGui
from PyQt4.QtGui import QFileDialog
import sys


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)




class pysat_ui(object):
    count = 1

    def __init__(self):
        self.norm_spinBox_ = [None]*1024
        pysat_ui.count = 0

    def mainframe(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(581, 843)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_9.setMargin(11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.scrollArea = QtGui.QScrollArea(self.centralWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 561, 770))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.scrollAreaWidgetContents_2.setFont(font)
        self.scrollAreaWidgetContents_2.setStyleSheet(_fromUtf8("QGroupBox {\n"
                                                                "  border: 2px solid gray;\n"
                                                                "  border-radius: 6px;\n"
                                                                "  margin-top: 0.5em;\n"
                                                                "}\n"
                                                                "\n"
                                                                "QGroupBox::title {\n"
                                                                "\n"
                                                                "  padding-top: -14px;\n"
                                                                "  padding-left: 8px;\n"
                                                                "}\n"
                                                                ""))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.setMargin(11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 581, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPreprocessing = QtGui.QMenu(self.menuBar)
        self.menuPreprocessing.setObjectName(_fromUtf8("menuPreprocessing"))
        self.menuBaseline_Removal = QtGui.QMenu(self.menuPreprocessing)
        self.menuBaseline_Removal.setObjectName(_fromUtf8("menuBaseline_Removal"))
        self.menuCalibration_Transfer = QtGui.QMenu(self.menuPreprocessing)
        self.menuCalibration_Transfer.setObjectName(_fromUtf8("menuCalibration_Transfer"))
        self.menuVisualization = QtGui.QMenu(self.menuBar)
        self.menuVisualization.setObjectName(_fromUtf8("menuVisualization"))
        self.menuClustering = QtGui.QMenu(self.menuVisualization)
        self.menuClustering.setObjectName(_fromUtf8("menuClustering"))
        self.menuRegression = QtGui.QMenu(self.menuBar)
        self.menuRegression.setObjectName(_fromUtf8("menuRegression"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionLoad_Refence_Data = QtGui.QAction(MainWindow)
        self.actionLoad_Refence_Data.setObjectName(_fromUtf8("actionLoad_Refence_Data"))
        self.actionLoad_Unknown_Data = QtGui.QAction(MainWindow)
        self.actionLoad_Unknown_Data.setObjectName(_fromUtf8("actionLoad_Unknown_Data"))
        self.actionSave_Current_Workflow = QtGui.QAction(MainWindow)
        self.actionSave_Current_Workflow.setObjectName(_fromUtf8("actionSave_Current_Workflow"))
        self.actionSave_Current_Plots = QtGui.QAction(MainWindow)
        self.actionSave_Current_Plots.setObjectName(_fromUtf8("actionSave_Current_Plots"))
        self.actionSave_Current_Data = QtGui.QAction(MainWindow)
        self.actionSave_Current_Data.setObjectName(_fromUtf8("actionSave_Current_Data"))
        self.actionCreate_New_Workflow = QtGui.QAction(MainWindow)
        self.actionCreate_New_Workflow.setObjectName(_fromUtf8("actionCreate_New_Workflow"))
        self.actionNoise_Reduction = QtGui.QAction(MainWindow)
        self.actionNoise_Reduction.setObjectName(_fromUtf8("actionNoise_Reduction"))
        self.actionApply_Mask = QtGui.QAction(MainWindow)
        self.actionApply_Mask.setObjectName(_fromUtf8("actionApply_Mask"))
        self.actionInterpolate = QtGui.QAction(MainWindow)
        self.actionInterpolate.setObjectName(_fromUtf8("actionInterpolate"))
        self.actionInstrument_Response = QtGui.QAction(MainWindow)
        self.actionInstrument_Response.setObjectName(_fromUtf8("actionInstrument_Response"))
        self.actionALS = QtGui.QAction(MainWindow)
        self.actionALS.setObjectName(_fromUtf8("actionALS"))
        self.actionDietrich = QtGui.QAction(MainWindow)
        self.actionDietrich.setObjectName(_fromUtf8("actionDietrich"))
        self.actionPolyFit = QtGui.QAction(MainWindow)
        self.actionPolyFit.setObjectName(_fromUtf8("actionPolyFit"))
        self.actionAirPLS = QtGui.QAction(MainWindow)
        self.actionAirPLS.setObjectName(_fromUtf8("actionAirPLS"))
        self.actionFABC = QtGui.QAction(MainWindow)
        self.actionFABC.setObjectName(_fromUtf8("actionFABC"))
        self.actionKK = QtGui.QAction(MainWindow)
        self.actionKK.setObjectName(_fromUtf8("actionKK"))
        self.actionMario = QtGui.QAction(MainWindow)
        self.actionMario.setObjectName(_fromUtf8("actionMario"))
        self.actionMedian = QtGui.QAction(MainWindow)
        self.actionMedian.setObjectName(_fromUtf8("actionMedian"))
        self.actionRubberband = QtGui.QAction(MainWindow)
        self.actionRubberband.setObjectName(_fromUtf8("actionRubberband"))
        self.actionUndecimated_Wavelet = QtGui.QAction(MainWindow)
        self.actionUndecimated_Wavelet.setObjectName(_fromUtf8("actionUndecimated_Wavelet"))
        self.actionRatio = QtGui.QAction(MainWindow)
        self.actionRatio.setObjectName(_fromUtf8("actionRatio"))
        self.actionTommy_s_Methgod = QtGui.QAction(MainWindow)
        self.actionTommy_s_Methgod.setObjectName(_fromUtf8("actionTommy_s_Methgod"))
        self.actionPiecewise_Direct_Standardization = QtGui.QAction(MainWindow)
        self.actionPiecewise_Direct_Standardization.setObjectName(_fromUtf8("actionPiecewise_Direct_Standardization"))
        self.actionPCA = QtGui.QAction(MainWindow)
        self.actionPCA.setObjectName(_fromUtf8("actionPCA"))
        self.actionICA = QtGui.QAction(MainWindow)
        self.actionICA.setObjectName(_fromUtf8("actionICA"))
        self.actionK_Means = QtGui.QAction(MainWindow)
        self.actionK_Means.setObjectName(_fromUtf8("actionK_Means"))
        self.actionHierarchical = QtGui.QAction(MainWindow)
        self.actionHierarchical.setObjectName(_fromUtf8("actionHierarchical"))
        self.actionOthers = QtGui.QAction(MainWindow)
        self.actionOthers.setObjectName(_fromUtf8("actionOthers"))
        self.actionOthers_2 = QtGui.QAction(MainWindow)
        self.actionOthers_2.setObjectName(_fromUtf8("actionOthers_2"))
        self.actionOthers_3 = QtGui.QAction(MainWindow)
        self.actionOthers_3.setObjectName(_fromUtf8("actionOthers_3"))
        self.actionPLS = QtGui.QAction(MainWindow)
        self.actionPLS.setObjectName(_fromUtf8("actionPLS"))
        self.actionSM_PLS = QtGui.QAction(MainWindow)
        self.actionSM_PLS.setObjectName(_fromUtf8("actionSM_PLS"))
        self.actionICA_Regression = QtGui.QAction(MainWindow)
        self.actionICA_Regression.setObjectName(_fromUtf8("actionICA_Regression"))
        self.actionGaussian_Process = QtGui.QAction(MainWindow)
        self.actionGaussian_Process.setObjectName(_fromUtf8("actionGaussian_Process"))
        self.actionMLP = QtGui.QAction(MainWindow)
        self.actionMLP.setObjectName(_fromUtf8("actionMLP"))
        self.actionSVM = QtGui.QAction(MainWindow)
        self.actionSVM.setObjectName(_fromUtf8("actionSVM"))
        self.actionOthers_4 = QtGui.QAction(MainWindow)
        self.actionOthers_4.setObjectName(_fromUtf8("actionOthers_4"))
        self.actionOthers_5 = QtGui.QAction(MainWindow)
        self.actionOthers_5.setObjectName(_fromUtf8("actionOthers_5"))
        self.actionIndex = QtGui.QAction(MainWindow)
        self.actionIndex.setObjectName(_fromUtf8("actionIndex"))
        self.actionContent_2 = QtGui.QAction(MainWindow)
        self.actionContent_2.setObjectName(_fromUtf8("actionContent_2"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAbout_QtCreator = QtGui.QAction(MainWindow)
        self.actionAbout_QtCreator.setObjectName(_fromUtf8("actionAbout_QtCreator"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionNormalization = QtGui.QAction(MainWindow)
        self.actionNormalization.setObjectName(_fromUtf8("actionNormalization"))
        self.actionElement_Name_Setup = QtGui.QAction(MainWindow)
        self.actionElement_Name_Setup.setObjectName(_fromUtf8("actionElement_Name_Setup"))
        self.actionComposition_Ranges = QtGui.QAction(MainWindow)
        self.actionComposition_Ranges.setObjectName(_fromUtf8("actionComposition_Ranges"))
        self.actionCreate_Models = QtGui.QAction(MainWindow)
        self.actionCreate_Models.setObjectName(_fromUtf8("actionCreate_Models"))
        self.menuFile.addAction(self.actionLoad_Unknown_Data)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Current_Plots)
        self.menuFile.addAction(self.actionSave_Current_Data)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionCreate_New_Workflow)
        self.menuFile.addAction(self.actionSave_Current_Workflow)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuBaseline_Removal.addAction(self.actionALS)
        self.menuBaseline_Removal.addAction(self.actionDietrich)
        self.menuBaseline_Removal.addAction(self.actionPolyFit)
        self.menuBaseline_Removal.addAction(self.actionAirPLS)
        self.menuBaseline_Removal.addAction(self.actionFABC)
        self.menuBaseline_Removal.addAction(self.actionKK)
        self.menuBaseline_Removal.addAction(self.actionMario)
        self.menuBaseline_Removal.addAction(self.actionMedian)
        self.menuBaseline_Removal.addAction(self.actionRubberband)
        self.menuBaseline_Removal.addAction(self.actionUndecimated_Wavelet)
        self.menuCalibration_Transfer.addAction(self.actionRatio)
        self.menuCalibration_Transfer.addAction(self.actionTommy_s_Methgod)
        self.menuCalibration_Transfer.addAction(self.actionPiecewise_Direct_Standardization)
        self.menuCalibration_Transfer.addAction(self.actionOthers_3)
        self.menuPreprocessing.addAction(self.actionNormalization)
        self.menuPreprocessing.addAction(self.actionNoise_Reduction)
        self.menuPreprocessing.addAction(self.actionApply_Mask)
        self.menuPreprocessing.addAction(self.actionInterpolate)
        self.menuPreprocessing.addAction(self.actionInstrument_Response)
        self.menuPreprocessing.addAction(self.menuCalibration_Transfer.menuAction())
        self.menuPreprocessing.addAction(self.menuBaseline_Removal.menuAction())
        self.menuPreprocessing.addSeparator()
        self.menuPreprocessing.addAction(self.actionElement_Name_Setup)
        self.menuPreprocessing.addAction(self.actionComposition_Ranges)
        self.menuPreprocessing.addAction(self.actionCreate_Models)
        self.menuClustering.addAction(self.actionK_Means)
        self.menuClustering.addAction(self.actionHierarchical)
        self.menuClustering.addAction(self.actionOthers)
        self.menuClustering.addAction(self.actionOthers_2)
        self.menuVisualization.addAction(self.actionPCA)
        self.menuVisualization.addAction(self.actionICA)
        self.menuVisualization.addAction(self.menuClustering.menuAction())
        self.menuRegression.addAction(self.actionPLS)
        self.menuRegression.addAction(self.actionSM_PLS)
        self.menuRegression.addAction(self.actionICA_Regression)
        self.menuRegression.addAction(self.actionGaussian_Process)
        self.menuRegression.addAction(self.actionMLP)
        self.menuRegression.addAction(self.actionSVM)
        self.menuRegression.addAction(self.actionOthers_4)
        self.menuRegression.addAction(self.actionOthers_5)
        self.menuHelp.addAction(self.actionIndex)
        self.menuHelp.addAction(self.actionContent_2)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_QtCreator)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuPreprocessing.menuAction())
        self.menuBar.addAction(self.menuVisualization.menuAction())
        self.menuBar.addAction(self.menuRegression.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        MainWindow.setWindowTitle(_translate("MainWindow", "PYSAT", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuPreprocessing.setTitle(_translate("MainWindow", "Preprocessing", None))
        self.menuBaseline_Removal.setTitle(_translate("MainWindow", "Baseline Removal", None))
        self.menuCalibration_Transfer.setTitle(_translate("MainWindow", "Calibration Transfer", None))
        self.menuVisualization.setTitle(_translate("MainWindow", "Visualization", None))
        self.menuClustering.setTitle(_translate("MainWindow", "Clustering", None))
        self.menuRegression.setTitle(_translate("MainWindow", "Regression", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionLoad_Refence_Data.setText(_translate("MainWindow", "Load Refence Data", None))
        self.actionLoad_Unknown_Data.setText(_translate("MainWindow", "Load Data Files", None))
        self.actionSave_Current_Workflow.setText(_translate("MainWindow", "Save Current Workflow", None))
        self.actionSave_Current_Plots.setText(_translate("MainWindow", "Save Current Plots", None))
        self.actionSave_Current_Data.setText(_translate("MainWindow", "Save Current Data", None))
        self.actionCreate_New_Workflow.setText(_translate("MainWindow", "Create New Workflow", None))
        self.actionNoise_Reduction.setText(_translate("MainWindow", "Noise Reduction", None))
        self.actionApply_Mask.setText(_translate("MainWindow", "Apply Mask", None))
        self.actionInterpolate.setText(_translate("MainWindow", "Interpolate", None))
        self.actionInstrument_Response.setText(_translate("MainWindow", "Instrument Response", None))
        self.actionALS.setText(_translate("MainWindow", "ALS", None))
        self.actionDietrich.setText(_translate("MainWindow", "Dietrich", None))
        self.actionPolyFit.setText(_translate("MainWindow", "PolyFit", None))
        self.actionAirPLS.setText(_translate("MainWindow", "AirPLS", None))
        self.actionFABC.setText(_translate("MainWindow", "FABC", None))
        self.actionKK.setText(_translate("MainWindow", "KK", None))
        self.actionMario.setText(_translate("MainWindow", "Mario", None))
        self.actionMedian.setText(_translate("MainWindow", "Median", None))
        self.actionRubberband.setText(_translate("MainWindow", "Rubberband", None))
        self.actionUndecimated_Wavelet.setText(_translate("MainWindow", "Undecimated Wavelet", None))
        self.actionRatio.setText(_translate("MainWindow", "Ratio", None))
        self.actionTommy_s_Methgod.setText(_translate("MainWindow", "Tommy\'s Method", None))
        self.actionPiecewise_Direct_Standardization.setText(_translate("MainWindow", "Piecewise Direct Standardization", None))
        self.actionPCA.setText(_translate("MainWindow", "PCA", None))
        self.actionICA.setText(_translate("MainWindow", "ICA", None))
        self.actionK_Means.setText(_translate("MainWindow", "K-Means", None))
        self.actionHierarchical.setText(_translate("MainWindow", "Hierarchical", None))
        self.actionOthers.setText(_translate("MainWindow", "Others...", None))
        self.actionOthers_2.setText(_translate("MainWindow", "Others...", None))
        self.actionOthers_3.setText(_translate("MainWindow", "Others...", None))
        self.actionPLS.setText(_translate("MainWindow", "PLS", None))
        self.actionSM_PLS.setText(_translate("MainWindow", "SM-PLS", None))
        self.actionICA_Regression.setText(_translate("MainWindow", "ICA Regression", None))
        self.actionGaussian_Process.setText(_translate("MainWindow", "Gaussian Process", None))
        self.actionMLP.setText(_translate("MainWindow", "MLP", None))
        self.actionSVM.setText(_translate("MainWindow", "SVM", None))
        self.actionOthers_4.setText(_translate("MainWindow", "Others...", None))
        self.actionOthers_5.setText(_translate("MainWindow", "Others...", None))
        self.actionIndex.setText(_translate("MainWindow", "Index", None))
        self.actionContent_2.setText(_translate("MainWindow", "Content", None))
        self.actionAbout.setText(_translate("MainWindow", "About...", None))
        self.actionAbout_QtCreator.setText(_translate("MainWindow", "About QtCreator...", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionNormalization.setText(_translate("MainWindow", "Normalization", None))
        self.actionElement_Name_Setup.setText(_translate("MainWindow", "Element Name Setup", None))
        self.actionComposition_Ranges.setText(_translate("MainWindow", "Composition Ranges", None))
        self.actionCreate_Models.setText(_translate("MainWindow", "Create Models", None))

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def compranges(self, MainWindow):
        self.CompRanges = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CompRanges.setFont(font)
        self.CompRanges.setObjectName(_fromUtf8("CompRanges"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.CompRanges)
        self.verticalLayout_7.setMargin(11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_80 = QtGui.QLabel(self.CompRanges)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.horizontalLayout_3.addWidget(self.label_80)
        self.comp_range = QtGui.QSpinBox(self.CompRanges)
        self.comp_range.setMinimum(-100)
        self.comp_range.setMaximum(1000)
        self.comp_range.setObjectName(_fromUtf8("comp_range"))
        self.horizontalLayout_3.addWidget(self.comp_range)
        self.comp_range_2 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_2.setMaximum(1000)
        self.comp_range_2.setObjectName(_fromUtf8("comp_range_2"))
        self.horizontalLayout_3.addWidget(self.comp_range_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setMargin(11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_81 = QtGui.QLabel(self.CompRanges)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.horizontalLayout_5.addWidget(self.label_81)
        self.comp_range_3 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_3.setMaximum(1000)
        self.comp_range_3.setObjectName(_fromUtf8("comp_range_3"))
        self.horizontalLayout_5.addWidget(self.comp_range_3)
        self.comp_range_4 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_4.setMaximum(1000)
        self.comp_range_4.setObjectName(_fromUtf8("comp_range_4"))
        self.horizontalLayout_5.addWidget(self.comp_range_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setMargin(11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_82 = QtGui.QLabel(self.CompRanges)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.horizontalLayout_7.addWidget(self.label_82)
        self.comp_range_5 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_5.setMaximum(1000)
        self.comp_range_5.setObjectName(_fromUtf8("comp_range_5"))
        self.horizontalLayout_7.addWidget(self.comp_range_5)
        self.comp_range_6 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_6.setMaximum(1000)
        self.comp_range_6.setObjectName(_fromUtf8("comp_range_6"))
        self.horizontalLayout_7.addWidget(self.comp_range_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setMargin(11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_85 = QtGui.QLabel(self.CompRanges)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.horizontalLayout_10.addWidget(self.label_85)
        self.comp_range_7 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_7.setMaximum(1000)
        self.comp_range_7.setObjectName(_fromUtf8("comp_range_7"))
        self.horizontalLayout_10.addWidget(self.comp_range_7)
        self.comp_range_8 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_8.setMaximum(1000)
        self.comp_range_8.setObjectName(_fromUtf8("comp_range_8"))
        self.horizontalLayout_10.addWidget(self.comp_range_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setMargin(11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_40 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_9.addWidget(self.label_40)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setMargin(11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_20 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_6.addWidget(self.label_20)
        self.label_21 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_6.addWidget(self.label_21)
        self.label_22 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_6.addWidget(self.label_22)
        self.label_23 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_6.addWidget(self.label_23)
        self.label_24 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_6.addWidget(self.label_24)
        self.label_27 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_6.addWidget(self.label_27)
        self.label_29 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_6.addWidget(self.label_29)
        self.label_28 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_6.addWidget(self.label_28)
        self.label_26 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_6.addWidget(self.label_26)
        self.label_25 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_6.addWidget(self.label_25)
        self.label_32 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_6.addWidget(self.label_32)
        self.label_30 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_6.addWidget(self.label_30)
        self.label_33 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_6.addWidget(self.label_33)
        self.label_34 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_6.addWidget(self.label_34)
        self.label_31 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_6.addWidget(self.label_31)
        self.label_39 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_6.addWidget(self.label_39)
        self.label_36 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_6.addWidget(self.label_36)
        self.label_37 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_6.addWidget(self.label_37)
        self.label_35 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_6.addWidget(self.label_35)
        self.label_38 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_6.addWidget(self.label_38)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayout_8.addWidget(self.CompRanges)

        self.CompRanges.setTitle(_translate("MainWindow", "Composition Ranges", None))
        self.label_80.setText(_translate("MainWindow", "Value 1", None))
        self.label_81.setText(_translate("MainWindow", "Value 2", None))
        self.label_82.setText(_translate("MainWindow", "Value 3", None))
        self.label_85.setText(_translate("MainWindow", "Full Model Value", None))
        self.label_40.setText(_translate("MainWindow", "compranges", None))
        self.label_20.setText(_translate("MainWindow", "[", None))
        self.label_21.setText(_translate("MainWindow", "0", None))
        self.label_22.setText(_translate("MainWindow", ",", None))
        self.label_23.setText(_translate("MainWindow", "0", None))
        self.label_24.setText(_translate("MainWindow", "]", None))
        self.label_27.setText(_translate("MainWindow", "[", None))
        self.label_29.setText(_translate("MainWindow", "0", None))
        self.label_28.setText(_translate("MainWindow", ",", None))
        self.label_26.setText(_translate("MainWindow", "0", None))
        self.label_25.setText(_translate("MainWindow", "]", None))
        self.label_32.setText(_translate("MainWindow", "[", None))
        self.label_30.setText(_translate("MainWindow", "0", None))
        self.label_33.setText(_translate("MainWindow", ",", None))
        self.label_34.setText(_translate("MainWindow", "0", None))
        self.label_31.setText(_translate("MainWindow", "]", None))
        self.label_39.setText(_translate("MainWindow", "[", None))
        self.label_36.setText(_translate("MainWindow", "0", None))
        self.label_37.setText(_translate("MainWindow", ",", None))
        self.label_35.setText(_translate("MainWindow", "0", None))
        self.label_38.setText(_translate("MainWindow", "]", None))

        QtCore.QObject.connect(self.comp_range, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_21.setNum)
        QtCore.QObject.connect(self.comp_range_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_23.setNum)
        QtCore.QObject.connect(self.comp_range_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_29.setNum)
        QtCore.QObject.connect(self.comp_range_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_26.setNum)
        QtCore.QObject.connect(self.comp_range_5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_30.setNum)
        QtCore.QObject.connect(self.comp_range_6, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_34.setNum)
        QtCore.QObject.connect(self.comp_range_7, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_36.setNum)
        QtCore.QObject.connect(self.comp_range_8, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_35.setNum)

    def createmodels(self, MainWindow):
        self.CreateModels = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CreateModels.setFont(font)
        self.CreateModels.setObjectName(_fromUtf8("CreateModels"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.CreateModels)
        self.verticalLayout_17.setMargin(11)
        self.verticalLayout_17.setSpacing(6)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setMargin(11)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setMargin(11)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_70 = QtGui.QLabel(self.CreateModels)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.verticalLayout_18.addWidget(self.label_70)
        self.label_71 = QtGui.QLabel(self.CreateModels)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.verticalLayout_18.addWidget(self.label_71)
        self.label_72 = QtGui.QLabel(self.CreateModels)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.verticalLayout_18.addWidget(self.label_72)
        self.label_73 = QtGui.QLabel(self.CreateModels)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.verticalLayout_18.addWidget(self.label_73)
        self.horizontalLayout_14.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setMargin(11)
        self.verticalLayout_19.setSpacing(6)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.create_model_spin = QtGui.QSpinBox(self.CreateModels)
        self.create_model_spin.setMaximum(20)
        self.create_model_spin.setObjectName(_fromUtf8("create_model_spin"))
        self.verticalLayout_19.addWidget(self.create_model_spin)
        self.create_model_spin_2 = QtGui.QSpinBox(self.CreateModels)
        self.create_model_spin_2.setMaximum(20)
        self.create_model_spin_2.setObjectName(_fromUtf8("create_model_spin_2"))
        self.verticalLayout_19.addWidget(self.create_model_spin_2)
        self.create_model_spin_3 = QtGui.QSpinBox(self.CreateModels)
        self.create_model_spin_3.setMaximum(20)
        self.create_model_spin_3.setObjectName(_fromUtf8("create_model_spin_3"))
        self.verticalLayout_19.addWidget(self.create_model_spin_3)
        self.create_model_spin_4 = QtGui.QSpinBox(self.CreateModels)
        self.create_model_spin_4.setMaximum(20)
        self.create_model_spin_4.setObjectName(_fromUtf8("create_model_spin_4"))
        self.verticalLayout_19.addWidget(self.create_model_spin_4)
        self.horizontalLayout_14.addLayout(self.verticalLayout_19)
        self.verticalLayout_17.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setMargin(11)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_74 = QtGui.QLabel(self.CreateModels)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_15.addWidget(self.label_74)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setMargin(11)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_75 = QtGui.QLabel(self.CreateModels)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.horizontalLayout_16.addWidget(self.label_75)
        self.label_76 = QtGui.QLabel(self.CreateModels)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.horizontalLayout_16.addWidget(self.label_76)
        self.label_77 = QtGui.QLabel(self.CreateModels)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.horizontalLayout_16.addWidget(self.label_77)
        self.label_78 = QtGui.QLabel(self.CreateModels)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.horizontalLayout_16.addWidget(self.label_78)
        self.label_79 = QtGui.QLabel(self.CreateModels)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.horizontalLayout_16.addWidget(self.label_79)
        self.label_83 = QtGui.QLabel(self.CreateModels)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.horizontalLayout_16.addWidget(self.label_83)
        self.label_84 = QtGui.QLabel(self.CreateModels)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.horizontalLayout_16.addWidget(self.label_84)
        self.label_88 = QtGui.QLabel(self.CreateModels)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.horizontalLayout_16.addWidget(self.label_88)
        self.label_89 = QtGui.QLabel(self.CreateModels)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.horizontalLayout_16.addWidget(self.label_89)
        self.label_90 = QtGui.QLabel(self.CreateModels)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.horizontalLayout_16.addWidget(self.label_90)
        self.label_91 = QtGui.QLabel(self.CreateModels)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.horizontalLayout_16.addWidget(self.label_91)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.verticalLayout_17.addLayout(self.horizontalLayout_15)
        self.verticalLayout_8.addWidget(self.CreateModels)
        self.CreateModels.setTitle(_translate("MainWindow", "Create Models", None))
        self.label_70.setText(_translate("MainWindow", "Value 1", None))
        self.label_71.setText(_translate("MainWindow", "Value 2", None))
        self.label_72.setText(_translate("MainWindow", "Value 3", None))
        self.label_73.setText(_translate("MainWindow", "Value 4", None))
        self.label_74.setText(_translate("MainWindow", "ncs", None))
        self.label_75.setText(_translate("MainWindow", "[", None))
        self.label_76.setText(_translate("MainWindow", "(", None))
        self.label_77.setText(_translate("MainWindow", "0", None))
        self.label_78.setText(_translate("MainWindow", ",", None))
        self.label_79.setText(_translate("MainWindow", "0", None))
        self.label_83.setText(_translate("MainWindow", ",", None))
        self.label_84.setText(_translate("MainWindow", "0", None))
        self.label_88.setText(_translate("MainWindow", ",", None))
        self.label_89.setText(_translate("MainWindow", "0", None))
        self.label_90.setText(_translate("MainWindow", ")", None))
        self.label_91.setText(_translate("MainWindow", "]", None))
        QtCore.QObject.connect(self.create_model_spin_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_79.setNum)
        QtCore.QObject.connect(self.create_model_spin, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_77.setNum)
        QtCore.QObject.connect(self.create_model_spin_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_84.setNum)
        QtCore.QObject.connect(self.create_model_spin_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_89.setNum)

    def files(self, MainWindow):
        self.Files = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Files.setFont(font)
        self.Files.setObjectName(_fromUtf8("Files"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.Files)
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_3 = QtGui.QLabel(self.Files)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtGui.QLabel(self.Files)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.Files)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtGui.QLabel(self.Files)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lineEdit = QtGui.QLineEdit(self.Files)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtGui.QLineEdit(self.Files)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtGui.QLineEdit(self.Files)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtGui.QLineEdit(self.Files)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.maskFileButton = QtGui.QToolButton(self.Files)
        self.maskFileButton.setObjectName(_fromUtf8("maskFileButton"))
        self.verticalLayout_3.addWidget(self.maskFileButton)
        self.unknownDataButton = QtGui.QToolButton(self.Files)
        self.unknownDataButton.setObjectName(_fromUtf8("unknownDataButton"))
        self.verticalLayout_3.addWidget(self.unknownDataButton)
        self.fullDataBaseButton = QtGui.QToolButton(self.Files)
        self.fullDataBaseButton.setObjectName(_fromUtf8("fullDataBaseButton"))
        self.verticalLayout_3.addWidget(self.fullDataBaseButton)
        self.outPutLocationButton = QtGui.QToolButton(self.Files)
        self.outPutLocationButton.setObjectName(_fromUtf8("outPutLocationButton"))
        self.verticalLayout_3.addWidget(self.outPutLocationButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addWidget(self.Files)
        self.Files.setTitle(_translate("MainWindow", "Files", None))
        self.label_3.setText(_translate("MainWindow", "Maskfile", None))
        self.label.setText(_translate("MainWindow", "Unknown Data", None))
        self.label_2.setText(_translate("MainWindow", "Full Database", None))
        self.label_4.setText(_translate("MainWindow", "Output Location", None))
        self.lineEdit.setText(_translate("MainWindow", "*.csv", None))
        self.lineEdit_2.setText(_translate("MainWindow", "*.csv", None))
        self.lineEdit_3.setText(_translate("MainWindow", "*.csv", None))
        self.lineEdit_4.setText(_translate("MainWindow", "*/*", None))
        self.maskFileButton.setText(_translate("MainWindow", "...", None))
        self.unknownDataButton.setText(_translate("MainWindow", "...", None))
        self.fullDataBaseButton.setText(_translate("MainWindow", "...", None))
        self.outPutLocationButton.setText(_translate("MainWindow", "...", None))
        try: #this try allows for
            self.maskFileButton.clicked.connect(lambda: pysat_ui.on_maskFile_clicked(self))
            self.unknownDataButton.clicked.connect(lambda: pysat_ui.on_uknownDataButton_clicked(self))
            self.fullDataBaseButton.clicked.connect(lambda: pysat_ui.on_fullDataBaseButton_clicked(self))
            self.outPutLocationButton.clicked.connect(lambda: pysat_ui.on_outPutLocationButton_clicked(self))
            self.okButton.clicked.connect(lambda: pysat_ui.on_okButton_clicked(self))
        except:
            pass

    def ok(self, MainWindow):
        self.OK = QtGui.QGroupBox(self.centralWidget)
        self.OK.setObjectName(_fromUtf8("OK"))
        self.ok = QtGui.QHBoxLayout(self.OK)
        self.ok.setMargin(11)
        self.ok.setSpacing(6)
        self.ok.setObjectName(_fromUtf8("ok"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ok.addItem(spacerItem)
        self.okButton = QtGui.QPushButton(self.OK)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.okButton.setFont(font)
        self.okButton.setMouseTracking(False)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.ok.addWidget(self.okButton)
        self.verticalLayout_9.addWidget(self.OK)
        self.okButton.setText(_translate("MainWindow", "OK", None))

    def element_name_setup(self, MainWindow):
        self.CrossValidation = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CrossValidation.setFont(font)
        self.CrossValidation.setObjectName(_fromUtf8("CrossValidation"))
        self.CrossValid = QtGui.QVBoxLayout(self.CrossValidation)
        self.CrossValid.setMargin(11)
        self.CrossValid.setSpacing(6)
        self.CrossValid.setObjectName(_fromUtf8("CrossValid"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setMargin(11)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_14 = QtGui.QLabel(self.CrossValidation)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_11.addWidget(self.label_14)
        self.label_15 = QtGui.QLabel(self.CrossValidation)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_11.addWidget(self.label_15)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setMargin(11)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.elementNameLine = QtGui.QLineEdit(self.CrossValidation)
        self.elementNameLine.setObjectName(_fromUtf8("elementNameLine"))
        self.verticalLayout_12.addWidget(self.elementNameLine)
        self.nfolds_test = QtGui.QSpinBox(self.CrossValidation)
        self.nfolds_test.setObjectName(_fromUtf8("nfolds_test"))
        self.verticalLayout_12.addWidget(self.nfolds_test)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.CrossValid.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8.addWidget(self.CrossValidation)
        self.CrossValidation.setTitle(_translate("MainWindow", "Setup", None))
        self.label_14.setText(_translate("MainWindow", "Element Name", None))
        self.label_15.setText(_translate("MainWindow", "nfolds_test", None))

    def std_norm(self, MainWindow):
        self.Normalization = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Normalization.setFont(font)
        self.Normalization.setObjectName(_fromUtf8("Normalization"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Normalization)
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setMargin(11)
        self.horizontalLayout_25.setSpacing(6)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem)
        self.NormValuebutton = QtGui.QPushButton(self.Normalization)
        self.NormValuebutton.setObjectName(_fromUtf8("NormValuebutton"))
        self.horizontalLayout_25.addWidget(self.NormValuebutton)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.verticalLayout_8.addWidget(self.Normalization)
        self.Normalization.setTitle(_translate("MainWindow", "Normalization", None))
        self.NormValuebutton.setText(_translate("MainWindow", "Add Value", None))
        self.NormValuebutton.clicked.connect(lambda: pysat_ui.val_norm(self, MainWindow, self.count))


    def val_norm(self, MainWindow, count):
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.norm_label = QtGui.QLabel(self.Normalization)
        self.norm_label.setObjectName(_fromUtf8("norm_label"))
        self.horizontalLayout_2.addWidget(self.norm_label)
        
        self.norm_spinBox_[(count*2)-1] = QtGui.QSpinBox(self.Normalization)    # All the left side boxes
        self.norm_spinBox_[(count*2)] = QtGui.QSpinBox(self.Normalization)      # All the right side boxes

        self.norm_spinBox_[(count*2)-1].setMaximum(1000)                        # set the maximums for the left side
        self.norm_spinBox_[(count*2)].setMaximum(1000)                          # set the maximums for the right side
        self.horizontalLayout_2.addWidget(self.norm_spinBox_[(count*2)-1])      # adding the actual object to UI (left)
        self.horizontalLayout_2.addWidget(self.norm_spinBox_[(count*2)])        # adding the actual object to UI (right)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)                # setting up layout
        self.verticalLayout.addLayout(self.verticalLayout_2)                    # setting up layout

        # for debugging purposes
        left_value = self.norm_spinBox_[(count*2)-1].text()
        right_value = self.norm_spinBox_[count*2].text()
        self.norm_spinBox_[(count*2)-1].editingFinished.connect(lambda: self.isWithinRange(left_value, right_value))
        self.norm_spinBox_[(count*2)].editingFinished.connect(lambda: self.isWithinRange())

        self.norm_label.setText(_translate("MainWindow", "Value {}".format(self.count), None))
        self.count += 1

    ####These functions below are private and add functionality to the UI

    def isWithinRange(self, low, high):
        """
        isWithinRange(int, int)
        all values in spinboxes must go least to greatest
        value 0: [] []
        value 1: [1st] [2nd]

        or

        value 0: [] [1st]
        value 1: [2nd] []


        """

        # if (low > high):


        # if int(self.spinbox.text()) >= low and int(self.spinbox.text()) <= high:
        #     return
        # else:
        #     self.spinbox.setText("")

    def on_maskFile_clicked(self):
        filename = QFileDialog.getOpenFileName(None, "Open Mask File", '.', "(*.csv)")
        self.lineEdit.setText(filename)
        if self.lineEdit.text() == "":
            self.lineEdit.setText("*.csv")

    def on_uknownDataButton_clicked(self):
        filename = QFileDialog.getOpenFileName(None, "Open Uknown Data File", '.', "(*.csv)")
        self.lineEdit_2.setText(filename)
        if self.lineEdit_2.text() == "":
            self.lineEdit_2.setText("*.csv")

    def on_fullDataBaseButton_clicked(self):
        filename = QFileDialog.getOpenFileName(None, "Open Uknown Data File", '.', "(*.csv)")
        self.lineEdit_3.setText(filename)
        if self.lineEdit_3.text() == "":
            self.lineEdit_3.setText("*.csv")

    def on_outPutLocationButton_clicked(self):
        filename = QFileDialog.getExistingDirectory(None, "Select Output Directory", '.')
        self.lineEdit_4.setText(filename)
        if self.lineEdit_4.text() == "":
            self.lineEdit_4.setText("*/*")

    def on_okButton_clicked(self):
        print(self.lineEdit.text())
        print(self.lineEdit_2.text())
        print(self.lineEdit_3.text())
        print(self.lineEdit_4.text())

    ####These functions allow for interactions of buttons

    def menu_item_shortcuts(self):
        self.actionCreate_New_Workflow.setShortcut("ctrl+N")
        self.actionLoad_Unknown_Data.setShortcut("ctrl+O")
        self.actionExit.setShortcut("ctrl+Q")

    def menu_item_functions(self, MainWindow):
        self.actionLoad_Unknown_Data.triggered.connect(lambda: pysat_ui.files(self, MainWindow))
        self.actionNormalization.triggered.connect(lambda: pysat_ui.std_norm(self, MainWindow))
        self.actionElement_Name_Setup.triggered.connect(lambda: pysat_ui.element_name_setup(self, MainWindow))
        self.actionComposition_Ranges.triggered.connect(lambda: pysat_ui.compranges(self, MainWindow))
        self.actionCreate_Models.triggered.connect(lambda: pysat_ui.createmodels(self, MainWindow))

    def save(self):
        # TODO save the current window's data into a save file
        pass

    def open(self):
        # TODO open file dialog
        self.filename = QFileDialog.getOpenFileName(self, "Open a Workflow File", '.', "(*.wrf)")
