import sys
from PyQt4 import QtCore, QtGui
from PyQt4.QtGui import *
from pysat_function import pysat_func

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class pysat_ui(object):
    count = 0

    def __init__(self):
        self.pysat_fun = pysat_func()
        self.norm_spinBox_ = [None] * 1024
        self.spin_array = [None] * 1024
        self.addFunc = []
        self.addParam = []

        pysat_ui.count = 1

    def mainframe(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(581, 843)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_9.setMargin(11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.scrollArea = QtGui.QScrollArea(self.centralWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 557, 695))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.scrollAreaWidgetContents_2.setFont(font)
        self.scrollAreaWidgetContents_2.setStyleSheet(_fromUtf8("QGroupBox {\n"
                                                                "  border: 2px solid gray;\n"
                                                                "  border-radius: 6px;\n"
                                                                "  margin-top: 0.5em;\n"
                                                                "}\n"
                                                                "\n"
                                                                "QGroupBox::title {\n"
                                                                "\n"
                                                                "  padding-top: -14px;\n"
                                                                "  padding-left: 8px;\n"
                                                                "}\n"
                                                                ""))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.setMargin(11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 581, 26))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPreprocessing = QtGui.QMenu(self.menuBar)
        self.menuPreprocessing.setObjectName(_fromUtf8("menuPreprocessing"))
        self.menuBaseline_Removal = QtGui.QMenu(self.menuPreprocessing)
        self.menuBaseline_Removal.setObjectName(_fromUtf8("menuBaseline_Removal"))
        self.menuCalibration_Transfer = QtGui.QMenu(self.menuPreprocessing)
        self.menuCalibration_Transfer.setObjectName(_fromUtf8("menuCalibration_Transfer"))
        self.menuRegression = QtGui.QMenu(self.menuBar)
        self.menuRegression.setObjectName(_fromUtf8("menuRegression"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuClassification = QtGui.QMenu(self.menuBar)
        self.menuClassification.setObjectName(_fromUtf8("menuClassification"))
        self.menuSupervised = QtGui.QMenu(self.menuClassification)
        self.menuSupervised.setObjectName(_fromUtf8("menuSupervised"))
        self.menuClustering = QtGui.QMenu(self.menuClassification)
        self.menuClustering.setObjectName(_fromUtf8("menuClustering"))
        self.menuVisualization = QtGui.QMenu(self.menuBar)
        self.menuVisualization.setObjectName(_fromUtf8("menuVisualization"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionLoad_reference_Data = QtGui.QAction(MainWindow)
        self.actionLoad_reference_Data.setObjectName(_fromUtf8("actionLoad_reference_Data"))
        self.actionLoad_Unknown_Data = QtGui.QAction(MainWindow)
        self.actionLoad_Unknown_Data.setObjectName(_fromUtf8("actionLoad_Unknown_Data"))
        self.actionSave_Current_Workflow = QtGui.QAction(MainWindow)
        self.actionSave_Current_Workflow.setObjectName(_fromUtf8("actionSave_Current_Workflow"))
        self.actionSave_Current_Plots = QtGui.QAction(MainWindow)
        self.actionSave_Current_Plots.setObjectName(_fromUtf8("actionSave_Current_Plots"))
        self.actionSave_Current_Data = QtGui.QAction(MainWindow)
        self.actionSave_Current_Data.setObjectName(_fromUtf8("actionSave_Current_Data"))
        self.actionCreate_New_Workflow = QtGui.QAction(MainWindow)
        self.actionCreate_New_Workflow.setObjectName(_fromUtf8("actionCreate_New_Workflow"))
        self.actionNoise_Reduction = QtGui.QAction(MainWindow)
        self.actionNoise_Reduction.setObjectName(_fromUtf8("actionNoise_Reduction"))
        self.actionApply_Mask = QtGui.QAction(MainWindow)
        self.actionApply_Mask.setObjectName(_fromUtf8("actionApply_Mask"))
        self.actionInterpolate = QtGui.QAction(MainWindow)
        self.actionInterpolate.setObjectName(_fromUtf8("actionInterpolate"))
        self.actionInstrument_Response = QtGui.QAction(MainWindow)
        self.actionInstrument_Response.setObjectName(_fromUtf8("actionInstrument_Response"))
        self.actionALS = QtGui.QAction(MainWindow)
        self.actionALS.setObjectName(_fromUtf8("actionALS"))
        self.actionDietrich = QtGui.QAction(MainWindow)
        self.actionDietrich.setObjectName(_fromUtf8("actionDietrich"))
        self.actionPolyFit = QtGui.QAction(MainWindow)
        self.actionPolyFit.setObjectName(_fromUtf8("actionPolyFit"))
        self.actionAirPLS = QtGui.QAction(MainWindow)
        self.actionAirPLS.setObjectName(_fromUtf8("actionAirPLS"))
        self.actionFABC = QtGui.QAction(MainWindow)
        self.actionFABC.setObjectName(_fromUtf8("actionFABC"))
        self.actionKK = QtGui.QAction(MainWindow)
        self.actionKK.setObjectName(_fromUtf8("actionKK"))
        self.actionMario = QtGui.QAction(MainWindow)
        self.actionMario.setObjectName(_fromUtf8("actionMario"))
        self.actionMedian = QtGui.QAction(MainWindow)
        self.actionMedian.setObjectName(_fromUtf8("actionMedian"))
        self.actionRubberband = QtGui.QAction(MainWindow)
        self.actionRubberband.setObjectName(_fromUtf8("actionRubberband"))
        self.actionUndecimated_Wavelet = QtGui.QAction(MainWindow)
        self.actionUndecimated_Wavelet.setObjectName(_fromUtf8("actionUndecimated_Wavelet"))
        self.actionRatio = QtGui.QAction(MainWindow)
        self.actionRatio.setObjectName(_fromUtf8("actionRatio"))
        self.actionTommy_s_Methgod = QtGui.QAction(MainWindow)
        self.actionTommy_s_Methgod.setObjectName(_fromUtf8("actionTommy_s_Methgod"))
        self.actionPiecewise_Direct_Standardization = QtGui.QAction(MainWindow)
        self.actionPiecewise_Direct_Standardization.setObjectName(_fromUtf8("actionPiecewise_Direct_Standardization"))
        self.actionPCA = QtGui.QAction(MainWindow)
        self.actionPCA.setObjectName(_fromUtf8("actionPCA"))
        self.actionICA = QtGui.QAction(MainWindow)
        self.actionICA.setObjectName(_fromUtf8("actionICA"))
        self.actionK_Means = QtGui.QAction(MainWindow)
        self.actionK_Means.setObjectName(_fromUtf8("actionK_Means"))
        self.actionHierarchical = QtGui.QAction(MainWindow)
        self.actionHierarchical.setObjectName(_fromUtf8("actionHierarchical"))
        self.actionOthers = QtGui.QAction(MainWindow)
        self.actionOthers.setObjectName(_fromUtf8("actionOthers"))
        self.actionOthers_2 = QtGui.QAction(MainWindow)
        self.actionOthers_2.setObjectName(_fromUtf8("actionOthers_2"))
        self.actionOthers_3 = QtGui.QAction(MainWindow)
        self.actionOthers_3.setObjectName(_fromUtf8("actionOthers_3"))
        self.actionPLS = QtGui.QAction(MainWindow)
        self.actionPLS.setObjectName(_fromUtf8("actionPLS"))
        self.actionSM_PLS = QtGui.QAction(MainWindow)
        self.actionSM_PLS.setObjectName(_fromUtf8("actionSM_PLS"))
        self.actionICA_Regression = QtGui.QAction(MainWindow)
        self.actionICA_Regression.setObjectName(_fromUtf8("actionICA_Regression"))
        self.actionGaussian_Process = QtGui.QAction(MainWindow)
        self.actionGaussian_Process.setObjectName(_fromUtf8("actionGaussian_Process"))
        self.actionMLP = QtGui.QAction(MainWindow)
        self.actionMLP.setObjectName(_fromUtf8("actionMLP"))
        self.actionSVM = QtGui.QAction(MainWindow)
        self.actionSVM.setObjectName(_fromUtf8("actionSVM"))
        self.actionOthers_4 = QtGui.QAction(MainWindow)
        self.actionOthers_4.setObjectName(_fromUtf8("actionOthers_4"))
        self.actionOthers_5 = QtGui.QAction(MainWindow)
        self.actionOthers_5.setObjectName(_fromUtf8("actionOthers_5"))
        self.actionIndex = QtGui.QAction(MainWindow)
        self.actionIndex.setObjectName(_fromUtf8("actionIndex"))
        self.actionContent_2 = QtGui.QAction(MainWindow)
        self.actionContent_2.setObjectName(_fromUtf8("actionContent_2"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAbout_QtCreator = QtGui.QAction(MainWindow)
        self.actionAbout_QtCreator.setObjectName(_fromUtf8("actionAbout_QtCreator"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionNormalization = QtGui.QAction(MainWindow)
        self.actionNormalization.setObjectName(_fromUtf8("actionNormalization"))
        self.actionICA_2 = QtGui.QAction(MainWindow)
        self.actionICA_2.setObjectName(_fromUtf8("actionICA_2"))
        self.actionPCA_2 = QtGui.QAction(MainWindow)
        self.actionPCA_2.setObjectName(_fromUtf8("actionPCA_2"))
        self.actionPLS_DA = QtGui.QAction(MainWindow)
        self.actionPLS_DA.setObjectName(_fromUtf8("actionPLS_DA"))
        self.actionSIMCA = QtGui.QAction(MainWindow)
        self.actionSIMCA.setObjectName(_fromUtf8("actionSIMCA"))
        self.actionK_means = QtGui.QAction(MainWindow)
        self.actionK_means.setObjectName(_fromUtf8("actionK_means"))
        self.actionHierarchical_2 = QtGui.QAction(MainWindow)
        self.actionHierarchical_2.setObjectName(_fromUtf8("actionHierarchical_2"))
        self.actionCross_Validation = QtGui.QAction(MainWindow)
        self.actionCross_Validation.setObjectName(_fromUtf8("actionCross_Validation"))
        self.actionTrain = QtGui.QAction(MainWindow)
        self.actionTrain.setObjectName(_fromUtf8("actionTrain"))
        self.actionPredict = QtGui.QAction(MainWindow)
        self.actionPredict.setObjectName(_fromUtf8("actionPredict"))
        self.actionLine_Plot = QtGui.QAction(MainWindow)
        self.actionLine_Plot.setObjectName(_fromUtf8("actionLine_Plot"))
        self.action1_to_1_Plot = QtGui.QAction(MainWindow)
        self.action1_to_1_Plot.setObjectName(_fromUtf8("action1_to_1_Plot"))
        self.actionScatter_Plot = QtGui.QAction(MainWindow)
        self.actionScatter_Plot.setObjectName(_fromUtf8("actionScatter_Plot"))
        self.actionSet_output_location = QtGui.QAction(MainWindow)
        self.actionSet_output_location.setObjectName(_fromUtf8("actionSet_output_location"))
        self.actionCreate_N_Folds = QtGui.QAction(MainWindow)
        self.actionCreate_N_Folds.setObjectName(_fromUtf8("actionCreate_N_Folds"))
        self.actionCreate_Test_Folds = QtGui.QAction(MainWindow)
        self.actionCreate_Test_Folds.setObjectName(_fromUtf8("actionCreate_Test_Folds"))
        self.actionStratified_Folds = QtGui.QAction(MainWindow)
        self.actionStratified_Folds.setObjectName(_fromUtf8("actionStratified_Folds"))
        self.actionTrain_Submodels = QtGui.QAction(MainWindow)
        self.actionTrain_Submodels.setObjectName(_fromUtf8("actionTrain_Submodels"))
        self.menuFile.addAction(self.actionLoad_reference_Data)
        self.menuFile.addAction(self.actionLoad_Unknown_Data)
        self.menuFile.addAction(self.actionSet_output_location)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Current_Plots)
        self.menuFile.addAction(self.actionSave_Current_Data)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionCreate_New_Workflow)
        self.menuFile.addAction(self.actionSave_Current_Workflow)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuBaseline_Removal.addAction(self.actionALS)
        self.menuBaseline_Removal.addAction(self.actionDietrich)
        self.menuBaseline_Removal.addAction(self.actionPolyFit)
        self.menuBaseline_Removal.addAction(self.actionAirPLS)
        self.menuBaseline_Removal.addAction(self.actionFABC)
        self.menuBaseline_Removal.addAction(self.actionKK)
        self.menuBaseline_Removal.addAction(self.actionMario)
        self.menuBaseline_Removal.addAction(self.actionMedian)
        self.menuBaseline_Removal.addAction(self.actionRubberband)
        self.menuBaseline_Removal.addAction(self.actionUndecimated_Wavelet)
        self.menuCalibration_Transfer.addAction(self.actionRatio)
        self.menuCalibration_Transfer.addAction(self.actionTommy_s_Methgod)
        self.menuCalibration_Transfer.addAction(self.actionPiecewise_Direct_Standardization)
        self.menuCalibration_Transfer.addAction(self.actionOthers_3)
        self.menuPreprocessing.addAction(self.actionNormalization)
        self.menuPreprocessing.addAction(self.actionNoise_Reduction)
        self.menuPreprocessing.addAction(self.actionApply_Mask)
        self.menuPreprocessing.addAction(self.actionInterpolate)
        self.menuPreprocessing.addAction(self.actionInstrument_Response)
        self.menuPreprocessing.addAction(self.menuBaseline_Removal.menuAction())
        self.menuPreprocessing.addAction(self.menuCalibration_Transfer.menuAction())
        self.menuPreprocessing.addAction(self.actionICA_2)
        self.menuPreprocessing.addAction(self.actionPCA_2)
        self.menuPreprocessing.addAction(self.actionStratified_Folds)
        self.menuRegression.addAction(self.actionCross_Validation)
        self.menuRegression.addAction(self.actionTrain)
        self.menuRegression.addAction(self.actionTrain_Submodels)
        self.menuRegression.addAction(self.actionPredict)
        self.menuHelp.addAction(self.actionIndex)
        self.menuHelp.addAction(self.actionContent_2)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_QtCreator)
        self.menuSupervised.addAction(self.actionPLS_DA)
        self.menuSupervised.addAction(self.actionSIMCA)
        self.menuClustering.addAction(self.actionK_means)
        self.menuClustering.addAction(self.actionHierarchical_2)
        self.menuClassification.addAction(self.menuSupervised.menuAction())
        self.menuClassification.addAction(self.menuClustering.menuAction())
        self.menuVisualization.addAction(self.actionLine_Plot)
        self.menuVisualization.addAction(self.action1_to_1_Plot)
        self.menuVisualization.addAction(self.actionScatter_Plot)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuPreprocessing.menuAction())
        self.menuBar.addAction(self.menuClassification.menuAction())
        self.menuBar.addAction(self.menuRegression.menuAction())
        self.menuBar.addAction(self.menuVisualization.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setWindowTitle(_translate("MainWindow", "PYSAT", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuPreprocessing.setTitle(_translate("MainWindow", "Preprocessing", None))
        self.menuBaseline_Removal.setTitle(_translate("MainWindow", "Baseline Removal", None))
        self.menuCalibration_Transfer.setTitle(_translate("MainWindow", "Calibration Transfer", None))
        self.menuRegression.setTitle(_translate("MainWindow", "Regression", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuClassification.setTitle(_translate("MainWindow", "Classification", None))
        self.menuSupervised.setTitle(_translate("MainWindow", "Supervised", None))
        self.menuClustering.setTitle(_translate("MainWindow", "Clustering", None))
        self.menuVisualization.setTitle(_translate("MainWindow", "Visualization", None))
        self.actionLoad_reference_Data.setText(_translate("MainWindow", "Load Reference Data", None))
        self.actionLoad_Unknown_Data.setText(_translate("MainWindow", "Load Unknown Data", None))
        self.actionSave_Current_Workflow.setText(_translate("MainWindow", "Save Current Workflow", None))
        self.actionSave_Current_Plots.setText(_translate("MainWindow", "Save Current Plots", None))
        self.actionSave_Current_Data.setText(_translate("MainWindow", "Save Current Data", None))
        self.actionCreate_New_Workflow.setText(_translate("MainWindow", "Create New Workflow", None))
        self.actionNoise_Reduction.setText(_translate("MainWindow", "Noise Reduction", None))
        self.actionApply_Mask.setText(_translate("MainWindow", "Apply Mask", None))
        self.actionInterpolate.setText(_translate("MainWindow", "Interpolate (unknown to known)", None))
        self.actionInstrument_Response.setText(_translate("MainWindow", "Instrument Response", None))
        self.actionALS.setText(_translate("MainWindow", "ALS", None))
        self.actionDietrich.setText(_translate("MainWindow", "Dietrich", None))
        self.actionPolyFit.setText(_translate("MainWindow", "PolyFit", None))
        self.actionAirPLS.setText(_translate("MainWindow", "AirPLS", None))
        self.actionFABC.setText(_translate("MainWindow", "FABC", None))
        self.actionKK.setText(_translate("MainWindow", "KK", None))
        self.actionMario.setText(_translate("MainWindow", "Mario", None))
        self.actionMedian.setText(_translate("MainWindow", "Median", None))
        self.actionRubberband.setText(_translate("MainWindow", "Rubberband", None))
        self.actionUndecimated_Wavelet.setText(_translate("MainWindow", "Undecimated Wavelet", None))
        self.actionRatio.setText(_translate("MainWindow", "Ratio", None))
        self.actionTommy_s_Methgod.setText(_translate("MainWindow", "Tommy\'s Method", None))
        self.actionPiecewise_Direct_Standardization.setText(
            _translate("MainWindow", "Piecewise Direct Standardization", None))
        self.actionPCA.setText(_translate("MainWindow", "PCA", None))
        self.actionICA.setText(_translate("MainWindow", "ICA", None))
        self.actionK_Means.setText(_translate("MainWindow", "K-Means", None))
        self.actionHierarchical.setText(_translate("MainWindow", "Hierarchical", None))
        self.actionOthers.setText(_translate("MainWindow", "Others...", None))
        self.actionOthers_2.setText(_translate("MainWindow", "Others...", None))
        self.actionOthers_3.setText(_translate("MainWindow", "Others...", None))
        self.actionPLS.setText(_translate("MainWindow", "PLS", None))
        self.actionSM_PLS.setText(_translate("MainWindow", "SM-PLS", None))
        self.actionICA_Regression.setText(_translate("MainWindow", "ICA Regression", None))
        self.actionGaussian_Process.setText(_translate("MainWindow", "Gaussian Process", None))
        self.actionMLP.setText(_translate("MainWindow", "MLP", None))
        self.actionSVM.setText(_translate("MainWindow", "SVM", None))
        self.actionOthers_4.setText(_translate("MainWindow", "Others...", None))
        self.actionOthers_5.setText(_translate("MainWindow", "Others...", None))
        self.actionIndex.setText(_translate("MainWindow", "Index", None))
        self.actionContent_2.setText(_translate("MainWindow", "Content", None))
        self.actionAbout.setText(_translate("MainWindow", "About...", None))
        self.actionAbout_QtCreator.setText(_translate("MainWindow", "About Qt...", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionNormalization.setText(_translate("MainWindow", "Normalization", None))
        self.actionICA_2.setText(_translate("MainWindow", "ICA", None))
        self.actionPCA_2.setText(_translate("MainWindow", "PCA", None))
        self.actionPLS_DA.setText(_translate("MainWindow", "PLS-DA", None))
        self.actionSIMCA.setText(_translate("MainWindow", "SIMCA", None))
        self.actionK_means.setText(_translate("MainWindow", "K-means", None))
        self.actionHierarchical_2.setText(_translate("MainWindow", "Hierarchical", None))
        self.actionCross_Validation.setText(_translate("MainWindow", "Cross Validation", None))
        self.actionTrain.setText(_translate("MainWindow", "Train", None))
        self.actionPredict.setText(_translate("MainWindow", "Predict", None))
        self.actionLine_Plot.setText(_translate("MainWindow", "Line Plot", None))
        self.action1_to_1_Plot.setText(_translate("MainWindow", "1 to 1 Plot", None))
        self.actionScatter_Plot.setText(_translate("MainWindow", "Scatter Plot", None))
        self.actionSet_output_location.setText(_translate("MainWindow", "Output Location", None))
        self.actionCreate_N_Folds.setText(_translate("MainWindow", "Create N Folds", None))
        self.actionStratified_Folds.setText(_translate("MainWindow", "Stratified Folds", None))

    """
    UI modules
    """

    def ok_button(self, MainWindow):
        self.OK = QtGui.QGroupBox(self.centralWidget)
        self.OK.setObjectName(_fromUtf8("OK"))
        self.ok = QtGui.QHBoxLayout(self.OK)
        self.ok.setMargin(11)
        self.ok.setSpacing(6)
        self.ok.setObjectName(_fromUtf8("ok"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.ok.addItem(spacerItem)
        self.okButton = QtGui.QPushButton(self.OK)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.okButton.setFont(font)
        self.okButton.setMouseTracking(False)
        self.okButton.setObjectName(_fromUtf8("okButton"))
        self.ok.addWidget(self.okButton)
        self.verticalLayout_9.addWidget(self.OK)
        self.okButton.setText(_translate("MainWindow", "OK", None))
        try:
            self.okButton.clicked.connect(lambda: pysat_ui.on_okButton_clicked(self))

        except:
            pass

    def unknown_data(self, MainWindow):
        self.addFunc.append(lambda: pysat_ui.on_getDataButton_clicked())
        self.unknownData = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.unknownData.setFont(font)
        self.unknownData.setObjectName(_fromUtf8("unknownData"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.unknownData)
        self.verticalLayout_6.setMargin(11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.unknownData)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lineEdit_2 = QtGui.QLineEdit(self.unknownData)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setMargin(11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.unknownDataButton = QtGui.QToolButton(self.unknownData)
        self.unknownDataButton.setObjectName(_fromUtf8("unknownDataButton"))
        self.verticalLayout_5.addWidget(self.unknownDataButton)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addWidget(self.unknownData)
        self.unknownData.raise_()
        self.unknownData.setTitle(_translate("MainWindow", "File", None))
        self.label.setText(_translate("MainWindow", "Unknown Data", None))
        self.lineEdit_2.setText(_translate("MainWindow", "*.csv", None))
        self.unknownDataButton.setText(_translate("MainWindow", "...", None))
        try:
            self.unknownDataButton.clicked.connect(lambda: self.addParam.append(self.lineEdit_2, 'Unknown Data'))
        except:
            pass

    def reference_data(self, MainWindow):
        self.referenceData = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.referenceData.setFont(font)
        self.referenceData.setObjectName(_fromUtf8("referenceData"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.referenceData)
        self.verticalLayout_15.setMargin(11)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setMargin(11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setMargin(11)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_8 = QtGui.QLabel(self.referenceData)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_16.addWidget(self.label_8)
        self.horizontalLayout_11.addLayout(self.verticalLayout_16)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setMargin(11)
        self.verticalLayout_20.setSpacing(6)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.lineEdit_9 = QtGui.QLineEdit(self.referenceData)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.verticalLayout_20.addWidget(self.lineEdit_9)
        self.horizontalLayout_11.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setMargin(11)
        self.verticalLayout_21.setSpacing(6)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.fullDataBaseButton_3 = QtGui.QToolButton(self.referenceData)
        self.fullDataBaseButton_3.setObjectName(_fromUtf8("fullDataBaseButton_3"))
        self.verticalLayout_21.addWidget(self.fullDataBaseButton_3)
        self.horizontalLayout_11.addLayout(self.verticalLayout_21)
        self.verticalLayout_15.addLayout(self.horizontalLayout_11)
        self.verticalLayout_8.addWidget(self.referenceData)
        self.referenceData.raise_()
        self.referenceData.setTitle(_translate("MainWindow", "File", None))
        self.label_8.setText(_translate("MainWindow", "Full Database", None))
        self.lineEdit_9.setText(_translate("MainWindow", "*.csv", None))
        self.fullDataBaseButton_3.setText(_translate("MainWindow", "...", None))
        try:
            self.fullDataBaseButton_3.clicked.connect(
                lambda: pysat_ui.on_getDataButton_clicked(self, self.lineEdit_9, 'Known Data'))
        except:
            pass

    def output_folder(self, MainWindow):
        self.outputFolder = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.outputFolder.setFont(font)
        self.outputFolder.setObjectName(_fromUtf8("outputFolder"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.outputFolder)
        self.verticalLayout_22.setMargin(11)
        self.verticalLayout_22.setSpacing(6)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setMargin(11)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setMargin(11)
        self.verticalLayout_25.setSpacing(6)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.label_9 = QtGui.QLabel(self.outputFolder)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_25.addWidget(self.label_9)
        self.horizontalLayout_13.addLayout(self.verticalLayout_25)
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setMargin(11)
        self.verticalLayout_28.setSpacing(6)
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.lineEdit_10 = QtGui.QLineEdit(self.outputFolder)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.verticalLayout_28.addWidget(self.lineEdit_10)
        self.horizontalLayout_13.addLayout(self.verticalLayout_28)
        self.verticalLayout_29 = QtGui.QVBoxLayout()
        self.verticalLayout_29.setMargin(11)
        self.verticalLayout_29.setSpacing(6)
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.fullDataBaseButton_4 = QtGui.QToolButton(self.outputFolder)
        self.fullDataBaseButton_4.setObjectName(_fromUtf8("fullDataBaseButton_4"))
        self.verticalLayout_29.addWidget(self.fullDataBaseButton_4)
        self.horizontalLayout_13.addLayout(self.verticalLayout_29)
        self.verticalLayout_22.addLayout(self.horizontalLayout_13)
        self.verticalLayout_8.addWidget(self.outputFolder)
        self.outputFolder.raise_()
        self.outputFolder.setTitle(_translate("MainWindow", "Output", None))
        self.label_9.setText(_translate("MainWindow", "Output Folder", None))
        self.lineEdit_10.setText(_translate("MainWindow", "*.*", None))
        self.fullDataBaseButton_4.setText(_translate("MainWindow", "...", None))
        try:
            self.fullDataBaseButton_4.clicked.connect(
                lambda: pysat_ui.on_outPutLocationButton_clicked(self, self.lineEdit_10))
        except:
            pass

    def normalization(self, MainWindow):
        self.Normalization = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Normalization.setFont(font)
        self.Normalization.setObjectName(_fromUtf8("Normalization"))
        self.verticalLayout_27 = QtGui.QVBoxLayout(self.Normalization)
        self.verticalLayout_27.setMargin(11)
        self.verticalLayout_27.setSpacing(6)
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setMargin(11)
        self.verticalLayout_26.setSpacing(6)
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.norm_label = QtGui.QLabel(self.Normalization)
        self.norm_label.setObjectName(_fromUtf8("norm_label"))
        self.horizontalLayout_2.addWidget(self.norm_label)
        self.norm_spinBox_9 = QtGui.QSpinBox(self.Normalization)
        self.norm_spinBox_9.setMaximum(1000)
        self.norm_spinBox_9.setObjectName(_fromUtf8("norm_spinBox_9"))
        self.horizontalLayout_2.addWidget(self.norm_spinBox_9)
        self.norm_spinBox = QtGui.QSpinBox(self.Normalization)
        self.norm_spinBox.setMaximum(1000)
        self.norm_spinBox.setObjectName(_fromUtf8("norm_spinBox"))
        self.horizontalLayout_2.addWidget(self.norm_spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_26.addLayout(self.verticalLayout_2)
        self.verticalLayout_27.addLayout(self.verticalLayout_26)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setMargin(11)
        self.horizontalLayout_25.setSpacing(6)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem)
        self.NormValuebutton = QtGui.QPushButton(self.Normalization)
        self.NormValuebutton.setObjectName(_fromUtf8("NormValuebutton"))
        self.horizontalLayout_25.addWidget(self.NormValuebutton)
        self.verticalLayout_27.addLayout(self.horizontalLayout_25)
        self.verticalLayout_8.addWidget(self.Normalization)
        self.Normalization.raise_()
        self.Normalization.setTitle(_translate("MainWindow", "Normalization", None))
        self.norm_label.setText(_translate("MainWindow", "Value 1", None))
        self.NormValuebutton.setText(_translate("MainWindow", "Add Value", None))
        self.normalization_button = QtGui.QPushButton(self.Normalization)
        self.set_module_button(self.verticalLayout_27, self.normalization_button)
        try:
            self.normalization_button.clicked.connect(
                lambda: self.pysat_fun.get_ranges(([(int(self.norm_spinBox_9.text()),
                                                     int(self.norm_spinBox.text()))])))
        except:
            pass

    def comp_ranges(self, MainWindow):
        self.CompRanges = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CompRanges.setFont(font)
        self.CompRanges.setObjectName(_fromUtf8("CompRanges"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.CompRanges)
        self.verticalLayout_7.setMargin(11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_80 = QtGui.QLabel(self.CompRanges)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.horizontalLayout_3.addWidget(self.label_80)
        self.comp_range = QtGui.QSpinBox(self.CompRanges)
        self.comp_range.setMinimum(-100)
        self.comp_range.setMaximum(1000)
        self.comp_range.setObjectName(_fromUtf8("comp_range"))
        self.horizontalLayout_3.addWidget(self.comp_range)
        self.comp_range_2 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_2.setMaximum(1000)
        self.comp_range_2.setObjectName(_fromUtf8("comp_range_2"))
        self.horizontalLayout_3.addWidget(self.comp_range_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setMargin(11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_81 = QtGui.QLabel(self.CompRanges)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.horizontalLayout_5.addWidget(self.label_81)
        self.comp_range_3 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_3.setMaximum(1000)
        self.comp_range_3.setObjectName(_fromUtf8("comp_range_3"))
        self.horizontalLayout_5.addWidget(self.comp_range_3)
        self.comp_range_4 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_4.setMaximum(1000)
        self.comp_range_4.setObjectName(_fromUtf8("comp_range_4"))
        self.horizontalLayout_5.addWidget(self.comp_range_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setMargin(11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_82 = QtGui.QLabel(self.CompRanges)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.horizontalLayout_7.addWidget(self.label_82)
        self.comp_range_5 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_5.setMaximum(1000)
        self.comp_range_5.setObjectName(_fromUtf8("comp_range_5"))
        self.horizontalLayout_7.addWidget(self.comp_range_5)
        self.comp_range_6 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_6.setMaximum(1000)
        self.comp_range_6.setObjectName(_fromUtf8("comp_range_6"))
        self.horizontalLayout_7.addWidget(self.comp_range_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setMargin(11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_85 = QtGui.QLabel(self.CompRanges)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.horizontalLayout_10.addWidget(self.label_85)
        self.comp_range_7 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_7.setMaximum(1000)
        self.comp_range_7.setObjectName(_fromUtf8("comp_range_7"))
        self.horizontalLayout_10.addWidget(self.comp_range_7)
        self.comp_range_8 = QtGui.QSpinBox(self.CompRanges)
        self.comp_range_8.setMaximum(1000)
        self.comp_range_8.setObjectName(_fromUtf8("comp_range_8"))
        self.horizontalLayout_10.addWidget(self.comp_range_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setMargin(11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_40 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_9.addWidget(self.label_40)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setMargin(11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_20 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_6.addWidget(self.label_20)
        self.label_21 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_6.addWidget(self.label_21)
        self.label_22 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_6.addWidget(self.label_22)
        self.label_23 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_6.addWidget(self.label_23)
        self.label_24 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_6.addWidget(self.label_24)
        self.label_27 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_6.addWidget(self.label_27)
        self.label_29 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_6.addWidget(self.label_29)
        self.label_28 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_6.addWidget(self.label_28)
        self.label_26 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_6.addWidget(self.label_26)
        self.label_25 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_6.addWidget(self.label_25)
        self.label_32 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_6.addWidget(self.label_32)
        self.label_30 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_6.addWidget(self.label_30)
        self.label_33 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_6.addWidget(self.label_33)
        self.label_34 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_6.addWidget(self.label_34)
        self.label_31 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_6.addWidget(self.label_31)
        self.label_39 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_6.addWidget(self.label_39)
        self.label_36 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_6.addWidget(self.label_36)
        self.label_37 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_6.addWidget(self.label_37)
        self.label_35 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_6.addWidget(self.label_35)
        self.label_38 = QtGui.QLabel(self.CompRanges)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_6.addWidget(self.label_38)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayout_8.addWidget(self.CompRanges)
        self.CompRanges.raise_()
        QtCore.QObject.connect(self.comp_range, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_21.setNum)
        QtCore.QObject.connect(self.comp_range_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_23.setNum)
        QtCore.QObject.connect(self.comp_range_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_29.setNum)
        QtCore.QObject.connect(self.comp_range_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_26.setNum)
        QtCore.QObject.connect(self.comp_range_5, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_30.setNum)
        QtCore.QObject.connect(self.comp_range_6, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_34.setNum)
        QtCore.QObject.connect(self.comp_range_7, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_36.setNum)
        QtCore.QObject.connect(self.comp_range_8, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.label_35.setNum)
        self.CompRanges.setTitle(_translate("MainWindow", "Submodel Ranges", None))
        self.label_80.setText(_translate("MainWindow", "Value 1", None))
        self.label_81.setText(_translate("MainWindow", "Value 2", None))
        self.label_82.setText(_translate("MainWindow", "Value 3", None))
        self.label_85.setText(_translate("MainWindow", "Full Model Value", None))
        self.label_40.setText(_translate("MainWindow", "compranges", None))
        self.label_20.setText(_translate("MainWindow", "[", None))
        self.label_21.setText(_translate("MainWindow", "0", None))
        self.label_22.setText(_translate("MainWindow", ",", None))
        self.label_23.setText(_translate("MainWindow", "0", None))
        self.label_24.setText(_translate("MainWindow", "]", None))
        self.label_27.setText(_translate("MainWindow", "[", None))
        self.label_29.setText(_translate("MainWindow", "0", None))
        self.label_28.setText(_translate("MainWindow", ",", None))
        self.label_26.setText(_translate("MainWindow", "0", None))
        self.label_25.setText(_translate("MainWindow", "]", None))
        self.label_32.setText(_translate("MainWindow", "[", None))
        self.label_30.setText(_translate("MainWindow", "0", None))
        self.label_33.setText(_translate("MainWindow", ",", None))
        self.label_34.setText(_translate("MainWindow", "0", None))
        self.label_31.setText(_translate("MainWindow", "]", None))
        self.label_39.setText(_translate("MainWindow", "[", None))
        self.label_36.setText(_translate("MainWindow", "0", None))
        self.label_37.setText(_translate("MainWindow", ",", None))
        self.label_35.setText(_translate("MainWindow", "0", None))
        self.label_38.setText(_translate("MainWindow", "]", None))
        self.compRanges_button = QtGui.QPushButton(self.CompRanges)
        self.set_module_button(self.verticalLayout_7, self.compRanges_button)
        try:
            self.compRanges_button.clicked.connect(
                lambda: self.pysat_fun.set_compranges([[int(self.comp_range.text()), int(self.comp_range_2.text())],
                                                       [int(self.comp_range_3.text()), int(self.comp_range_4.text())],
                                                       [int(self.comp_range_5.text()), int(self.comp_range_6.text())],
                                                       [int(self.comp_range_7.text()), int(self.comp_range_8.text())]]))
        except:
            pass

    def num_of_components(self, MainWindow):
        self.NumberComponents = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NumberComponents.setFont(font)
        self.NumberComponents.setObjectName(_fromUtf8("NumberComponents"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.NumberComponents)
        self.verticalLayout_17.setMargin(11)
        self.verticalLayout_17.setSpacing(6)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setMargin(11)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setMargin(11)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_70 = QtGui.QLabel(self.NumberComponents)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.verticalLayout_18.addWidget(self.label_70)
        self.label_71 = QtGui.QLabel(self.NumberComponents)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.verticalLayout_18.addWidget(self.label_71)
        self.label_72 = QtGui.QLabel(self.NumberComponents)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.verticalLayout_18.addWidget(self.label_72)
        self.label_73 = QtGui.QLabel(self.NumberComponents)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.verticalLayout_18.addWidget(self.label_73)
        self.horizontalLayout_14.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setMargin(11)
        self.verticalLayout_19.setSpacing(6)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.create_model_spin = QtGui.QSpinBox(self.NumberComponents)
        self.create_model_spin.setMaximum(20)
        self.create_model_spin.setObjectName(_fromUtf8("create_model_spin"))
        self.verticalLayout_19.addWidget(self.create_model_spin)
        self.create_model_spin_2 = QtGui.QSpinBox(self.NumberComponents)
        self.create_model_spin_2.setMaximum(20)
        self.create_model_spin_2.setObjectName(_fromUtf8("create_model_spin_2"))
        self.verticalLayout_19.addWidget(self.create_model_spin_2)
        self.create_model_spin_3 = QtGui.QSpinBox(self.NumberComponents)
        self.create_model_spin_3.setMaximum(20)
        self.create_model_spin_3.setObjectName(_fromUtf8("create_model_spin_3"))
        self.verticalLayout_19.addWidget(self.create_model_spin_3)
        self.create_model_spin_4 = QtGui.QSpinBox(self.NumberComponents)
        self.create_model_spin_4.setMaximum(20)
        self.create_model_spin_4.setObjectName(_fromUtf8("create_model_spin_4"))
        self.verticalLayout_19.addWidget(self.create_model_spin_4)
        self.horizontalLayout_14.addLayout(self.verticalLayout_19)
        self.verticalLayout_17.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setMargin(11)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_74 = QtGui.QLabel(self.NumberComponents)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_15.addWidget(self.label_74)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setMargin(11)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_75 = QtGui.QLabel(self.NumberComponents)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.horizontalLayout_16.addWidget(self.label_75)
        self.label_76 = QtGui.QLabel(self.NumberComponents)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.horizontalLayout_16.addWidget(self.label_76)
        self.label_77 = QtGui.QLabel(self.NumberComponents)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.horizontalLayout_16.addWidget(self.label_77)
        self.label_78 = QtGui.QLabel(self.NumberComponents)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.horizontalLayout_16.addWidget(self.label_78)
        self.label_79 = QtGui.QLabel(self.NumberComponents)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.horizontalLayout_16.addWidget(self.label_79)
        self.label_83 = QtGui.QLabel(self.NumberComponents)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.horizontalLayout_16.addWidget(self.label_83)
        self.label_84 = QtGui.QLabel(self.NumberComponents)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.horizontalLayout_16.addWidget(self.label_84)
        self.label_88 = QtGui.QLabel(self.NumberComponents)
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.horizontalLayout_16.addWidget(self.label_88)
        self.label_89 = QtGui.QLabel(self.NumberComponents)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.horizontalLayout_16.addWidget(self.label_89)
        self.label_90 = QtGui.QLabel(self.NumberComponents)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.horizontalLayout_16.addWidget(self.label_90)
        self.label_91 = QtGui.QLabel(self.NumberComponents)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.horizontalLayout_16.addWidget(self.label_91)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_16)
        self.verticalLayout_17.addLayout(self.horizontalLayout_15)
        self.verticalLayout_8.addWidget(self.NumberComponents)
        self.NumberComponents.raise_()
        QtCore.QObject.connect(self.create_model_spin_2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")),
                               self.label_79.setNum)
        QtCore.QObject.connect(self.create_model_spin, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")),
                               self.label_77.setNum)
        QtCore.QObject.connect(self.create_model_spin_3, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")),
                               self.label_84.setNum)
        QtCore.QObject.connect(self.create_model_spin_4, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")),
                               self.label_89.setNum)
        self.NumberComponents.setTitle(_translate("MainWindow", "Number of Components", None))
        self.label_70.setText(_translate("MainWindow", "Value 1", None))
        self.label_71.setText(_translate("MainWindow", "Value 2", None))
        self.label_72.setText(_translate("MainWindow", "Value 3", None))
        self.label_73.setText(_translate("MainWindow", "Value 4", None))
        self.label_74.setText(_translate("MainWindow", "ncs", None))
        self.label_75.setText(_translate("MainWindow", "[", None))
        self.label_76.setText(_translate("MainWindow", "(", None))
        self.label_77.setText(_translate("MainWindow", "0", None))
        self.label_78.setText(_translate("MainWindow", ",", None))
        self.label_79.setText(_translate("MainWindow", "0", None))
        self.label_83.setText(_translate("MainWindow", ",", None))
        self.label_84.setText(_translate("MainWindow", "0", None))
        self.label_88.setText(_translate("MainWindow", ",", None))
        self.label_89.setText(_translate("MainWindow", "0", None))
        self.label_90.setText(_translate("MainWindow", ")", None))
        self.label_91.setText(_translate("MainWindow", "]", None))
        self.num_of_components_button = QtGui.QPushButton(self.NumberComponents)
        self.set_module_button(self.verticalLayout_17, self.num_of_components_button)
        try:
            self.num_of_components_button.clicked.connect(
                lambda: self.pysat_fun.get_number_components([int(self.create_model_spin.text()),
                                                              int(self.create_model_spin_2.text()),
                                                              int(self.create_model_spin_3.text()),
                                                              int(self.create_model_spin_4.text())]))
        except:
            pass

    def y_variable(self, MainWindow):
        self.y_variable = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.y_variable.setFont(font)
        self.y_variable.setObjectName(_fromUtf8("y_variable"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.y_variable)
        self.verticalLayout_25.setMargin(11)
        self.verticalLayout_25.setSpacing(6)
        self.verticalLayout_25.setObjectName(_fromUtf8("CrossValid"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setMargin(11)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_14 = QtGui.QLabel(self.y_variable)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_11.addWidget(self.label_14)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setMargin(11)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.elementNameLine = QtGui.QLineEdit(self.y_variable)
        self.elementNameLine.setObjectName(_fromUtf8("elementNameLine"))
        self.verticalLayout_12.addWidget(self.elementNameLine)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_25.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8.addWidget(self.y_variable)
        self.y_variable.raise_()
        self.y_variable.setTitle(_translate("MainWindow", "Y Variable", None))
        self.label_14.setText(_translate("MainWindow", "Element Name", None))
        self.y_variable_button = QtGui.QPushButton(self.y_variable)
        self.set_module_button(self.verticalLayout_25, self.y_variable_button)
        try:
            self.y_variable_button.clicked.connect(lambda: self.pysat_fun.set_element_name(self.elementNameLine.text()))
        except:
            pass

    def interpolated(self, MainWindow):
        self.Interpolated = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Interpolated.setFont(font)
        self.Interpolated.setObjectName(_fromUtf8("Interpolated"))
        self.verticalLayout_29 = QtGui.QVBoxLayout(self.Interpolated)
        self.verticalLayout_29.setMargin(11)
        self.verticalLayout_29.setSpacing(6)
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setMargin(11)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setMargin(11)
        self.verticalLayout_23.setSpacing(6)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.label_16 = QtGui.QLabel(self.Interpolated)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_23.addWidget(self.label_16)
        self.horizontalLayout_12.addLayout(self.verticalLayout_23)
        self.verticalLayout_29.addLayout(self.horizontalLayout_12)
        self.verticalLayout_8.addWidget(self.Interpolated)
        self.Interpolated.setTitle(_translate("MainWindow", "Interpolated", None))
        self.label_16.setText(_translate("MainWindow", "Interpolated unknown data to known data", None))
        self.pysat_fun.set_interp()

    def masked(self, MainWindow):
        self.masked = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.masked.setFont(font)
        self.masked.setObjectName(_fromUtf8("masked"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.masked)
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setMargin(11)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setMargin(11)
        self.verticalLayout_17.setSpacing(6)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_9 = QtGui.QLabel(self.masked)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_17.addWidget(self.label_9)
        self.horizontalLayout_13.addLayout(self.verticalLayout_17)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setMargin(11)
        self.verticalLayout_22.setSpacing(6)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.lineEdit_10 = QtGui.QLineEdit(self.masked)
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.verticalLayout_22.addWidget(self.lineEdit_10)
        self.horizontalLayout_13.addLayout(self.verticalLayout_22)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setMargin(11)
        self.verticalLayout_24.setSpacing(6)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.fullDataBaseButton_4 = QtGui.QToolButton(self.masked)
        self.fullDataBaseButton_4.setObjectName(_fromUtf8("fullDataBaseButton_4"))
        self.verticalLayout_24.addWidget(self.fullDataBaseButton_4)
        self.horizontalLayout_13.addLayout(self.verticalLayout_24)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.label_16 = QtGui.QLabel(self.masked)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout.addWidget(self.label_16)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_8.addWidget(self.masked)
        self.masked.setTitle(_translate("MainWindow", "Mask", None))
        self.label_9.setText(_translate("MainWindow", "Maskfile", None))
        self.lineEdit_10.setText(_translate("MainWindow", "*.csv", None))
        self.fullDataBaseButton_4.setText(_translate("MainWindow", "...", None))
        self.label_16.setText(_translate("MainWindow", "Mask was applied to unknown and known data", None))
        try:
            self.fullDataBaseButton_4.clicked.connect(lambda: pysat_ui.on_maskFile_clicked(self, self.lineEdit_10))
        except:
            pass

    def regression_train(self, MainWindow):
        self.regression_train = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.regression_train.setFont(font)
        self.regression_train.setObjectName(_fromUtf8("regression_train"))
        self.regression_vlayout = QtGui.QVBoxLayout(self.regression_train)
        self.regression_vlayout.setObjectName(_fromUtf8("regression_vlayout"))
        # choose data
        self.regression_choosedata_hlayout = QtGui.QHBoxLayout()
        self.regression_choosedata_hlayout.setObjectName(_fromUtf8("regression_choosedata_hlayout"))
        self.regression_train_choosedata_label = QtGui.QLabel(self.regression_train)
        self.regression_train_choosedata_label.setObjectName(_fromUtf8("regression_train_choosedata_label"))
        self.regression_choosedata_hlayout.addWidget(self.regression_train_choosedata_label)
        self.regression_choosedata = QtGui.QComboBox(self.regression_train)
        self.regression_choosedata.setIconSize(QtCore.QSize(50, 20))
        self.regression_choosedata.setObjectName(_fromUtf8("regression_choosedata"))
        self.regression_choosedata.addItem(_fromUtf8(""))
        self.regression_choosedata.addItem(_fromUtf8(""))
        self.regression_choosedata_hlayout.addWidget(self.regression_choosedata)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.regression_choosedata_hlayout.addItem(spacerItem)
        self.regression_vlayout.addLayout(self.regression_choosedata_hlayout)
        # choose variables
        self.regression_choosevars_hlayout = QtGui.QHBoxLayout()
        self.regression_choosevars_hlayout.setObjectName(_fromUtf8("regression_choosevars_hlayout"))
        self.regression_train_choosex_label = QtGui.QLabel(self.regression_train)
        self.regression_train_choosex_label.setObjectName(_fromUtf8("regression_train_choosex_label"))
        self.regression_choosevars_hlayout.addWidget(self.regression_train_choosex_label)
        self.regression_train_choosex = QtGui.QListWidget(self.regression_train)
        self.regression_train_choosex.setObjectName(_fromUtf8("regression_train_choosex"))
        item = QtGui.QListWidgetItem()
        self.regression_train_choosex.addItem(item)
        self.regression_choosevars_hlayout.addWidget(self.regression_train_choosex)
        self.regression_train_choosey_label = QtGui.QLabel(self.regression_train)
        self.regression_train_choosey_label.setObjectName(_fromUtf8("regression_train_choosey_label"))
        self.regression_choosevars_hlayout.addWidget(self.regression_train_choosey_label)
        self.regression_train_choosey = QtGui.QListWidget(self.regression_train)
        self.regression_train_choosey.setObjectName(_fromUtf8("regression_train_choosey"))
        item = QtGui.QListWidgetItem()
        self.regression_train_choosey.addItem(item)
        self.regression_choosevars_hlayout.addWidget(self.regression_train_choosey)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.regression_choosevars_hlayout.addItem(spacerItem1)
        self.regression_vlayout.addLayout(self.regression_choosevars_hlayout)
        # choose regression algorithm
        self.regression_choosealg_hlayout = QtGui.QHBoxLayout()
        self.regression_choosealg_hlayout.setObjectName(_fromUtf8("regression_choosealg_hlayout"))
        self.regression_choosealg_label = QtGui.QLabel(self.regression_train)
        self.regression_choosealg_label.setObjectName(_fromUtf8("regression_choosealg_label"))
        self.regression_choosealg_hlayout.addWidget(self.regression_choosealg_label)
        self.regression_choosealg = QtGui.QComboBox(self.regression_train)
        self.regression_choosealg.setIconSize(QtCore.QSize(50, 20))
        self.regression_choosealg.setObjectName(_fromUtf8("regression_choosealg"))
        self.regression_choosealg.addItem(_fromUtf8(""))
        self.regression_choosealg.addItem(_fromUtf8(""))
        self.regression_choosealg.addItem(_fromUtf8(""))
        self.regression_choosealg_hlayout.addWidget(self.regression_choosealg)
        regression_choosealg_spacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.regression_choosealg_hlayout.addItem(regression_choosealg_spacer)
        self.regression_vlayout.addLayout(self.regression_choosealg_hlayout)
        # pls options
        #        self.pls_hlayout = QtGui.QHBoxLayout()
        #        self.pls_hlayout.setObjectName(_fromUtf8("pls_hlayout"))
        #        self.pls_nc_label = QtGui.QLabel(self.regression_train)
        #        self.pls_nc_label.setObjectName(_fromUtf8("pls_nc_label"))
        #        self.pls_hlayout.addWidget(self.pls_nc_label)
        #        self.pls_nc_spin = QtGui.QSpinBox(self.regression_train)
        #        self.pls_nc_spin.setObjectName(_fromUtf8("pls_nc_spin"))
        #        self.pls_hlayout.addWidget(self.pls_nc_spin)
        #        pls_spacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        #        self.pls_hlayout.addItem(pls_spacer)
        #        self.regression_vlayout.addLayout(self.pls_hlayout)
        # gp options
        #        self.gp_vlayout = QtGui.QVBoxLayout()
        #        self.gp_vlayout.setObjectName(_fromUtf8("gp_vlayout"))
        #        self.gp_dim_red_hlayout = QtGui.QHBoxLayout()
        #        self.gp_dim_red_hlayout.setObjectName(_fromUtf8("gp_dim_red_hlayout"))
        #        self.gp_dim_red_label = QtGui.QLabel(self.regression_train)
        #        self.gp_dim_red_label.setObjectName(_fromUtf8("gp_dim_red_label"))
        #        self.gp_dim_red_hlayout.addWidget(self.gp_dim_red_label)
        #        self.gp_dim_red_combobox = QtGui.QComboBox(self.regression_train)
        #        self.gp_dim_red_combobox.setObjectName(_fromUtf8("gp_dim_red_combobox"))
        #        self.gp_dim_red_combobox.addItem(_fromUtf8(""))
        #        self.gp_dim_red_combobox.addItem(_fromUtf8(""))
        #        self.gp_dim_red_combobox.addItem(_fromUtf8(""))
        #        self.gp_dim_red_combobox.addItem(_fromUtf8(""))
        #        self.gp_dim_red_hlayout.addWidget(self.gp_dim_red_combobox)
        #        self.gp_vlayout.addLayout(self.gp_dim_red_hlayout)
        #        self.gp_rand_starts_hlayout = QtGui.QHBoxLayout()
        #        self.gp_rand_starts_hlayout.setObjectName(_fromUtf8("gp_rand_starts_hlayout"))
        #        self.gp_rand_starts_label = QtGui.QLabel(self.regression_train)
        #        self.gp_rand_starts_label.setObjectName(_fromUtf8("gp_rand_starts_label"))
        #        self.gp_rand_starts_hlayout.addWidget(self.gp_rand_starts_label)
        #        self.gp_rand_starts_spin = QtGui.QSpinBox(self.regression_train)
        #        self.gp_rand_starts_spin.setObjectName(_fromUtf8("gp_rand_starts_spin"))
        #        self.gp_rand_starts_hlayout.addWidget(self.gp_rand_starts_spin)
        #        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        #        self.gp_rand_starts_hlayout.addItem(spacerItem4)
        #        self.gp_vlayout.addLayout(self.gp_rand_starts_hlayout)
        #        self.gp_theta_hlayout = QtGui.QHBoxLayout()
        #        self.gp_theta_hlayout.setObjectName(_fromUtf8("gp_theta_hlayout"))
        #        self.gp_theta0_label = QtGui.QLabel(self.regression_train)
        #        self.gp_theta0_label.setObjectName(_fromUtf8("gp_theta0_label"))
        #        self.gp_theta_hlayout.addWidget(self.gp_theta0_label)
        #        self.gp_theta0_spin = QtGui.QDoubleSpinBox(self.regression_train)
        #        self.gp_theta0_spin.setObjectName(_fromUtf8("gp_theta0_spin"))
        #        self.gp_theta_hlayout.addWidget(self.gp_theta0_spin)
        #        self.gp_thetaL_label = QtGui.QLabel(self.regression_train)
        #        self.gp_thetaL_label.setObjectName(_fromUtf8("gp_thetaL_label"))
        #        self.gp_theta_hlayout.addWidget(self.gp_thetaL_label)
        #        self.gp_thetaL_spin = QtGui.QDoubleSpinBox(self.regression_train)
        #        self.gp_thetaL_spin.setObjectName(_fromUtf8("gp_thetaL_spin"))
        #        self.gp_theta_hlayout.addWidget(self.gp_thetaL_spin)
        #        self.gp_thetaU_label = QtGui.QLabel(self.regression_train)
        #        self.gp_thetaU_label.setObjectName(_fromUtf8("gp_thetaU_label"))
        #        self.gp_theta_hlayout.addWidget(self.gp_thetaU_label)
        #        self.gp_thetaU_spin = QtGui.QDoubleSpinBox(self.regression_train)
        #        self.gp_thetaU_spin.setObjectName(_fromUtf8("gp_thetaU_spin"))
        #        self.gp_theta_hlayout.addWidget(self.gp_thetaU_spin)
        #        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        #        self.gp_theta_hlayout.addItem(spacerItem5)
        #        self.gp_vlayout.addLayout(self.gp_theta_hlayout)
        #        self.regression_vlayout.addLayout(self.gp_vlayout)
        # ransac options
        #        self.regression_ransac_checkbox = QtGui.QCheckBox(self.regression_train)
        #        self.regression_ransac_checkbox.setObjectName(_fromUtf8("regression_ransac_checkbox"))
        #        self.regression_vlayout.addWidget(self.regression_ransac_checkbox)
        #        self.ransac_vlayout = QtGui.QVBoxLayout()
        #        self.ransac_vlayout.setObjectName(_fromUtf8("ransac_vlayout"))
        #        self.ransac_lossfunc_hlayout = QtGui.QHBoxLayout()
        #        self.ransac_lossfunc_hlayout.setObjectName(_fromUtf8("ransac_lossfunc_hlayout"))
        #        self.ransac_lossfunc_label = QtGui.QLabel(self.regression_train)
        #        self.ransac_lossfunc_label.setObjectName(_fromUtf8("ransac_lossfunc_label"))
        #        self.ransac_lossfunc_hlayout.addWidget(self.ransac_lossfunc_label)
        #        self.ransac_lossfunc_combobox = QtGui.QComboBox(self.regression_train)
        #        self.ransac_lossfunc_combobox.setObjectName(_fromUtf8("ransac_lossfunc_combobox"))
        #        self.ransac_lossfunc_combobox.addItem(_fromUtf8(""))
        #        self.ransac_lossfunc_combobox.addItem(_fromUtf8(""))
        #        self.ransac_lossfunc_hlayout.addWidget(self.ransac_lossfunc_combobox)
        #        ransac_lossfunc_spacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        #        self.ransac_lossfunc_hlayout.addItem(ransac_lossfunc_spacer)
        #        self.ransac_vlayout.addLayout(self.ransac_lossfunc_hlayout)
        #        self.ransac_thresh_hlayout = QtGui.QHBoxLayout()
        #        self.ransac_thresh_hlayout.setObjectName(_fromUtf8("ransac_thresh_hlayout"))
        #        self.ransac_thresh_label = QtGui.QLabel(self.regression_train)
        #        self.ransac_thresh_label.setObjectName(_fromUtf8("ransac_thresh_label"))
        #        self.ransac_thresh_hlayout.addWidget(self.ransac_thresh_label)
        #        self.ransac_thresh_spin = QtGui.QDoubleSpinBox(self.regression_train)
        #        self.ransac_thresh_spin.setObjectName(_fromUtf8("ransac_thresh_spin"))
        #        self.ransac_thresh_hlayout.addWidget(self.ransac_thresh_spin)
        #        ransac_thresh_spacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        #        self.ransac_thresh_hlayout.addItem(ransac_thresh_spacer)
        #        self.ransac_vlayout.addLayout(self.ransac_thresh_hlayout)
        #        self.regression_vlayout.addLayout(self.ransac_vlayout)

        # train button
        self.regression_trainbutton_hlayout = QtGui.QHBoxLayout()
        self.regression_trainbutton_hlayout.setObjectName(_fromUtf8("regression_trainbutton_hlayout"))
        regression_trainbutton_spacer = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding,
                                                          QtGui.QSizePolicy.Minimum)
        self.regression_trainbutton_hlayout.addItem(regression_trainbutton_spacer)
        self.regression_trainbutton = QtGui.QPushButton(self.regression_train)
        self.regression_trainbutton.setObjectName(_fromUtf8("regression_trainbutton"))
        self.regression_trainbutton_hlayout.addWidget(self.regression_trainbutton)
        self.regression_vlayout.addLayout(self.regression_trainbutton_hlayout)

        self.verticalLayout_8.addWidget(self.regression_train)
        self.regression_train.raise_()

        self.regression_train.setTitle(_translate("regression_train", "Regression - Train", None))
        self.regression_train_choosedata_label.setText(_translate("regression_train", "Choose data:", None))

        self.regression_train_choosex.setItemText(0, _translate("regression_train", "Choose X Variables", None))
        self.regression_train_choosey.setItemText(0, _translate("regression_train", "Choose Y Variables", None))
        self.regression_train_choosealg.setItemText(0, _translate("regression_train", "Choose Algorithm", None))
        self.regression_train_choosealg.setItemText(1, _translate("regression_train", "PLS", None))
        self.regression_train_choosealg.setItemText(2, _translate("regression_train", "GP", None))
        self.regression_train_choosealg.setItemText(3, _translate("regression_train", "Others coming soon...", None))
        self.regression_train_ransac_checkbox.setText(_translate("regression_train", "RANSAC", None))
        self.regression_train_trainbutton.setText(_translate("regression_train", "Train Regression", None))

    def stratified_folds(self, MainWindow):
        self.strat_folds = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.strat_folds.setFont(font)
        self.strat_folds.setObjectName(_fromUtf8("Stratified Folds"))
        self.strat_folds_vlayout = QtGui.QVBoxLayout(self.strat_folds)
        self.strat_folds_vlayout.setObjectName(_fromUtf8("strat_folds_vlayout"))
        self.strat_folds_choose_data_label = QtGui.QLabel(self.strat_folds)
        self.strat_folds_choose_data_label.setObjectName(_fromUtf8("strat_folds_choose_data_label"))
        self.strat_folds_vlayout.addWidget(self.strat_folds_choose_data_label)
        datachoices = self.pysat_fun.datakeys
        if datachoices == []:
            print('No data has been loaded!')

        self.strat_folds_choose_data = make_combobox(datachoices)
        self.strat_folds_vlayout.addWidget(self.strat_folds_choose_data)
        self.strat_folds_choose_var_label = QtGui.QLabel(self.strat_folds)
        self.strat_folds_choose_var_label.setObjectName(_fromUtf8("strat_folds_choose_var_label"))
        self.strat_folds_vlayout.addWidget(self.strat_folds_choose_var_label)
        varchoices = self.pysat_fun.data[self.strat_folds_choose_data.currentText()].df['meta'].columns.values
        self.strat_folds_choose_var = make_combobox(varchoices)
        self.strat_folds_vlayout.addWidget(self.strat_folds_choose_var)
        self.strat_folds_choose_data.activated[int].connect(self.strat_fold_change_vars)
        self.strat_folds_hlayout = QtGui.QHBoxLayout()
        self.strat_folds_hlayout.setObjectName(_fromUtf8("strat_folds_hlayout"))
        self.nfolds_label = QtGui.QLabel(self.strat_folds)
        self.nfolds_label.setObjectName(_fromUtf8("nfolds_label"))
        self.strat_folds_hlayout.addWidget(self.nfolds_label)
        self.nfolds_spin = QtGui.QSpinBox(self.strat_folds)
        self.nfolds_spin.setObjectName(_fromUtf8("nfolds_spin"))
        self.nfolds_spin.setMinimum(1)
        self.strat_folds_hlayout.addWidget(self.nfolds_spin)
        self.test_fold_label = QtGui.QLabel(self.strat_folds)
        self.test_fold_label.setObjectName(_fromUtf8("test_fold_label"))
        self.strat_folds_hlayout.addWidget(self.test_fold_label)
        foldchoices = ['1']
        self.choose_test_fold = make_combobox(foldchoices)
        self.choose_test_fold.setObjectName(_fromUtf8("choose_test_fold"))
        self.nfolds_spin.valueChanged.connect(self.strat_fold_change_testfolds)
        self.strat_folds_hlayout.addWidget(self.choose_test_fold)
        self.spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.strat_folds_hlayout.addItem(self.spacerItem)
        self.create_folds = QtGui.QPushButton(self.strat_folds)
        self.create_folds.setObjectName(_fromUtf8("create_folds"))
        self.create_folds.setText(_translate("strat_folds", "Create Folds", None))
        self.strat_folds_hlayout.addWidget(self.create_folds)
        self.strat_folds_vlayout.addLayout(self.strat_folds_hlayout)
        self.verticalLayout_8.addWidget(self.strat_folds)
        self.strat_folds.raise_()
        self.strat_folds.setTitle(_translate("MainWindow", "Stratified Folds", None))
        self.nfolds_label.setText(_translate("strat_folds", "N folds", None))
        self.test_fold_label.setText(_translate("strat_folds", "Test Fold", None))
        self.create_folds.setText(_translate("strat_folds", "Create Folds", None))
        self.strat_folds_choose_data_label.setText(_translate("strat_folds", "Choose data to stratify:", None))
        self.strat_folds_choose_var_label.setText(_translate("strat_folds", "Choose variable on which to sort:", None))
        try:
            self.create_folds.clicked.connect(
                lambda: self.pysat_fun.do_strat_folds(datakey=str(self.strat_folds_choose_data.currentText()),
                                                      nfolds=int(self.nfolds_spin.text()),
                                                      testfold=int(self.choose_test_fold.currentText()),
                                                      colname=('meta', self.strat_folds_choose_var.currentText())))
        except:
            print('There was a problem with creating stratified folds...')


            ####These functions below are private and add functionality to the UI

    def set_module_button(self, QVBoxLayout, PushButtonName):
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        PushButtonName.setObjectName(_fromUtf8("run_module_files"))
        self.horizontalLayout.addWidget(PushButtonName)
        QVBoxLayout.addLayout(self.horizontalLayout)
        PushButtonName.setText(_translate("MainWindow", "Run Module", None))

    def menu_item_shortcuts(self):
        self.actionExit.setShortcut("ctrl+Q")

    def menu_item_functions(self, MainWindow):
        self.actionSet_output_location.triggered.connect(lambda: pysat_ui.output_folder(self, MainWindow))
        self.actionLoad_Unknown_Data.triggered.connect(lambda: pysat_ui.unknown_data(self, MainWindow))
        self.actionLoad_reference_Data.triggered.connect(lambda: pysat_ui.reference_data(self, MainWindow))
        self.actionNormalization.triggered.connect(lambda: pysat_ui.normalization(self, MainWindow))
        self.actionInterpolate.triggered.connect(lambda: pysat_ui.interpolated(self, MainWindow))
        self.actionApply_Mask.triggered.connect(lambda: pysat_ui.masked(self, MainWindow))
        self.actionStratified_Folds.triggered.connect(lambda: pysat_ui.stratified_folds(self, MainWindow))
        self.actionTrain.triggered.connect(lambda: pysat_ui.regression_train(self, MainWindow))
        self.actionSave_Current_Workflow.triggered.connect(lambda: pysat_ui.saveworkflow(MainWindow))

    def saveworkflow(self):
        # TODO save the current window's data into a save file
        pysat_ui.open_wait_box(self)

    def openworkflow(self):
        # TODO open file dialog
        self.filename = QFileDialog.getOpenFileName(self, "Open a Workflow File", '.', "(*.wrf)")

    """
    Opening Files
    """

    def on_maskFile_clicked(self, lineEdit):
        filename = QFileDialog.getOpenFileName(None, "Open Mask File", '.', "(*.csv)")
        lineEdit.setText(filename)
        if lineEdit.text() == "":
            lineEdit.setText("*.csv")
        else:
            self.open_wait_box()
            self.list_of_functions.append(lambda: self.pysat_fun.set_file_maskfile(filename))
            self.list_of_functions.append(lambda: self.pysat_fun.set_mask())
            self.close_wait_box()

    def on_getDataButton_clicked(self, lineEdit, key):
        filename = QFileDialog.getOpenFileName(None, "Open Uknown Data File", '.', "(*.csv)")
        lineEdit.setText(filename)
        if lineEdit.text() == "":
            lineEdit.setText("*.csv")
        self.open_wait_box()
        self.pysat_fun.get_data(filename, key)
        self.close_wait_box()

    def on_outPutLocationButton_clicked(self, lineEdit):
        filename = QFileDialog.getExistingDirectory(None, "Select Output Directory", '.')
        lineEdit.setText(filename)
        if lineEdit.text() == "":
            lineEdit.setText("*/*")
        self.open_wait_box()
        self.pysat_fun.set_file_outpath(filename)
        self.close_wait_box()

    """
    Ok Button Clicked
    """

    def on_okButton_clicked(self):
        for i in range(10):
            self.addFunc[i]
            self.addParam[i]
        self.pysat_fun.set_sm()
        self.pysat_fun.get_sm_fit()
        self.pysat_fun.get_plots()

    def strat_fold_change_vars(self):
        self.strat_folds_choose_var.clear()
        choices = self.pysat_fun.data[self.strat_folds_choose_data.currentText()].df['meta'].columns.values
        print(choices)
        self.strat_folds_choose_var.addItems(choices)

    def strat_fold_change_testfolds(self):
        self.choose_test_fold.clear()
        choices = list(map(str, list(range(1, self.nfolds_spin.value() + 1))))
        print(choices)
        self.choose_test_fold.addItems(choices)

    """
    Message Box that will appear, to let the user know that some work is being done, and that
    the UI will be non-responsive for a sec.
    """

    def open_wait_box(self):
        self.splash_pix = QPixmap('27-512.png')
        self.splash = QSplashScreen(self.splash_pix, QtCore.Qt.WindowStaysOnTopHint)
        self.splash.show()

    def close_wait_box(self):
        self.splash.close()


def make_combobox(choices):
    combo = QtGui.QComboBox()
    for i, choice in enumerate(choices):
        combo.addItem(_fromUtf8(""))
        combo.setItemText(i, _translate('', choice, None))

    return combo

